# Generated by Django 5.0.14 on 2026-03-05 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kanban', '0082_board_archived_at_board_is_archived'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_type', models.CharField(choices=[('decision', 'Decision Made'), ('lesson', 'Lesson Learned'), ('risk_event', 'Risk Event'), ('outcome', 'Project Outcome'), ('conflict_resolution', 'Conflict Resolution'), ('scope_change', 'Scope Change'), ('milestone', 'Milestone Reached'), ('ai_recommendation', 'AI Recommendation'), ('manual_log', 'Manual Decision Log')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('context_data', models.JSONField(blank=True, default=dict)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_auto_captured', models.BooleanField(default=True)),
                ('source_object_type', models.CharField(blank=True, default='', max_length=50)),
                ('source_object_id', models.IntegerField(blank=True, null=True)),
                ('importance_score', models.FloatField(default=0.5)),
                ('board', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memory_nodes', to='kanban.board')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('mission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kanban.mission')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MemoryConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_type', models.CharField(choices=[('caused', 'Caused'), ('similar_to', 'Similar To'), ('led_to', 'Led To'), ('prevented', 'Prevented'), ('repeated_from', 'Repeated From Past Project')], max_length=30)),
                ('reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_generated', models.BooleanField(default=True)),
                ('from_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_connections', to='knowledge_graph.memorynode')),
                ('to_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_connections', to='knowledge_graph.memorynode')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationalMemoryQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.TextField()),
                ('response_json', models.JSONField(default=dict)),
                ('asked_at', models.DateTimeField(auto_now_add=True)),
                ('was_helpful', models.BooleanField(null=True)),
                ('asked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('nodes_referenced', models.ManyToManyField(blank=True, to='knowledge_graph.memorynode')),
            ],
            options={
                'ordering': ['-asked_at'],
            },
        ),
        migrations.AddIndex(
            model_name='memorynode',
            index=models.Index(fields=['board', '-importance_score'], name='knowledge_g_board_i_3b5101_idx'),
        ),
        migrations.AddIndex(
            model_name='memorynode',
            index=models.Index(fields=['node_type'], name='knowledge_g_node_ty_fb2723_idx'),
        ),
        migrations.AddIndex(
            model_name='memorynode',
            index=models.Index(fields=['source_object_type', 'source_object_id'], name='knowledge_g_source__05ba49_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='memoryconnection',
            unique_together={('from_node', 'to_node', 'connection_type')},
        ),
    ]
