# Generated by Django 5.2.3 on 2026-06-01 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_graph', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memorynode',
            name='is_org_wide',
            field=models.BooleanField(default=False, help_text='If True, visible to everyone in the organization, not just board members. Only Owners/Org Admins can set this.'),
        ),
        migrations.AlterField(
            model_name='memorynode',
            name='node_type',
            field=models.CharField(choices=[('decision', 'Decision Made'), ('lesson', 'Lesson Learned'), ('risk_event', 'Risk Event'), ('outcome', 'Project Outcome'), ('conflict_resolution', 'Conflict Resolution'), ('scope_change', 'Scope Change'), ('milestone', 'Milestone Reached'), ('ai_recommendation', 'AI Recommendation'), ('manual_log', 'Manual Decision Log'), ('note', 'Note')], max_length=30),
        ),
    ]
