# Generated by Django 5.2.3 on 2026-06-01 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_graph', '0002_memorynode_is_org_wide_alter_memorynode_node_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='memorynode',
            name='gap_questions',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memorynode',
            name='gaps_analyzed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='memorynode',
            name='has_gaps',
            field=models.BooleanField(default=False),
        ),
    ]
