# Generated by Django 5.2.3 on 2026-06-02 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_graph', '0003_memorynode_gap_questions_memorynode_gaps_analyzed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memorynode',
            name='gap_enrichment_count',
            field=models.IntegerField(default=0),
        ),
    ]
