# Generated by Django 5.2.3 on 2026-06-02 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_graph', '0004_memorynode_gap_enrichment_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='memorynode',
            name='gap_questions_original',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
