# Generated by Django 5.2.3 on 2026-06-23 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_graph', '0006_backfill_gap_questions_original'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memorynode',
            name='is_org_wide',
            field=models.BooleanField(default=False, help_text="If True, visible to everyone who collaborates in this board's workspace (workspace-wide), not just members of this board. Only the board owner can set this."),
        ),
    ]
