# Generated by Django 5.2.3 on 2026-07-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_graph', '0007_alter_memorynode_is_org_wide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memorynode',
            name='node_type',
            field=models.CharField(choices=[('decision', 'Decision Made'), ('lesson', 'Lesson Learned'), ('risk_event', 'Risk Event'), ('outcome', 'Project Outcome'), ('conflict_resolution', 'Conflict Resolution'), ('scope_change', 'Scope Change'), ('milestone', 'Milestone Reached'), ('ai_recommendation', 'AI Recommendation'), ('manual_log', 'Manual Log'), ('note', 'Note')], max_length=30),
        ),
    ]
