# Generated by Django 5.2.3 on 2025-11-08 18:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kanban', '0031_alter_task_workload_impact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Friendly name for this webhook (e.g., 'Slack Notifications')", max_length=100)),
                ('url', models.URLField(help_text='URL to send webhook POST requests to', max_length=500, validators=[django.core.validators.URLValidator()])),
                ('events', models.JSONField(default=list, help_text="List of event types to trigger this webhook (e.g., ['task.created', 'task.updated'])")),
                ('is_active', models.BooleanField(default=True, help_text='Whether this webhook is currently active')),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('failed', 'Failed'), ('disabled', 'Disabled')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_triggered', models.DateTimeField(blank=True, help_text='Last time this webhook was triggered', null=True)),
                ('timeout_seconds', models.IntegerField(default=10, help_text='HTTP request timeout in seconds')),
                ('max_retries', models.IntegerField(default=3, help_text='Maximum number of retry attempts on failure')),
                ('retry_delay_seconds', models.IntegerField(default=60, help_text='Delay between retry attempts in seconds')),
                ('total_deliveries', models.IntegerField(default=0, help_text='Total number of delivery attempts')),
                ('successful_deliveries', models.IntegerField(default=0, help_text='Number of successful deliveries')),
                ('failed_deliveries', models.IntegerField(default=0, help_text='Number of failed deliveries')),
                ('consecutive_failures', models.IntegerField(default=0, help_text='Number of consecutive failures (resets on success)')),
                ('secret', models.CharField(blank=True, help_text='Optional secret key for HMAC signature verification', max_length=64)),
                ('custom_headers', models.JSONField(blank=True, default=dict, help_text='Custom HTTP headers to include in webhook requests')),
                ('board', models.ForeignKey(help_text='Board to monitor for events', on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='kanban.board')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_webhooks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('payload', models.JSONField(help_text='Event data sent to webhook')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('success', 'Success'), ('failed', 'Failed'), ('retrying', 'Retrying')], default='pending', max_length=20)),
                ('response_status_code', models.IntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True)),
                ('response_time_ms', models.IntegerField(blank=True, help_text='Response time in milliseconds', null=True)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='webhooks.webhook')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, max_length=50)),
                ('object_id', models.IntegerField(help_text='ID of the object that triggered the event (task, comment, etc.)')),
                ('data', models.JSONField(help_text='Event data snapshot')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('webhooks_triggered', models.IntegerField(default=0)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_events', to='kanban.board')),
                ('triggered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_webhook_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='webhook',
            index=models.Index(fields=['board', 'is_active'], name='webhooks_we_board_i_b87f73_idx'),
        ),
        migrations.AddIndex(
            model_name='webhook',
            index=models.Index(fields=['status'], name='webhooks_we_status_2bc765_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(fields=['webhook', '-created_at'], name='webhooks_we_webhook_8d7634_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(fields=['status'], name='webhooks_we_status_6d768a_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(fields=['next_retry_at'], name='webhooks_we_next_re_8ddc98_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['board', '-created_at'], name='webhooks_we_board_i_4c617d_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['event_type', '-created_at'], name='webhooks_we_event_t_44a6a9_idx'),
        ),
    ]
