# Generated by Django 5.2.3 on 2026-06-03 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhook',
            name='provider',
            field=models.CharField(blank=True, default='', help_text='Integration preset this webhook targets (slack, discord, teams, github, pagerduty, ...). Blank = auto-detect from the URL host.', max_length=20),
        ),
        migrations.AddField(
            model_name='webhook',
            name='provider_config',
            field=models.JSONField(blank=True, default=dict, help_text="Provider-specific config the payload body needs but the URL/headers can't carry (e.g. PagerDuty routing_key, GitHub event_type)."),
        ),
    ]
