# Generated by Django 5.2.3 on 2025-11-03 19:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_completed_wizard_and_more'),
        ('kanban', '0028_task_dependencies_task_start_date'),
        ('wiki', '0002_alter_wikicategory_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingnotes',
            name='extraction_results',
            field=models.JSONField(blank=True, default=dict, help_text='AI extraction results including tasks and metadata'),
        ),
        migrations.AddField(
            model_name='meetingnotes',
            name='meeting_context',
            field=models.JSONField(blank=True, default=dict, help_text='Additional meeting context and metadata'),
        ),
        migrations.AddField(
            model_name='meetingnotes',
            name='meeting_type',
            field=models.CharField(choices=[('standup', 'Daily Standup'), ('planning', 'Sprint Planning'), ('review', 'Review Meeting'), ('retrospective', 'Retrospective'), ('general', 'General Meeting')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='meetingnotes',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meetingnotes',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='meetingnotes',
            name='tasks_created_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meetingnotes',
            name='tasks_extracted_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meetingnotes',
            name='transcript_file',
            field=models.FileField(blank=True, help_text='Uploaded transcript file (txt, pdf, docx)', null=True, upload_to='meeting_transcripts/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='meetingnotes',
            name='transcript_text',
            field=models.TextField(blank=True, help_text='Raw meeting transcript'),
        ),
        migrations.AlterField(
            model_name='meetingnotes',
            name='content',
            field=models.TextField(help_text='Markdown supported - manual notes or AI-generated'),
        ),
        migrations.AddIndex(
            model_name='meetingnotes',
            index=models.Index(fields=['processing_status'], name='wiki_meetin_process_624101_idx'),
        ),
    ]
