# Generated by Django 5.2.3 on 2025-11-19 02:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_completed_wizard_and_more'),
        ('kanban', '0034_comment_kanban_comm_task_id_6e23a3_idx_and_more'),
        ('wiki', '0003_enhance_meeting_notes_with_transcript'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WikiMeetingAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('processing_error', models.TextField(blank=True, help_text='Error message if processing failed', null=True)),
                ('analysis_results', models.JSONField(blank=True, default=dict, help_text='\n        Complete AI analysis including:\n        - meeting_summary: {title, summary, date_detected, participants, meeting_type, confidence}\n        - action_items: [{title, description, priority, assignee, due_date, etc.}]\n        - decisions: [{decision, context, impact, requires_action}]\n        - blockers: [{blocker, severity, resolution, owner}]\n        - risks: [{risk, impact, probability, mitigation}]\n        - key_topics: [list of main topics]\n        - follow_ups: [{type, description, timeframe, participants}]\n        - metadata: {counts, sentiment, notes}\n    ')),
                ('action_items_count', models.IntegerField(default=0, help_text='Number of action items extracted')),
                ('decisions_count', models.IntegerField(default=0, help_text='Number of decisions identified')),
                ('blockers_count', models.IntegerField(default=0, help_text='Number of blockers found')),
                ('risks_count', models.IntegerField(default=0, help_text='Number of risks identified')),
                ('tasks_created_count', models.IntegerField(default=0, help_text='Number of tasks created from this analysis')),
                ('content_hash', models.CharField(help_text='Hash of content analyzed (to detect changes)', max_length=64)),
                ('ai_model_version', models.CharField(default='gemini-pro', help_text='AI model used', max_length=50)),
                ('confidence_score', models.CharField(blank=True, help_text='Overall confidence: high/medium/low', max_length=20, null=True)),
                ('user_reviewed', models.BooleanField(default=False, help_text='Has user reviewed the analysis?')),
                ('user_notes', models.TextField(blank=True, help_text='User notes about the analysis', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wiki_meeting_analyses', to='accounts.organization')),
                ('processed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_meeting_analyses', to=settings.AUTH_USER_MODEL)),
                ('wiki_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_analyses', to='wiki.wikipage')),
            ],
            options={
                'verbose_name': 'Wiki Meeting Analysis',
                'verbose_name_plural': 'Wiki Meeting Analyses',
                'ordering': ['-processed_at'],
            },
        ),
        migrations.CreateModel(
            name='WikiMeetingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_item_index', models.IntegerField(help_text='Index in the action_items array')),
                ('action_item_data', models.JSONField(default=dict, help_text='Original AI-extracted action item data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_modified', models.BooleanField(default=False, help_text='Did user modify before creating?')),
                ('modifications_note', models.TextField(blank=True, help_text='What was changed from AI suggestion', null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_meeting_tasks', to=settings.AUTH_USER_MODEL)),
                ('meeting_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to='wiki.wikimeetinganalysis')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wiki_meeting_source', to='kanban.task')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='wikimeetinganalysis',
            index=models.Index(fields=['wiki_page', '-processed_at'], name='wiki_wikime_wiki_pa_2c84f2_idx'),
        ),
        migrations.AddIndex(
            model_name='wikimeetinganalysis',
            index=models.Index(fields=['organization', 'processing_status'], name='wiki_wikime_organiz_02c462_idx'),
        ),
        migrations.AddIndex(
            model_name='wikimeetinganalysis',
            index=models.Index(fields=['processing_status'], name='wiki_wikime_process_70d114_idx'),
        ),
        migrations.AddIndex(
            model_name='wikimeetingtask',
            index=models.Index(fields=['meeting_analysis', 'task'], name='wiki_wikime_meeting_8055f2_idx'),
        ),
        migrations.AddIndex(
            model_name='wikimeetingtask',
            index=models.Index(fields=['task'], name='wiki_wikime_task_id_1a70fb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='wikimeetingtask',
            unique_together={('meeting_analysis', 'action_item_index')},
        ),
    ]
