# Generated by Django 5.2.3 on 2025-11-19 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0004_wikimeetinganalysis_wikimeetingtask_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikimeetinganalysis',
            name='ai_model_version',
            field=models.CharField(default='gemini-1.5-flash', help_text='AI model used', max_length=50),
        ),
    ]
