# Generated by Django 5.2.3 on 2025-11-19 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0006_alter_wikimeetinganalysis_ai_model_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikimeetinganalysis',
            name='ai_model_version',
            field=models.CharField(default='gemini-2.0-flash-exp', help_text='AI model used (Flash or Flash-Lite)', max_length=50),
        ),
    ]
