# Generated by Django 5.2.3 on 2025-11-19 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0007_alter_wikimeetinganalysis_ai_model_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikicategory',
            name='ai_assistant_type',
            field=models.CharField(choices=[('meeting', 'Meeting Analysis - For meeting notes, standups, sprint planning'), ('documentation', 'Documentation Assistant - For guides, references, tutorials'), ('none', 'No AI Assistant - Disable AI features for this category')], default='documentation', help_text='Which AI assistant to use for pages in this category', max_length=20),
        ),
    ]
