# Generated by Django 5.2.3 on 2025-12-27 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0008_wikicategory_ai_assistant_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikipage',
            name='transcript_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Metadata about imported transcript: {"source": "fireflies|otter|manual", "imported_at": "...", "meeting_date": "...", "duration_minutes": 0, "participants": [...]}'),
        ),
    ]
