# Generated by Django 5.2.3 on 2026-01-27 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_organization_nullable'),
        ('wiki', '0009_wikipage_transcript_metadata'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='wikipage',
            name='wiki_wikipa_organiz_7f30dd_idx',
        ),
        migrations.AlterUniqueTogether(
            name='wikicategory',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='wikipage',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='meetingnotes',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Organization (optional - MVP mode uses demo org)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_notes', to='accounts.organization'),
        ),
        migrations.AlterField(
            model_name='wikicategory',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Organization (optional - MVP mode uses demo org for all wiki data)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wiki_categories', to='accounts.organization'),
        ),
        migrations.AlterField(
            model_name='wikimeetinganalysis',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Organization (optional - MVP mode uses demo org)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wiki_meeting_analyses', to='accounts.organization'),
        ),
        migrations.AlterField(
            model_name='wikipage',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Organization (optional - MVP mode uses demo org for all wiki data)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wiki_pages', to='accounts.organization'),
        ),
    ]
