# Generated by Django 5.2.3 on 2026-02-28 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0010_organization_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='WikiTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(help_text='One-line summary shown on template cards', max_length=300)),
                ('category_name', models.CharField(help_text='Suggested WikiCategory name; auto-created for the org if it does not exist', max_length=100)),
                ('content', models.TextField(help_text='Full Markdown body pre-filled into the create form')),
                ('icon', models.CharField(default='file-alt', help_text='Font Awesome icon name (without fa- prefix)', max_length=50)),
                ('color', models.CharField(default='#3498db', help_text='Hex accent color for the card', max_length=7)),
                ('order', models.IntegerField(default=0, help_text='Display order in the gallery (lower = first)')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive templates are hidden from the gallery')),
            ],
            options={
                'verbose_name': 'Wiki Template',
                'verbose_name_plural': 'Wiki Templates',
                'ordering': ['order', 'name'],
            },
        ),
    ]
