# Generated by Django 5.2.3 on 2026-06-23 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0152_discoveryidea_workspace'),
        ('wiki', '0012_seed_wikitemplate_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingnotes',
            name='workspace',
            field=models.ForeignKey(blank=True, help_text='Workspace these notes belong to (scopes visibility).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_notes', to='kanban.workspace'),
        ),
        migrations.AddField(
            model_name='wikicategory',
            name='workspace',
            field=models.ForeignKey(blank=True, help_text='Workspace this category belongs to (scopes visibility).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wiki_categories', to='kanban.workspace'),
        ),
        migrations.AddField(
            model_name='wikipage',
            name='workspace',
            field=models.ForeignKey(blank=True, help_text='Workspace this page belongs to (scopes visibility).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wiki_pages', to='kanban.workspace'),
        ),
    ]
