# Generated by Django 5.2.3 on 2026-07-17 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0014_backfill_wiki_workspace'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='wikicategory',
            name='sandbox_owner',
            field=models.ForeignKey(blank=True, help_text='Owning demo user for sandbox-isolated copies; None for template/real rows.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sandbox_wiki_categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wikipage',
            name='sandbox_owner',
            field=models.ForeignKey(blank=True, help_text='Owning demo user for sandbox-isolated copies; None for template/real rows.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sandbox_wiki_pages', to=settings.AUTH_USER_MODEL),
        ),
    ]
