# Generated by Django 5.2.3 on 2026-07-21 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_userprofile_custom_ai_instructions_and_more'),
        ('kanban', '0166_customfielddefinition_sandbox_owner'),
        ('wiki', '0015_wikicategory_sandbox_owner_wikipage_sandbox_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WikiDocumentationAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('processing_error', models.TextField(blank=True, help_text='Error message if processing failed', null=True)),
                ('analysis_results', models.JSONField(blank=True, default=dict, help_text='\n        Complete AI analysis including:\n        - summary, key_points\n        - action_items: [{title, description, priority, type, source_context, ...}]\n        - suggested_improvements, related_topics, questions_raised, metadata\n    ')),
                ('action_items_count', models.IntegerField(default=0, help_text='Number of action items extracted')),
                ('tasks_created_count', models.IntegerField(default=0, help_text='Number of tasks created from this analysis')),
                ('content_hash', models.CharField(help_text='Hash of content analyzed (to detect changes)', max_length=64)),
                ('user_reviewed', models.BooleanField(default=False, help_text='Has user reviewed the analysis?')),
                ('user_notes', models.TextField(blank=True, help_text='User notes about the analysis', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, help_text='Organization (optional - MVP mode uses demo org)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wiki_documentation_analyses', to='accounts.organization')),
                ('processed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_documentation_analyses', to=settings.AUTH_USER_MODEL)),
                ('wiki_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentation_analyses', to='wiki.wikipage')),
            ],
            options={
                'verbose_name': 'Wiki Documentation Analysis',
                'verbose_name_plural': 'Wiki Documentation Analyses',
                'ordering': ['-processed_at'],
            },
        ),
        migrations.CreateModel(
            name='WikiDocumentationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_item_index', models.IntegerField(help_text='Index in the action_items array')),
                ('action_item_data', models.JSONField(default=dict, help_text='Original AI-extracted action item data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_modified', models.BooleanField(default=False, help_text='Did user modify before creating?')),
                ('modifications_note', models.TextField(blank=True, help_text='What was changed from AI suggestion', null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_documentation_tasks', to=settings.AUTH_USER_MODEL)),
                ('documentation_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to='wiki.wikidocumentationanalysis')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wiki_documentation_source', to='kanban.task')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='wikidocumentationanalysis',
            index=models.Index(fields=['wiki_page', '-processed_at'], name='wiki_wikido_wiki_pa_a08fdb_idx'),
        ),
        migrations.AddIndex(
            model_name='wikidocumentationanalysis',
            index=models.Index(fields=['processing_status'], name='wiki_wikido_process_8c7f11_idx'),
        ),
        migrations.AddIndex(
            model_name='wikidocumentationtask',
            index=models.Index(fields=['documentation_analysis', 'task'], name='wiki_wikido_documen_899721_idx'),
        ),
        migrations.AddIndex(
            model_name='wikidocumentationtask',
            index=models.Index(fields=['task'], name='wiki_wikido_task_id_75350e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='wikidocumentationtask',
            unique_together={('documentation_analysis', 'action_item_index')},
        ),
    ]
