# Generated by Django 5.2.3 on 2026-07-20 17:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kanban', '0166_customfielddefinition_sandbox_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('target_destination', models.CharField(choices=[('DISCOVERY', 'PrizmDiscovery Idea'), ('KANBAN_TASK', 'Kanban Task')], default='DISCOVERY', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('submit_button_text', models.CharField(default='Submit Request', max_length=60)),
                ('confirmation_message', models.TextField(blank=True, default='Thanks — your submission has been received.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_forms', to=settings.AUTH_USER_MODEL)),
                ('sandbox_owner', models.ForeignKey(blank=True, help_text='Owning demo user for sandbox-isolated copies; None for template/real forms.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sandbox_forms', to=settings.AUTH_USER_MODEL)),
                ('target_board', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intake_forms', to='kanban.board')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='kanban.workspace')),
            ],
            options={
                'verbose_name': 'Form',
                'verbose_name_plural': 'Forms',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('help_text', models.CharField(blank=True, default='', max_length=255)),
                ('field_type', models.CharField(choices=[('SHORT_TEXT', 'Short Text'), ('LONG_TEXT', 'Long Text'), ('SINGLE_SELECT', 'Single Select'), ('MULTI_SELECT', 'Multi Select'), ('STATIC_CONTENT', 'Static Content (instructions only)')], default='SHORT_TEXT', max_length=20)),
                ('mapped_property', models.CharField(choices=[('title', 'Title'), ('description', 'Description'), ('source', 'Source (Discovery only)'), ('none', 'Context only (included in description)')], default='none', max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('choices', models.JSONField(blank=True, default=list)),
                ('order', models.PositiveIntegerField(default=0)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='forms.form')),
            ],
            options={
                'verbose_name': 'Form Field',
                'verbose_name_plural': 'Form Fields',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_idea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_submission', to='kanban.discoveryidea')),
                ('created_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_submission', to='kanban.task')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='forms.form')),
                ('submitter_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Form Submission',
                'verbose_name_plural': 'Form Submissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField(blank=True, default=str)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='forms.formfield')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='forms.formsubmission')),
            ],
            options={
                'verbose_name': 'Form Answer',
                'verbose_name_plural': 'Form Answers',
            },
        ),
    ]
