# Generated by Django 5.0.14 on 2026-03-17 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kanban', '0091_alter_stresstestscenario_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HospiceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_type', models.CharField(choices=[('ai_detected', 'AI Detected'), ('manager_initiated', 'Manager Initiated')], max_length=20)),
                ('status', models.CharField(choices=[('assessment', 'Assessment Phase'), ('knowledge_extraction', 'Knowledge Extraction'), ('organ_scan', 'Organ Scan'), ('team_transition', 'Team Transition'), ('burial_pending', 'Burial Pending'), ('buried', 'Buried')], default='assessment', max_length=30)),
                ('ai_assessment', models.TextField(blank=True)),
                ('knowledge_checklist', models.JSONField(default=dict)),
                ('team_transition_memos', models.JSONField(default=dict)),
                ('checklist_completed_items', models.JSONField(default=list)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('buried_at', models.DateTimeField(blank=True, null=True)),
                ('board', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hospice_session', to='kanban.board')),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_hospice_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CemeteryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('project_description', models.TextField(blank=True)),
                ('board_id_snapshot', models.IntegerField()),
                ('team_size', models.IntegerField(default=0)),
                ('total_tasks', models.IntegerField(default=0)),
                ('completed_tasks', models.IntegerField(default=0)),
                ('budget_allocated', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('budget_spent', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('cause_of_death', models.CharField(choices=[('natural_completion', '✅ Natural Completion'), ('budget_exhaustion', '💸 Budget Exhaustion'), ('deadline_collapse', '⏰ Deadline Collapse'), ('scope_creep_spiral', '🔄 Scope Creep Spiral'), ('team_dissolution', '👥 Team Dissolution'), ('strategic_pivot', '🔀 Strategic Pivot'), ('zombie_death', '🧟 Zombie Death'), ('merger', '🔗 Merger / Absorbed')], max_length=30)),
                ('ai_cause_rationale', models.TextField(blank=True)),
                ('contributing_factors', models.JSONField(default=list)),
                ('autopsy_report', models.JSONField(default=dict)),
                ('autopsy_summary', models.TextField(blank=True)),
                ('lessons_to_repeat', models.JSONField(default=list)),
                ('lessons_to_avoid', models.JSONField(default=list)),
                ('open_questions', models.JSONField(default=list)),
                ('decline_timeline', models.JSONField(default=list)),
                ('tags', models.JSONField(default=list)),
                ('buried_at', models.DateTimeField(auto_now_add=True)),
                ('is_resurrected', models.BooleanField(default=False)),
                ('board', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cemetery_entry', to='kanban.board')),
                ('resurrected_as', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resurrected_from', to='kanban.board')),
                ('hospice_session', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cemetery_entry', to='exit_protocol.hospicesession')),
            ],
            options={
                'verbose_name_plural': 'Cemetery Entries',
                'ordering': ['-buried_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectHealthSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('velocity_last_sprint', models.FloatField(blank=True, null=True)),
                ('velocity_3sprint_avg', models.FloatField(blank=True, null=True)),
                ('velocity_decline_pct', models.FloatField(blank=True, null=True)),
                ('budget_spent_pct', models.FloatField(blank=True, null=True)),
                ('tasks_complete_pct', models.FloatField(blank=True, null=True)),
                ('deadlines_missed_30d', models.IntegerField(default=0)),
                ('days_since_last_activity', models.IntegerField(default=0)),
                ('dimensions_available', models.IntegerField(default=0)),
                ('hospice_risk_score', models.FloatField(default=0.0)),
                ('score_is_valid', models.BooleanField(default=False)),
                ('triggered_hospice', models.BooleanField(default=False)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_signals', to='kanban.board')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectOrgan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organ_type', models.CharField(choices=[('task_template', 'Task Template'), ('checklist', 'Checklist'), ('automation_rule', 'Automation Rule'), ('goal_framework', 'Goal Framework'), ('knowledge_entry', 'Knowledge Entry'), ('role_definition', 'Role Definition')], max_length=30)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('payload', models.JSONField()),
                ('reusability_score', models.IntegerField(default=0)),
                ('ai_rationale', models.TextField(blank=True)),
                ('best_suited_for', models.TextField(blank=True)),
                ('cautions', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('available', 'Available for Transplant'), ('transplanted', 'Transplanted'), ('rejected', 'Rejected / Archived')], default='available', max_length=20)),
                ('extracted_at', models.DateTimeField(auto_now_add=True)),
                ('hospice_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organs', to='exit_protocol.hospicesession')),
                ('source_board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donated_organs', to='kanban.board')),
            ],
        ),
        migrations.CreateModel(
            name='OrganTransplant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compatibility_score', models.IntegerField(default=0)),
                ('ai_match_rationale', models.TextField(blank=True)),
                ('adaptation_needed', models.TextField(blank=True)),
                ('transplanted_at', models.DateTimeField(auto_now_add=True)),
                ('created_object_type', models.CharField(blank=True, max_length=50)),
                ('created_object_id', models.IntegerField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_transplants', to=settings.AUTH_USER_MODEL)),
                ('target_board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_organs', to='kanban.board')),
                ('organ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transplants', to='exit_protocol.projectorgan')),
            ],
        ),
        migrations.CreateModel(
            name='HospiceDismissal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dismissed_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospice_dismissals', to='kanban.board')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospice_dismissals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['board', 'user', 'expires_at'], name='exit_protoc_board_i_6f4cd5_idx')],
                'unique_together': {('board', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='hospicesession',
            index=models.Index(fields=['board', 'status'], name='exit_protoc_board_i_2a8a12_idx'),
        ),
        migrations.AddIndex(
            model_name='cemeteryentry',
            index=models.Index(fields=['cause_of_death'], name='exit_protoc_cause_o_c928fb_idx'),
        ),
        migrations.AddIndex(
            model_name='cemeteryentry',
            index=models.Index(fields=['buried_at'], name='exit_protoc_buried__b9e10c_idx'),
        ),
        migrations.AddIndex(
            model_name='projecthealthsignal',
            index=models.Index(fields=['board', 'recorded_at'], name='exit_protoc_board_i_1788d2_idx'),
        ),
        migrations.AddIndex(
            model_name='projectorgan',
            index=models.Index(fields=['organ_type', 'status'], name='exit_protoc_organ_t_f84408_idx'),
        ),
    ]
