"""
Project Signals & Auto-Computed Confidence Score

Replaces the standalone Living Commitment Protocol feature by integrating
the valuable parts into existing features:

1. ProjectSignal — Unified signal log recording events that affect project
   health (task completions, scope changes, blockers, team changes).
   Feeds the Triple Constraint Dashboard and AI Coach automatically.

2. ProjectConfidenceScore — Auto-computed daily snapshot synthesising
   scope stability, budget health, schedule adherence, and velocity trend
   into a single 0-100 confidence score. No manual configuration required.
"""

from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator
from django.utils import timezone


class ProjectSignal(models.Model):
    """
    A single project event that affects overall health or confidence.

    Automatically generated by Django signals on task saves/deletes,
    scope snapshots, and burndown predictions. Can also be created
    manually by team members via the Triple Constraint Dashboard.
    """

    SIGNAL_TYPE_CHOICES = [
        # Task-related
        ('task_completed', 'Task Completed'),
        ('task_added', 'Task Added (Scope Growth)'),
        ('task_removed', 'Task Removed'),
        # Schedule-related
        ('milestone_hit', 'Milestone Hit'),
        ('milestone_missed', 'Milestone Missed'),
        ('deadline_risk', 'Deadline Risk Detected'),
        # Team-related
        ('team_member_joined', 'Team Member Joined'),
        ('team_member_left', 'Team Member Left'),
        # Blockers
        ('blocker_added', 'Blocker Emerged'),
        ('blocker_resolved', 'Blocker Resolved'),
        # Scope
        ('scope_creep', 'Scope Creep Detected'),
        ('scope_approved', 'Scope Change Approved'),
        # Budget
        ('budget_overrun', 'Budget Overrun Risk'),
        ('budget_approved', 'Budget Increase Approved'),
        # Quality
        ('quality_issue', 'Quality Issue Detected'),
        # Manual
        ('manual_positive', 'Manual Positive Update'),
        ('manual_negative', 'Manual Negative Update'),
    ]

    IMPACT_CHOICES = [
        ('positive', 'Positive'),
        ('negative', 'Negative'),
        ('neutral', 'Neutral'),
    ]

    board = models.ForeignKey(
        'kanban.Board',
        on_delete=models.CASCADE,
        related_name='project_signals',
    )
    signal_type = models.CharField(max_length=30, choices=SIGNAL_TYPE_CHOICES)
    impact = models.CharField(max_length=10, choices=IMPACT_CHOICES, default='neutral')
    strength = models.FloatField(
        default=0.0,
        validators=[MinValueValidator(-1.0), MaxValueValidator(1.0)],
        help_text='Signal strength from -1.0 (very negative) to +1.0 (very positive)',
    )
    description = models.TextField()

    # Optional links to related objects
    related_task = models.ForeignKey(
        'kanban.Task',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='project_signals',
    )

    # Source tracking
    ai_generated = models.BooleanField(default=False)
    recorded_by = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='recorded_project_signals',
    )

    # Confidence impact (set when signal is applied)
    confidence_before = models.FloatField(null=True, blank=True)
    confidence_after = models.FloatField(null=True, blank=True)

    timestamp = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-timestamp']
        verbose_name = 'Project Signal'
        verbose_name_plural = 'Project Signals'
        indexes = [
            models.Index(fields=['board', '-timestamp']),
            models.Index(fields=['board', 'signal_type']),
        ]

    def __str__(self):
        direction = '+' if self.strength >= 0 else ''
        return f'[{self.get_signal_type_display()}] {direction}{self.strength:.2f} – {self.board.name}'


class ProjectConfidenceScore(models.Model):
    """
    Auto-computed daily confidence snapshot for a board.

    Synthesised from three dimensions:
      - scope_score:    based on scope change % from baseline
      - budget_score:   based on budget utilisation %
      - schedule_score: based on burndown delay probability

    composite_score = weighted average, displayed on the Triple Constraint
    Dashboard as the "Project Confidence" indicator.
    """

    board = models.ForeignKey(
        'kanban.Board',
        on_delete=models.CASCADE,
        related_name='confidence_scores',
    )
    computed_at = models.DateTimeField(auto_now_add=True)

    # Dimension scores (0-100)
    scope_score = models.FloatField(
        default=100.0,
        validators=[MinValueValidator(0), MaxValueValidator(100)],
        help_text='100 = no scope creep, 0 = extreme scope creep',
    )
    budget_score = models.FloatField(
        default=100.0,
        validators=[MinValueValidator(0), MaxValueValidator(100)],
        help_text='100 = on budget, 0 = severely over budget',
    )
    schedule_score = models.FloatField(
        default=100.0,
        validators=[MinValueValidator(0), MaxValueValidator(100)],
        help_text='100 = on schedule, 0 = far behind schedule',
    )

    # Signal adjustment — cumulative signal impact since last snapshot
    signal_adjustment = models.FloatField(
        default=0.0,
        help_text='Adjustment from recent project signals (-50 to +50)',
    )

    # Final composite score
    composite_score = models.FloatField(
        default=100.0,
        validators=[MinValueValidator(0), MaxValueValidator(100)],
        help_text='Weighted composite confidence score',
    )

    # Trend since previous snapshot
    trend = models.CharField(
        max_length=20,
        choices=[
            ('improving', 'Improving'),
            ('stable', 'Stable'),
            ('declining', 'Declining'),
        ],
        default='stable',
    )
    previous_score = models.FloatField(null=True, blank=True)

    # Raw data used for the computation (for transparency and debugging)
    computation_data = models.JSONField(
        default=dict,
        blank=True,
        help_text='Raw metrics snapshot used for this calculation',
    )

    class Meta:
        ordering = ['-computed_at']
        verbose_name = 'Project Confidence Score'
        verbose_name_plural = 'Project Confidence Scores'
        indexes = [
            models.Index(fields=['board', '-computed_at']),
        ]

    def __str__(self):
        return f'{self.board.name} – {self.composite_score:.0f}% ({self.computed_at:%Y-%m-%d})'

    @property
    def confidence_color(self):
        """Bootstrap color class."""
        if self.composite_score >= 70:
            return 'success'
        elif self.composite_score >= 40:
            return 'warning'
        return 'danger'

    @property
    def status_label(self):
        """Human-readable status."""
        if self.composite_score >= 70:
            return 'Healthy'
        elif self.composite_score >= 40:
            return 'At Risk'
        return 'Critical'
