# Generated by Django 5.2.3 on 2025-12-20 01:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('boards_viewed', models.IntegerField(default=0)),
                ('boards_created', models.IntegerField(default=0)),
                ('tasks_created', models.IntegerField(default=0)),
                ('tasks_completed', models.IntegerField(default=0)),
                ('ai_features_used', models.IntegerField(default=0)),
                ('pages_visited', models.IntegerField(default=0)),
                ('session_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('session_end', models.DateTimeField(blank=True, null=True)),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration_minutes', models.IntegerField(default=0)),
                ('engagement_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('very_high', 'Very High')], default='low', max_length=20)),
                ('engagement_score', models.IntegerField(default=0, help_text='Calculated score 0-12')),
                ('registered_during_session', models.BooleanField(default=False)),
                ('is_return_visit', models.BooleanField(default=False)),
                ('previous_session_count', models.IntegerField(default=0)),
                ('features_discovered', models.JSONField(blank=True, default=list, help_text="List of features user discovered: ['kanban', 'ai_recommend', etc.]")),
                ('exit_page', models.CharField(blank=True, max_length=200)),
                ('exit_reason', models.CharField(blank=True, choices=[('logout', 'User Logged Out'), ('timeout', 'Session Timeout'), ('navigation', 'Navigation Away')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('referrer', models.URLField(blank=True, max_length=500)),
                ('device_type', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('user', models.ForeignKey(blank=True, help_text='Authenticated user (null for anonymous)', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Session',
                'verbose_name_plural': 'User Sessions',
                'ordering': ['-session_start'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_type', models.CharField(choices=[('logout', 'Logout Page'), ('exit_intent', 'Exit Intent Popup'), ('in_app', 'In-App Banner'), ('email', 'Follow-up Email'), ('modal', 'Modal Dialog')], max_length=20)),
                ('shown_at', models.DateTimeField(auto_now_add=True)),
                ('interacted', models.BooleanField(default=False, help_text='User clicked or engaged with prompt')),
                ('submitted', models.BooleanField(default=False, help_text='User submitted feedback')),
                ('dismissed', models.BooleanField(default=False, help_text='User dismissed/closed prompt')),
                ('user_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_prompts', to='analytics.usersession')),
            ],
            options={
                'verbose_name': 'Feedback Prompt',
                'verbose_name_plural': 'Feedback Prompts',
                'ordering': ['-shown_at'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('feedback_text', models.TextField()),
                ('rating', models.IntegerField(blank=True, choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], help_text='1-5 star rating', null=True)),
                ('sentiment', models.CharField(blank=True, choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], max_length=20)),
                ('feedback_type', models.CharField(choices=[('feature_request', 'Feature Request'), ('bug_report', 'Bug Report'), ('praise', 'Praise'), ('complaint', 'Complaint'), ('question', 'Question'), ('other', 'Other')], default='other', max_length=20)),
                ('email_consent', models.BooleanField(default=False, help_text='User agreed to receive follow-up emails')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('hubspot_contact_id', models.CharField(blank=True, max_length=50)),
                ('hubspot_deal_id', models.CharField(blank=True, max_length=50)),
                ('synced_to_hubspot', models.BooleanField(default=False)),
                ('hubspot_sync_date', models.DateTimeField(blank=True, null=True)),
                ('follow_up_sent', models.BooleanField(default=False)),
                ('follow_up_sent_at', models.DateTimeField(blank=True, null=True)),
                ('follow_up_response', models.TextField(blank=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for team use only')),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('archived', 'Archived')], default='new', max_length=20)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_session', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='analytics.usersession')),
            ],
            options={
                'verbose_name': 'User Feedback',
                'verbose_name_plural': 'User Feedback',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(db_index=True, max_length=100)),
                ('event_category', models.CharField(blank=True, max_length=50)),
                ('event_label', models.CharField(blank=True, max_length=200)),
                ('event_value', models.IntegerField(blank=True, null=True)),
                ('event_data', models.JSONField(blank=True, default=dict, help_text='Additional event metadata')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='analytics.usersession')),
            ],
            options={
                'verbose_name': 'Analytics Event',
                'verbose_name_plural': 'Analytics Events',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['session_key', 'session_end'], name='analytics_u_session_214633_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user', 'session_start'], name='analytics_u_user_id_25916b_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['engagement_level'], name='analytics_u_engagem_16c48c_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['event_name', 'timestamp'], name='analytics_a_event_n_ad6c50_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['user_session', 'event_name'], name='analytics_a_user_se_cebf52_idx'),
        ),
    ]
