# Generated by Django 5.2.3 on 2025-12-20 02:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='last_engagement_update',
            field=models.IntegerField(default=0, help_text='Duration minutes when engagement was last updated'),
        ),
        migrations.AddConstraint(
            model_name='usersession',
            constraint=models.UniqueConstraint(condition=models.Q(('session_end__isnull', True)), fields=('user',), name='one_active_session_per_user'),
        ),
    ]
