# Generated by Django 5.2.3 on 2025-12-21 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_add_engagement_tracking_improvements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='hubspot_contact_id',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='hubspot_deal_id',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='hubspot_sync_date',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='synced_to_hubspot',
        ),
    ]
