# Generated by Django 5.2.3 on 2025-12-29 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_remove_hubspot_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('demo_mode', models.CharField(choices=[('solo', 'Solo Exploration'), ('team', 'Team Collaboration')], help_text='Demo mode selected by user', max_length=20)),
                ('selection_method', models.CharField(choices=[('selected', 'Explicitly Selected'), ('skipped', 'Skipped Selection')], default='selected', help_text='How user entered demo mode', max_length=20)),
                ('current_role', models.CharField(choices=[('admin', 'Administrator'), ('member', 'Team Member'), ('viewer', 'Viewer')], default='admin', help_text='Current persona role (for Team mode)', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='Session expiration (48 hours default)')),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('session_end', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(default=0, help_text='Total time in demo')),
                ('features_explored', models.IntegerField(default=0, help_text='Count of features with meaningful interaction')),
                ('features_list', models.JSONField(blank=True, default=list, help_text="List of features explored: ['ai_generator', 'burndown', etc.]")),
                ('aha_moments', models.IntegerField(default=0, help_text='Count of aha moments experienced')),
                ('aha_moments_list', models.JSONField(blank=True, default=list, help_text='List of aha moment triggers')),
                ('nudges_shown', models.IntegerField(default=0, help_text='Count of conversion nudges shown')),
                ('nudges_clicked', models.IntegerField(default=0, help_text='Count of nudge CTAs clicked')),
                ('converted_to_signup', models.BooleanField(default=False)),
                ('conversion_timestamp', models.DateTimeField(blank=True, null=True)),
                ('time_to_conversion_seconds', models.IntegerField(blank=True, help_text='Time from demo start to signup', null=True)),
                ('reset_count', models.IntegerField(default=0, help_text='Number of times demo was reset')),
                ('role_switches', models.IntegerField(default=0, help_text='Number of role switches (Team mode)')),
                ('device_type', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('user_agent', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('has_ga4_data', models.BooleanField(default=False, help_text='Whether GA4 successfully tracked this session')),
                ('user', models.ForeignKey(blank=True, help_text='User who started demo (null if demo led to signup)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demo_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demo Session',
                'verbose_name_plural': 'Demo Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DemoConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('time_in_demo_seconds', models.IntegerField(help_text='Total time spent in demo before signup')),
                ('features_explored', models.IntegerField(default=0)),
                ('features_list', models.JSONField(blank=True, default=list)),
                ('aha_moments', models.IntegerField(default=0)),
                ('aha_moments_list', models.JSONField(blank=True, default=list)),
                ('last_nudge_seen', models.CharField(blank=True, max_length=50)),
                ('nudge_clicks', models.IntegerField(default=0)),
                ('conversion_source', models.CharField(choices=[('demo', 'Demo CTA'), ('nudge_soft', 'Soft Nudge'), ('nudge_medium', 'Medium Nudge'), ('nudge_peak', 'Peak Moment Nudge'), ('nudge_exit', 'Exit Intent Nudge'), ('banner', 'Demo Banner'), ('direct', 'Direct Signup')], default='demo', max_length=50)),
                ('reset_count', models.IntegerField(default=0)),
                ('role_switches', models.IntegerField(default=0)),
                ('demo_mode', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('device_type', models.CharField(max_length=20)),
                ('converted_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demo_conversion', to=settings.AUTH_USER_MODEL)),
                ('demo_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conversion_details', to='analytics.demosession')),
            ],
            options={
                'verbose_name': 'Demo Conversion',
                'verbose_name_plural': 'Demo Conversions',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DemoAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=255)),
                ('event_type', models.CharField(db_index=True, help_text="Event name: 'demo_mode_selected', 'feature_explored', 'aha_moment', etc.", max_length=100)),
                ('event_data', models.JSONField(blank=True, default=dict, help_text='Event-specific data and metadata')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('page_path', models.CharField(blank=True, max_length=500)),
                ('device_type', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('user_agent', models.TextField(blank=True)),
                ('demo_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analytics_events', to='analytics.demosession')),
            ],
            options={
                'verbose_name': 'Demo Analytics Event',
                'verbose_name_plural': 'Demo Analytics Events',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='demosession',
            index=models.Index(fields=['session_id'], name='analytics_d_session_9f33e4_idx'),
        ),
        migrations.AddIndex(
            model_name='demosession',
            index=models.Index(fields=['created_at', 'expires_at'], name='analytics_d_created_9cca80_idx'),
        ),
        migrations.AddIndex(
            model_name='demosession',
            index=models.Index(fields=['demo_mode'], name='analytics_d_demo_mo_6e90bb_idx'),
        ),
        migrations.AddIndex(
            model_name='demosession',
            index=models.Index(fields=['converted_to_signup'], name='analytics_d_convert_7bb922_idx'),
        ),
        migrations.AddIndex(
            model_name='democonversion',
            index=models.Index(fields=['converted_user'], name='analytics_d_convert_b81c80_idx'),
        ),
        migrations.AddIndex(
            model_name='democonversion',
            index=models.Index(fields=['conversion_source'], name='analytics_d_convers_0f437b_idx'),
        ),
        migrations.AddIndex(
            model_name='democonversion',
            index=models.Index(fields=['timestamp'], name='analytics_d_timesta_fe9419_idx'),
        ),
        migrations.AddIndex(
            model_name='demoanalytics',
            index=models.Index(fields=['session_id', 'event_type'], name='analytics_d_session_27fee6_idx'),
        ),
        migrations.AddIndex(
            model_name='demoanalytics',
            index=models.Index(fields=['event_type', 'timestamp'], name='analytics_d_event_t_9f30aa_idx'),
        ),
        migrations.AddIndex(
            model_name='demoanalytics',
            index=models.Index(fields=['demo_session', 'event_type'], name='analytics_d_demo_se_636178_idx'),
        ),
    ]
