# Generated by Django 5.2.3 on 2025-12-29 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_demosession_democonversion_demoanalytics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demosession',
            name='extensions_count',
            field=models.IntegerField(default=0, help_text='Number of times session was extended'),
        ),
    ]
