# Generated by Django 5.2.3 on 2025-12-29 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_add_extensions_count_to_demo_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='demosession',
            name='nudges_dismissed',
            field=models.IntegerField(default=0, help_text='Count of nudges dismissed by user'),
        ),
    ]
