# Generated by Django 5.2.3 on 2026-01-01 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_add_nudges_dismissed_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='demosession',
            name='ai_generations_used',
            field=models.IntegerField(default=0, help_text='Number of AI generations used in demo'),
        ),
        migrations.AddField(
            model_name='demosession',
            name='export_attempts',
            field=models.IntegerField(default=0, help_text='Number of export attempts (blocked)'),
        ),
        migrations.AddField(
            model_name='demosession',
            name='limitations_hit',
            field=models.JSONField(blank=True, default=list, help_text="List of limitations encountered: ['project_limit', 'export_blocked', etc.]"),
        ),
        migrations.AddField(
            model_name='demosession',
            name='projects_created_in_demo',
            field=models.IntegerField(default=0, help_text='Number of projects created in demo mode'),
        ),
    ]
