# Generated by Django 5.2.3 on 2026-01-01 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_add_demo_limitation_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='demosession',
            name='browser_fingerprint',
            field=models.CharField(blank=True, db_index=True, help_text='Browser fingerprint to track demo across sessions', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='demosession',
            name='first_demo_start',
            field=models.DateTimeField(blank=True, help_text='When user FIRST started demo (persists across logins)', null=True),
        ),
    ]
