# Generated by Django 5.2.3 on 2026-01-04 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0009_demo_abuse_prevention'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='demoabuseprevention',
            name='unique_ip_fingerprint',
        ),
        migrations.RenameIndex(
            model_name='demoabuseprevention',
            new_name='analytics_d_ip_addr_301bbe_idx',
            old_name='analytics_d_ip_addr_abuse_idx',
        ),
        migrations.RenameIndex(
            model_name='demoabuseprevention',
            new_name='analytics_d_is_flag_246c15_idx',
            old_name='analytics_d_is_flag_idx',
        ),
        migrations.RenameIndex(
            model_name='demoabuseprevention',
            new_name='analytics_d_is_bloc_a62db1_idx',
            old_name='analytics_d_is_bloc_idx',
        ),
        migrations.RenameIndex(
            model_name='demoabuseprevention',
            new_name='analytics_d_last_se_572d11_idx',
            old_name='analytics_d_last_se_idx',
        ),
        migrations.AlterUniqueTogether(
            name='demoabuseprevention',
            unique_together={('ip_address', 'browser_fingerprint')},
        ),
    ]
