# Generated by Django 5.2.3 on 2026-01-08 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0010_remove_demoabuseprevention_unique_ip_fingerprint_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='demosession',
            name='demo_user_email',
            field=models.EmailField(blank=True, help_text='Email address for demo user (for sending reminders)', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='demosession',
            name='inactivity_email_sent',
            field=models.BooleanField(default=False, help_text='Whether inactivity re-engagement email was sent'),
        ),
        migrations.AddField(
            model_name='demosession',
            name='inactivity_email_sent_at',
            field=models.DateTimeField(blank=True, help_text='When inactivity email was sent', null=True),
        ),
        migrations.AddField(
            model_name='demosession',
            name='reminder_12h_sent',
            field=models.BooleanField(default=False, help_text='Whether 12-hour reminder email was sent'),
        ),
        migrations.AddField(
            model_name='demosession',
            name='reminder_12h_sent_at',
            field=models.DateTimeField(blank=True, help_text='When 12-hour reminder email was sent', null=True),
        ),
        migrations.AddField(
            model_name='demosession',
            name='reminder_24h_sent',
            field=models.BooleanField(default=False, help_text='Whether 24-hour reminder email was sent'),
        ),
        migrations.AddField(
            model_name='demosession',
            name='reminder_24h_sent_at',
            field=models.DateTimeField(blank=True, help_text='When 24-hour reminder email was sent', null=True),
        ),
        migrations.CreateModel(
            name='AhaMomentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, help_text='Session identifier for tracking', max_length=255)),
                ('moment_type', models.CharField(choices=[('ai_suggestion_accepted', 'AI Suggestion Accepted'), ('burndown_viewed', 'Burndown Chart Viewed'), ('rbac_workflow', 'RBAC/Permissions Used'), ('time_tracking_used', 'Time Tracking Used'), ('dependency_created', 'Task Dependency Created'), ('gantt_viewed', 'Gantt Chart Viewed'), ('skill_gap_viewed', 'Skill Gap Analysis Viewed'), ('conflict_detected', 'Conflict Detection Explored'), ('budget_forecasting', 'Budget Forecasting Used'), ('retrospective_completed', 'Retrospective Completed'), ('milestone_reached', 'Milestone Reached'), ('first_board_created', 'First Board Created'), ('first_task_completed', 'First Task Completed'), ('team_collaboration', 'Team Collaboration Feature'), ('wiki_explored', 'Wiki/Documentation Explored'), ('analytics_deep_dive', 'Analytics Deep Dive'), ('custom', 'Custom Aha Moment')], db_index=True, help_text='Type of aha moment triggered', max_length=50)),
                ('moment_subtype', models.CharField(blank=True, help_text='Specific subtype or variant of aha moment', max_length=100)),
                ('page_path', models.CharField(help_text='Page where aha moment occurred', max_length=500)),
                ('feature_context', models.CharField(blank=True, help_text="Specific feature being used (e.g., 'task_generator', 'sprint_burndown')", max_length=100)),
                ('trigger_action', models.CharField(blank=True, help_text="Specific action that triggered the aha (e.g., 'accept_suggestion', 'view_chart')", max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('time_since_session_start', models.IntegerField(blank=True, help_text='Seconds since session started when aha occurred', null=True)),
                ('actions_before_aha', models.IntegerField(default=0, help_text='Number of user actions before this aha moment')),
                ('previous_aha_moments', models.IntegerField(default=0, help_text='Number of aha moments before this one in session')),
                ('led_to_conversion', models.BooleanField(default=False, help_text='Whether this aha moment led to signup/conversion')),
                ('conversion_time_seconds', models.IntegerField(blank=True, help_text='Seconds between aha moment and conversion', null=True)),
                ('engagement_after_aha', models.CharField(choices=[('increased', 'Increased Engagement'), ('maintained', 'Maintained Engagement'), ('decreased', 'Decreased Engagement'), ('unknown', 'Unknown')], default='unknown', help_text='User engagement level after aha moment', max_length=20)),
                ('user_acknowledged', models.BooleanField(default=False, help_text='Whether user interacted with aha celebration UI')),
                ('celebration_shown', models.BooleanField(default=True, help_text='Whether celebration UI was shown to user')),
                ('celebration_dismissed', models.BooleanField(default=False, help_text='Whether user dismissed celebration quickly')),
                ('cta_clicked', models.BooleanField(default=False, help_text='Whether user clicked the CTA in celebration UI')),
                ('event_data', models.JSONField(blank=True, default=dict, help_text='Additional context data about the aha moment')),
                ('device_type', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('user_agent', models.TextField(blank=True)),
                ('ga_event_sent', models.BooleanField(default=False, help_text='Whether event was synced to Google Analytics')),
                ('demo_session', models.ForeignKey(blank=True, help_text='Demo session where aha moment occurred', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aha_moment_events', to='analytics.demosession')),
                ('user', models.ForeignKey(blank=True, help_text='User who experienced the aha moment', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aha_moment_events', to=settings.AUTH_USER_MODEL)),
                ('user_session', models.ForeignKey(blank=True, help_text='User session where aha moment occurred', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aha_moment_events', to='analytics.usersession')),
            ],
            options={
                'verbose_name': 'Aha Moment Event',
                'verbose_name_plural': 'Aha Moment Events',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['session_id', 'moment_type'], name='analytics_a_session_18901d_idx'), models.Index(fields=['moment_type', 'timestamp'], name='analytics_a_moment__afc0fe_idx'), models.Index(fields=['demo_session', 'moment_type'], name='analytics_a_demo_se_38ed40_idx'), models.Index(fields=['led_to_conversion'], name='analytics_a_led_to__80b6ee_idx'), models.Index(fields=['user', 'timestamp'], name='analytics_a_user_id_e28dcc_idx')],
            },
        ),
    ]
