# Generated by Django 5.2.3 on 2026-01-23 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0011_add_aha_moment_and_email_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='demoabuseprevention',
            name='ai_generation_timestamps',
            field=models.JSONField(blank=True, default=list, help_text='Timestamps of recent AI generations for rate limiting'),
        ),
        migrations.AddField(
            model_name='demoabuseprevention',
            name='client_fingerprint',
            field=models.CharField(blank=True, db_index=True, help_text='Client-side JS fingerprint (canvas, webgl, audio)', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='demoabuseprevention',
            name='is_vpn_user',
            field=models.BooleanField(default=False, help_text='Whether this visitor uses VPN/proxy'),
        ),
        migrations.AddField(
            model_name='demosession',
            name='client_fingerprint',
            field=models.CharField(blank=True, db_index=True, help_text='Client-side JS fingerprint (more robust than server-side)', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='demosession',
            name='is_vpn_detected',
            field=models.BooleanField(default=False, help_text='Whether VPN/proxy was detected for this session'),
        ),
    ]
