# Generated by Django 5.2.3 on 2026-01-31 12:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0012_add_client_fingerprint_and_vpn_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='demosession',
            name='analytics_d_created_9cca80_idx',
        ),
        migrations.RemoveField(
            model_name='demosession',
            name='demo_user_email',
        ),
        migrations.RemoveField(
            model_name='demosession',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='demosession',
            name='extensions_count',
        ),
        migrations.RemoveField(
            model_name='demosession',
            name='inactivity_email_sent',
        ),
        migrations.RemoveField(
            model_name='demosession',
            name='inactivity_email_sent_at',
        ),
        migrations.RemoveField(
            model_name='demosession',
            name='reminder_12h_sent',
        ),
        migrations.RemoveField(
            model_name='demosession',
            name='reminder_12h_sent_at',
        ),
        migrations.RemoveField(
            model_name='demosession',
            name='reminder_24h_sent',
        ),
        migrations.RemoveField(
            model_name='demosession',
            name='reminder_24h_sent_at',
        ),
        migrations.AddIndex(
            model_name='demosession',
            index=models.Index(fields=['created_at'], name='analytics_d_created_dcb053_idx'),
        ),
    ]
