# Generated by Django 5.2.3 on 2026-05-03 02:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_googlecalendartoken'),
        ('analytics', '0015_fix_abuse_prevention_unique_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIQuotaEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('quota_warning', 'Quota Warning (80%)'), ('quota_exhausted', 'Quota Exhausted (100%)'), ('feature_blocked', 'Feature Blocked by Quota'), ('byok_configured', 'BYOK Key Configured'), ('byok_removed', 'BYOK Key Removed')], db_index=True, max_length=20)),
                ('quota_used', models.IntegerField(default=0)),
                ('quota_limit', models.IntegerField(default=25)),
                ('feature_blocked', models.CharField(blank=True, default='', max_length=50)),
                ('provider_configured', models.CharField(blank=True, default='', max_length=20)),
                ('days_since_first_use', models.IntegerField(default=0, help_text='How many days since the user first used an AI feature')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'AI Quota Event',
                'verbose_name_plural': 'AI Quota Events',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='FeatureAdoptionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(choices=[('kanban_board', 'Kanban Board'), ('gantt_chart', 'Gantt Chart'), ('burndown_chart', 'Burndown Chart'), ('calendar_view', 'Calendar View'), ('time_tracking', 'Time Tracking'), ('budget_roi', 'Budget & ROI'), ('task_dependency', 'Task Dependencies'), ('board_automation', 'Board Automations'), ('requirements_mgmt', 'Requirements Management'), ('spectra_query', 'Spectra AI Query'), ('ai_coach', 'AI Coach'), ('ai_retrospective', 'AI Retrospective'), ('skill_gap', 'Skill Gap Analyser'), ('conflict_detection', 'Conflict Detection'), ('scope_creep', 'Scope Creep Monitor'), ('resource_leveling', 'Resource Levelling'), ('requirements_ai', 'Requirements AI'), ('knowledge_graph', 'Knowledge Graph'), ('cognitive_load', 'Cognitive Load Analyser'), ('ai_bubble_up', 'AI Bubble-Up Insights'), ('semantic_search', 'Semantic Search'), ('ai_onboarding', 'AI Onboarding'), ('premortem', 'Pre-Mortem Analysis'), ('stress_test', 'Stress Test'), ('what_if', 'What-If Scenarios'), ('shadow_board', 'Shadow Board'), ('scope_autopsy', 'Scope Autopsy'), ('exit_protocol', 'Exit Protocol'), ('prizm_brief', 'PrizmBrief'), ('triple_constraint', 'Triple Constraint'), ('commitments', 'Commitments Tracker'), ('team_invite', 'Team Invite'), ('real_time_chat', 'Real-Time Chat'), ('wiki', 'Wiki'), ('board_import', 'Board Import'), ('board_export', 'Board Export'), ('webhook', 'Webhooks'), ('google_calendar', 'Google Calendar Sync'), ('byok_setup', 'BYOK Key Setup'), ('github_webhook', 'GitHub Webhook')], db_index=True, max_length=30)),
                ('feature_category', models.CharField(choices=[('core', 'Core Feature'), ('ai', 'AI Feature'), ('enterprise_ai', 'Enterprise AI Feature'), ('collaboration', 'Collaboration'), ('integration', 'Integration')], max_length=20)),
                ('event_type', models.CharField(choices=[('first_use', 'First Use'), ('repeat_use', 'Repeat Use'), ('deep_use', 'Deep Use')], default='repeat_use', max_length=15)),
                ('workspace_preset', models.CharField(blank=True, default='', max_length=20)),
                ('using_byok', models.BooleanField(default=False)),
                ('ai_provider', models.CharField(blank=True, default='', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Feature Adoption Event',
                'verbose_name_plural': 'Feature Adoption Events',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WorkspacePresetEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_preset', models.CharField(blank=True, choices=[('lean', 'Lean'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], default='', max_length=20)),
                ('to_preset', models.CharField(choices=[('lean', 'Lean'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], max_length=20)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Workspace Preset Event',
                'verbose_name_plural': 'Workspace Preset Events',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.RenameIndex(
            model_name='demoemailcapture',
            new_name='analytics_d_capture_48f567_idx',
            old_name='analytics_d_capture_idx',
        ),
        migrations.AddField(
            model_name='usersession',
            name='ai_provider_used',
            field=models.CharField(blank=True, default='', help_text='AI provider active during session: gemini/openai/anthropic', max_length=20),
        ),
        migrations.AddField(
            model_name='usersession',
            name='byok_active',
            field=models.BooleanField(default=False, help_text='Whether user was using their own API key during this session'),
        ),
        migrations.AddField(
            model_name='usersession',
            name='workspace_preset',
            field=models.CharField(blank=True, default='', help_text='Workspace preset tier at session start: lean/professional/enterprise', max_length=20),
        ),
        migrations.AddField(
            model_name='aiquotaevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_quota_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='featureadoptionevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_adoption_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='featureadoptionevent',
            name='user_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feature_adoption_events', to='analytics.usersession'),
        ),
        migrations.AddField(
            model_name='workspacepresetevent',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preset_change_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workspacepresetevent',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preset_events', to='accounts.organization'),
        ),
        migrations.AddIndex(
            model_name='aiquotaevent',
            index=models.Index(fields=['event_type', 'timestamp'], name='analytics_aqe_type_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='featureadoptionevent',
            index=models.Index(fields=['feature', 'event_type'], name='analytics_fae_feature_type_idx'),
        ),
        migrations.AddIndex(
            model_name='featureadoptionevent',
            index=models.Index(fields=['user', 'feature'], name='analytics_fae_user_feature_idx'),
        ),
    ]
