# Generated by Django 5.2.3 on 2025-11-08 18:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, help_text='Unique API token string', max_length=64, unique=True)),
                ('name', models.CharField(help_text="Friendly name for this token (e.g., 'Slack Integration', 'Mobile App')", max_length=100)),
                ('scopes', models.JSONField(default=list, help_text="API scopes/permissions (e.g., ['boards.read', 'tasks.write', 'tasks.read'])")),
                ('is_active', models.BooleanField(default=True, help_text='Whether this token is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, help_text='Last time this token was used', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this token expires (null = never expires)', null=True)),
                ('rate_limit_per_hour', models.IntegerField(default=1000, help_text='Maximum API requests allowed per hour')),
                ('request_count_current_hour', models.IntegerField(default=0, help_text='Number of requests made in current hour')),
                ('rate_limit_reset_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the rate limit counter resets')),
                ('user_agent', models.CharField(blank=True, help_text='User agent of application using this token', max_length=255)),
                ('ip_whitelist', models.JSONField(blank=True, default=list, help_text='List of allowed IP addresses (empty = allow all)')),
                ('user', models.ForeignKey(help_text='User who owns this API token', on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Token',
                'verbose_name_plural': 'API Tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='APIRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=10)),
                ('status_code', models.IntegerField()),
                ('response_time_ms', models.IntegerField(help_text='Response time in milliseconds')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('error_message', models.TextField(blank=True)),
                ('token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_logs', to='api.apitoken')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='api_apirequ_timesta_df54ac_idx'), models.Index(fields=['token', '-timestamp'], name='api_apirequ_token_i_2074b8_idx')],
            },
        ),
    ]
