# Generated by Django 5.2.3 on 2025-12-12 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apirequestlog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'API Request Log', 'verbose_name_plural': 'API Request Logs'},
        ),
    ]
