# Generated by Django 5.2.3 on 2025-12-12 03:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_apirequestlog_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='apitoken',
            name='monthly_quota',
            field=models.IntegerField(default=10000, help_text='Maximum API requests allowed per month'),
        ),
        migrations.AddField(
            model_name='apitoken',
            name='monthly_reset_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When the monthly quota resets (start of next month)'),
        ),
        migrations.AddField(
            model_name='apitoken',
            name='request_count_current_month',
            field=models.IntegerField(default=0, help_text='Number of requests made in current month'),
        ),
    ]
