# Generated by Django 5.2.3 on 2025-12-12 04:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_apitoken_monthly_quota_apitoken_monthly_reset_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIUsageQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requests_used', models.IntegerField(default=0, help_text='Number of AI requests made in current period')),
                ('monthly_quota', models.IntegerField(default=1000, help_text='Maximum AI requests allowed per month')),
                ('period_start', models.DateTimeField(default=django.utils.timezone.now, help_text='When the current usage period started')),
                ('period_end', models.DateTimeField(help_text='When the current usage period ends')),
                ('last_request_at', models.DateTimeField(blank=True, help_text='Last time user made an AI request', null=True)),
                ('total_requests_all_time', models.IntegerField(default=0, help_text='Total AI requests made since account creation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='User whose AI usage is being tracked', on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage_quota', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Usage Quota',
                'verbose_name_plural': 'AI Usage Quotas',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AIRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(db_index=True, help_text='Which AI feature was used (ai_coach, ai_assistant, etc.)', max_length=50)),
                ('request_type', models.CharField(blank=True, help_text='Type of request (question, suggestion, analysis, etc.)', max_length=50)),
                ('ai_model', models.CharField(default='gemini', help_text='AI model used (gemini, gpt, etc.)', max_length=50)),
                ('tokens_used', models.IntegerField(default=0, help_text='Approximate tokens used (if available)')),
                ('success', models.BooleanField(default=True, help_text='Whether the request was successful')),
                ('error_message', models.TextField(blank=True, help_text='Error message if request failed')),
                ('response_time_ms', models.IntegerField(default=0, help_text='Response time in milliseconds')),
                ('board_id', models.IntegerField(blank=True, help_text='Board ID if request was board-specific', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(help_text='User who made the AI request', on_delete=django.db.models.deletion.CASCADE, related_name='ai_request_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Request Log',
                'verbose_name_plural': 'AI Request Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='api_aireque_user_id_fd6e48_idx'), models.Index(fields=['feature', '-timestamp'], name='api_aireque_feature_103b1a_idx')],
            },
        ),
    ]
