# Generated by Django 5.2.3 on 2026-01-23 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_aiusagequota_airequestlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiusagequota',
            name='daily_limit',
            field=models.IntegerField(default=10, help_text='Maximum AI requests allowed per day (10 for free users)'),
        ),
        migrations.AddField(
            model_name='aiusagequota',
            name='daily_requests_used',
            field=models.IntegerField(default=0, help_text='Number of AI requests made today'),
        ),
        migrations.AddField(
            model_name='aiusagequota',
            name='last_daily_reset',
            field=models.DateField(blank=True, help_text='Date of last daily counter reset', null=True),
        ),
        migrations.AlterField(
            model_name='aiusagequota',
            name='monthly_quota',
            field=models.IntegerField(default=50, help_text='Maximum AI requests allowed per month (50 for free users)'),
        ),
    ]
