# Generated by Django 5.2.3 on 2026-02-02 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_add_daily_limit_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiusagequota',
            name='daily_limit',
            field=models.IntegerField(default=999999, help_text='Maximum AI requests allowed per day (unlimited for dev testing)'),
        ),
        migrations.AlterField(
            model_name='aiusagequota',
            name='monthly_quota',
            field=models.IntegerField(default=999999, help_text='Maximum AI requests allowed per month (unlimited for dev testing)'),
        ),
    ]
