# Generated by Django 5.2.3 on 2026-07-01 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_aiusagequota_daily_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airequestlog',
            name='input_tokens',
            field=models.IntegerField(blank=True, default=0, help_text='Prompt (input) tokens, if the provider reported the split', null=True),
        ),
        migrations.AddField(
            model_name='airequestlog',
            name='output_tokens',
            field=models.IntegerField(blank=True, default=0, help_text='Generated (output) tokens, if the provider reported the split', null=True),
        ),
    ]
