# Generated by Django 5.2.3 on 2025-11-07 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0028_task_dependencies_task_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stakeholdertaskinvolvement',
            name='involvement_type',
            field=models.CharField(choices=[('owner', 'Task Owner'), ('contributor', 'Contributor'), ('reviewer', 'Reviewer'), ('approver', 'Approver/Decision Maker'), ('observer', 'Observer/Monitor'), ('beneficiary', 'Beneficiary'), ('impacted', 'Impacted Party')], default='stakeholder', help_text='Type of stakeholder involvement in task', max_length=20),
        ),
    ]
