# Generated by Django 5.2.3 on 2025-11-07 10:08

from django.db import migrations


def migrate_stakeholder_to_observer(apps, schema_editor):
    """Update existing 'stakeholder' involvement types to 'observer'"""
    StakeholderTaskInvolvement = apps.get_model('kanban', 'StakeholderTaskInvolvement')
    StakeholderTaskInvolvement.objects.filter(involvement_type='stakeholder').update(involvement_type='observer')


def reverse_migration(apps, schema_editor):
    """Reverse the migration if needed"""
    StakeholderTaskInvolvement = apps.get_model('kanban', 'StakeholderTaskInvolvement')
    StakeholderTaskInvolvement.objects.filter(involvement_type='observer').update(involvement_type='stakeholder')


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0029_update_stakeholder_involvement_types'),
    ]

    operations = [
        migrations.RunPython(migrate_stakeholder_to_observer, reverse_migration),
    ]
