# Generated by Django 5.2.3 on 2025-11-08 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0030_migrate_stakeholder_to_observer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='workload_impact',
            field=models.CharField(blank=True, choices=[('low', 'Low Impact'), ('medium', 'Medium Impact'), ('high', 'High Impact'), ('critical', 'Critical Impact')], default='medium', help_text="Impact on assignee's workload", max_length=20, null=True),
        ),
    ]
