# Generated by Django 5.2.3 on 2025-11-13 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_completed_wizard_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('kanban', '0031_alter_task_workload_impact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Role name (e.g., 'Project Manager', 'Viewer')", max_length=50)),
                ('description', models.TextField(blank=True, help_text='What this role can do')),
                ('permissions', models.JSONField(default=list, help_text="List of permission strings (e.g., ['board.view', 'task.create'])")),
                ('is_system_role', models.BooleanField(default=False, help_text='System-defined role (cannot be deleted)')),
                ('is_default', models.BooleanField(default=False, help_text='Default role for new board members')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_roles', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='Organization this role belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='accounts.organization')),
            ],
            options={
                'ordering': ['organization', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ColumnPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_move_to', models.BooleanField(default=True, help_text='Can move tasks INTO this column')),
                ('can_move_from', models.BooleanField(default=True, help_text='Can move tasks OUT OF this column')),
                ('can_create_in', models.BooleanField(default=True, help_text='Can create new tasks in this column')),
                ('can_edit_in', models.BooleanField(default=True, help_text='Can edit tasks in this column')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='column_permissions', to='kanban.column')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='column_permissions', to='kanban.role')),
            ],
        ),
        migrations.CreateModel(
            name='BoardMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this membership expires (optional)', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_board_members', to=settings.AUTH_USER_MODEL)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='kanban.board')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_memberships', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(help_text="Role defining user's permissions on this board", on_delete=django.db.models.deletion.PROTECT, related_name='board_memberships', to='kanban.role')),
            ],
            options={
                'ordering': ['board', '-added_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('action_type', models.CharField(choices=[('user.login', 'User Login'), ('user.logout', 'User Logout'), ('user.login_failed', 'Login Failed'), ('user.password_changed', 'Password Changed'), ('user.session_expired', 'Session Expired'), ('user.created', 'User Created'), ('user.updated', 'User Updated'), ('user.deleted', 'User Deleted'), ('user.profile_updated', 'Profile Updated'), ('organization.created', 'Organization Created'), ('organization.updated', 'Organization Updated'), ('organization.member_added', 'Member Added to Organization'), ('organization.member_removed', 'Member Removed from Organization'), ('board.created', 'Board Created'), ('board.updated', 'Board Updated'), ('board.deleted', 'Board Deleted'), ('board.member_added', 'Board Member Added'), ('board.member_removed', 'Board Member Removed'), ('board.viewed', 'Board Viewed'), ('column.created', 'Column Created'), ('column.updated', 'Column Updated'), ('column.deleted', 'Column Deleted'), ('column.reordered', 'Column Reordered'), ('task.created', 'Task Created'), ('task.updated', 'Task Updated'), ('task.deleted', 'Task Deleted'), ('task.field_changed', 'Task Field Changed'), ('task.assigned', 'Task Assigned'), ('task.moved', 'Task Moved Between Columns'), ('task.viewed', 'Task Viewed'), ('comment.created', 'Comment Created'), ('comment.updated', 'Comment Updated'), ('comment.deleted', 'Comment Deleted'), ('label.created', 'Label Created'), ('label.updated', 'Label Updated'), ('label.deleted', 'Label Deleted'), ('label.added_to_task', 'Label Added to Task'), ('label.removed_from_task', 'Label Removed from Task'), ('file.uploaded', 'File Uploaded'), ('file.downloaded', 'File Downloaded'), ('file.deleted', 'File Deleted'), ('permission.granted', 'Permission Granted'), ('permission.revoked', 'Permission Revoked'), ('role.assigned', 'Role Assigned'), ('role.removed', 'Role Removed'), ('access.denied', 'Access Denied'), ('token.created', 'API Token Created'), ('token.revoked', 'API Token Revoked'), ('token.used', 'API Token Used'), ('webhook.created', 'Webhook Created'), ('webhook.updated', 'Webhook Updated'), ('webhook.deleted', 'Webhook Deleted'), ('webhook.triggered', 'Webhook Triggered'), ('data.exported', 'Data Exported'), ('data.imported', 'Data Imported'), ('data.bulk_operation', 'Bulk Operation Performed'), ('system.error', 'System Error'), ('system.warning', 'System Warning')], db_index=True, max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='medium', max_length=20)),
                ('user_email', models.EmailField(blank=True, help_text='Email at time of action (preserved even if user deleted)', max_length=254)),
                ('user_username', models.CharField(blank=True, help_text='Username at time of action', max_length=150)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('object_type', models.CharField(help_text='Type of object (board, task, user, etc.)', max_length=50)),
                ('object_id_backup', models.IntegerField(help_text='ID of the affected object')),
                ('object_repr', models.CharField(help_text='Human-readable representation', max_length=255)),
                ('changes', models.JSONField(blank=True, default=dict, help_text="Dictionary of field changes: {'field_name': {'old': 'value', 'new': 'value'}}")),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Client IP address', null=True)),
                ('user_agent', models.CharField(blank=True, help_text='Browser/client user agent', max_length=255)),
                ('session_key', models.CharField(blank=True, help_text='Session identifier', max_length=40)),
                ('request_method', models.CharField(blank=True, help_text='HTTP method (GET, POST, etc.)', max_length=10)),
                ('request_path', models.CharField(blank=True, help_text='Request URL path', max_length=500)),
                ('additional_data', models.JSONField(blank=True, default=dict, help_text='Any additional context data specific to the action')),
                ('message', models.TextField(blank=True, help_text='Human-readable description of the action')),
                ('organization_id', models.IntegerField(blank=True, db_index=True, help_text='Organization ID (denormalized for performance)', null=True)),
                ('board_id', models.IntegerField(blank=True, db_index=True, help_text='Board ID (denormalized for performance)', null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'permissions': [('view_audit_log', 'Can view audit logs'), ('export_audit_log', 'Can export audit logs')],
            },
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('event_type', models.CharField(choices=[('suspicious_login', 'Suspicious Login Attempt'), ('brute_force', 'Possible Brute Force Attack'), ('unauthorized_access', 'Unauthorized Access Attempt'), ('permission_escalation', 'Permission Escalation Attempt'), ('unusual_api_usage', 'Unusual API Usage Pattern'), ('data_exfiltration', 'Possible Data Exfiltration'), ('token_compromised', 'Possibly Compromised Token'), ('multiple_failures', 'Multiple Failed Attempts')], db_index=True, max_length=50)),
                ('status', models.CharField(choices=[('new', 'New'), ('investigating', 'Under Investigation'), ('resolved', 'Resolved'), ('false_positive', 'False Positive')], db_index=True, default='new', max_length=20)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('risk_score', models.IntegerField(default=50, help_text='Risk score 0-100')),
                ('investigated_at', models.DateTimeField(blank=True, null=True)),
                ('investigation_notes', models.TextField(blank=True)),
                ('actions_taken', models.JSONField(blank=True, default=list)),
                ('notification_sent', models.BooleanField(default=False)),
                ('notification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('investigated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investigated_security_events', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('audit_logs', models.ManyToManyField(blank=True, related_name='security_events', to='kanban.systemauditlog')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DataAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('data_type', models.CharField(db_index=True, help_text='Type of sensitive data accessed (task, user_profile, etc.)', max_length=50)),
                ('record_id', models.IntegerField(help_text='ID of accessed record')),
                ('access_type', models.CharField(choices=[('read', 'Read'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('export', 'Export')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('purpose', models.TextField(blank=True, help_text='Business reason for access (if required)')),
                ('user_email', models.EmailField(blank=True, max_length=254)),
                ('organization_id', models.IntegerField(db_index=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='kanban_data_user_id_ff0a25_idx'), models.Index(fields=['data_type', 'record_id'], name='kanban_data_data_ty_b0823d_idx'), models.Index(fields=['organization_id', '-timestamp'], name='kanban_data_organiz_f8bb81_idx')],
            },
        ),
        migrations.CreateModel(
            name='PermissionOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(help_text="Permission to override (e.g., 'task.delete')", max_length=50)),
                ('override_type', models.CharField(choices=[('grant', 'Grant Permission'), ('deny', 'Deny Permission')], help_text='Whether to grant or explicitly deny this permission', max_length=10)),
                ('reason', models.TextField(blank=True, help_text='Reason for this permission override')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this override expires (optional)', null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_permission_overrides', to=settings.AUTH_USER_MODEL)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_overrides', to='kanban.boardmembership')),
            ],
            options={
                'ordering': ['membership', 'permission'],
                'unique_together': {('membership', 'permission')},
            },
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['organization', 'name'], name='kanban_role_organiz_cdfe41_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('organization', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='columnpermission',
            unique_together={('column', 'role')},
        ),
        migrations.AddIndex(
            model_name='boardmembership',
            index=models.Index(fields=['board', 'user'], name='kanban_boar_board_i_a4a952_idx'),
        ),
        migrations.AddIndex(
            model_name='boardmembership',
            index=models.Index(fields=['user', 'is_active'], name='kanban_boar_user_id_0ca23e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='boardmembership',
            unique_together={('board', 'user')},
        ),
        migrations.AddIndex(
            model_name='systemauditlog',
            index=models.Index(fields=['-timestamp'], name='kanban_syst_timesta_f664bb_idx'),
        ),
        migrations.AddIndex(
            model_name='systemauditlog',
            index=models.Index(fields=['user', '-timestamp'], name='kanban_syst_user_id_ec27a9_idx'),
        ),
        migrations.AddIndex(
            model_name='systemauditlog',
            index=models.Index(fields=['action_type', '-timestamp'], name='kanban_syst_action__941870_idx'),
        ),
        migrations.AddIndex(
            model_name='systemauditlog',
            index=models.Index(fields=['object_type', 'object_id_backup'], name='kanban_syst_object__294177_idx'),
        ),
        migrations.AddIndex(
            model_name='systemauditlog',
            index=models.Index(fields=['organization_id', '-timestamp'], name='kanban_syst_organiz_ae7361_idx'),
        ),
        migrations.AddIndex(
            model_name='systemauditlog',
            index=models.Index(fields=['board_id', '-timestamp'], name='kanban_syst_board_i_ef2a0f_idx'),
        ),
        migrations.AddIndex(
            model_name='systemauditlog',
            index=models.Index(fields=['severity', '-timestamp'], name='kanban_syst_severit_feb1bf_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['status', '-timestamp'], name='kanban_secu_status_73f374_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['user', '-timestamp'], name='kanban_secu_user_id_5345e5_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['ip_address', '-timestamp'], name='kanban_secu_ip_addr_c5b74d_idx'),
        ),
    ]
