# Generated by Django 5.2.3 on 2025-11-18 03:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0032_role_columnpermission_boardmembership_systemauditlog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='actual_duration_days',
            field=models.FloatField(blank=True, help_text='Actual days taken to complete (start_date to completed_at)', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='Actual completion timestamp (when progress reached 100%)', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='last_prediction_update',
            field=models.DateTimeField(blank=True, help_text='When prediction was last calculated', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='predicted_completion_date',
            field=models.DateTimeField(blank=True, help_text='AI-predicted completion date based on historical data', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='prediction_confidence',
            field=models.FloatField(blank=True, help_text='Confidence score for prediction (0.0-1.0)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='task',
            name='prediction_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Prediction details: confidence_interval, based_on_tasks, factors'),
        ),
    ]
