# Generated by Django 5.2.3 on 2025-11-18 05:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0033_task_actual_duration_days_task_completed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['task', '-created_at'], name='kanban_comm_task_id_6e23a3_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['user'], name='kanban_comm_user_id_8d8922_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['column', 'position'], name='kanban_task_column__4fa4b9_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assigned_to'], name='kanban_task_assigne_909dd2_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['created_by'], name='kanban_task_created_0f3106_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['due_date'], name='kanban_task_due_dat_e1e907_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['progress'], name='kanban_task_progres_e7e6f2_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['priority'], name='kanban_task_priorit_bdef99_idx'),
        ),
        migrations.AddIndex(
            model_name='taskactivity',
            index=models.Index(fields=['task', '-created_at'], name='kanban_task_task_id_7f2e12_idx'),
        ),
        migrations.AddIndex(
            model_name='taskactivity',
            index=models.Index(fields=['user'], name='kanban_task_user_id_530d81_idx'),
        ),
        migrations.AddIndex(
            model_name='taskactivity',
            index=models.Index(fields=['activity_type'], name='kanban_task_activit_967d35_idx'),
        ),
    ]
