# Generated by Django 5.2.3 on 2025-11-19 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0034_comment_kanban_comm_task_id_6e23a3_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriorityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_version', models.IntegerField(default=1, help_text='Version number of this model')),
                ('model_type', models.CharField(default='random_forest', help_text='Type of ML model used', max_length=50)),
                ('model_file', models.BinaryField(help_text='Serialized model (pickle)')),
                ('feature_importance', models.JSONField(default=dict, help_text='Feature importance scores for explainability')),
                ('trained_at', models.DateTimeField(auto_now_add=True, help_text='When model was trained')),
                ('training_samples', models.IntegerField(help_text='Number of samples used for training')),
                ('accuracy_score', models.FloatField(help_text='Model accuracy on test set')),
                ('precision_scores', models.JSONField(default=dict, help_text='Precision per priority class')),
                ('recall_scores', models.JSONField(default=dict, help_text='Recall per priority class')),
                ('f1_scores', models.JSONField(default=dict, help_text='F1 scores per priority class')),
                ('confusion_matrix', models.JSONField(default=list, help_text='Confusion matrix for model evaluation')),
                ('is_active', models.BooleanField(default=True, help_text='Is this the active model for predictions?')),
                ('board', models.ForeignKey(help_text='Board this model is trained for', on_delete=django.db.models.deletion.CASCADE, related_name='priority_models', to='kanban.board')),
            ],
            options={
                'ordering': ['-trained_at'],
            },
        ),
        migrations.CreateModel(
            name='PrioritySuggestionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_priority', models.CharField(max_length=10)),
                ('confidence_score', models.FloatField()),
                ('reasoning', models.JSONField(default=dict)),
                ('feature_values', models.JSONField(default=dict, help_text='Feature values used for prediction')),
                ('shown_at', models.DateTimeField(auto_now_add=True)),
                ('user_action', models.CharField(blank=True, choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('modified', 'Modified'), ('ignored', 'Ignored')], help_text='How user responded to suggestion', max_length=20, null=True)),
                ('actual_priority', models.CharField(blank=True, help_text='Priority user actually chose', max_length=10, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestions', to='kanban.prioritymodel')),
                ('shown_to_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='priority_suggestions_received', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='priority_suggestions', to='kanban.task')),
            ],
            options={
                'ordering': ['-shown_at'],
            },
        ),
        migrations.CreateModel(
            name='PriorityDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_priority', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], help_text='AI-suggested priority (null for manual decisions)', max_length=10, null=True)),
                ('actual_priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], help_text='Priority that was actually assigned', max_length=10)),
                ('previous_priority', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], help_text='Previous priority (for corrections)', max_length=10, null=True)),
                ('decision_type', models.CharField(choices=[('initial', 'Initial Assignment'), ('correction', 'Manual Correction'), ('ai_suggestion', 'AI Suggested'), ('ai_accepted', 'AI Suggestion Accepted'), ('ai_rejected', 'AI Suggestion Rejected')], default='initial', help_text='Type of priority decision', max_length=20)),
                ('decided_at', models.DateTimeField(auto_now_add=True, help_text='When decision was made')),
                ('task_context', models.JSONField(default=dict, help_text='Task features at decision time: due_date, dependencies, etc.')),
                ('confidence_score', models.FloatField(blank=True, help_text='AI confidence in suggestion (0.0-1.0)', null=True)),
                ('reasoning', models.JSONField(blank=True, default=dict, help_text='AI reasoning for the suggestion')),
                ('was_correct', models.BooleanField(blank=True, help_text='Whether AI suggestion was accepted (null for manual decisions)', null=True)),
                ('feedback_notes', models.TextField(blank=True, help_text='Optional user feedback on why they accepted/rejected')),
                ('board', models.ForeignKey(help_text='Board for organizational filtering', on_delete=django.db.models.deletion.CASCADE, related_name='priority_decisions', to='kanban.board')),
                ('decided_by', models.ForeignKey(help_text='User who made this decision', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='priority_decisions', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(help_text='Task this decision is for', on_delete=django.db.models.deletion.CASCADE, related_name='priority_decisions', to='kanban.task')),
            ],
            options={
                'ordering': ['-decided_at'],
                'indexes': [models.Index(fields=['task', '-decided_at'], name='kanban_prio_task_id_16602c_idx'), models.Index(fields=['board', '-decided_at'], name='kanban_prio_board_i_b760a7_idx'), models.Index(fields=['decided_by', '-decided_at'], name='kanban_prio_decided_6ff3c0_idx'), models.Index(fields=['decision_type'], name='kanban_prio_decisio_bfef34_idx'), models.Index(fields=['was_correct'], name='kanban_prio_was_cor_9fd3f3_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='prioritymodel',
            index=models.Index(fields=['board', 'is_active'], name='kanban_prio_board_i_5d1c97_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='prioritymodel',
            unique_together={('board', 'model_version')},
        ),
        migrations.AddIndex(
            model_name='prioritysuggestionlog',
            index=models.Index(fields=['task', '-shown_at'], name='kanban_prio_task_id_7f30ff_idx'),
        ),
        migrations.AddIndex(
            model_name='prioritysuggestionlog',
            index=models.Index(fields=['model', '-shown_at'], name='kanban_prio_model_i_c2c860_idx'),
        ),
        migrations.AddIndex(
            model_name='prioritysuggestionlog',
            index=models.Index(fields=['user_action'], name='kanban_prio_user_ac_e5eeb3_idx'),
        ),
    ]
