# Generated by Django 5.2.3 on 2025-11-19 16:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0035_prioritymodel_prioritysuggestionlog_prioritydecision_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillGap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(help_text='Name of the missing/insufficient skill', max_length=100)),
                ('proficiency_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], help_text='Required proficiency level', max_length=20)),
                ('required_count', models.IntegerField(default=1, help_text='Number of team members needed with this skill')),
                ('available_count', models.IntegerField(default=0, help_text='Number of team members currently with this skill')),
                ('gap_count', models.IntegerField(help_text='Difference between required and available (auto-calculated)')),
                ('severity', models.CharField(choices=[('low', 'Low - Can work around'), ('medium', 'Medium - May cause delays'), ('high', 'High - Blocking work'), ('critical', 'Critical - Cannot proceed')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('identified', 'Identified'), ('acknowledged', 'Acknowledged'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('accepted', 'Accepted Risk')], default='identified', max_length=20)),
                ('sprint_period_start', models.DateField(blank=True, help_text='Sprint/period when gap was identified', null=True)),
                ('sprint_period_end', models.DateField(blank=True, null=True)),
                ('ai_recommendations', models.JSONField(default=list, help_text="AI-generated recommendations: [{'type': 'hire', 'details': '...', 'priority': 1}]")),
                ('estimated_impact_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated hours of delay/impact if not addressed', max_digits=10, null=True)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0.75, help_text='AI confidence in this gap analysis (0-1)', max_digits=3)),
                ('identified_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_skill_gaps', to=settings.AUTH_USER_MODEL)),
                ('affected_tasks', models.ManyToManyField(blank=True, help_text='Tasks that require this skill', related_name='skill_gaps', to='kanban.task')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_gaps', to='kanban.board')),
            ],
            options={
                'verbose_name': 'Skill Gap',
                'verbose_name_plural': 'Skill Gaps',
                'ordering': ['-severity', '-identified_at'],
            },
        ),
        migrations.CreateModel(
            name='SkillDevelopmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('training', 'Training/Upskilling'), ('hiring', 'Hire New Resource'), ('contractor', 'Contract Resource'), ('redistribute', 'Redistribute Work'), ('mentorship', 'Mentorship Program'), ('cross_training', 'Cross Training')], max_length=20)),
                ('title', models.CharField(help_text='Brief title of the development plan', max_length=200)),
                ('description', models.TextField(help_text='Detailed plan description and action steps')),
                ('target_skill', models.CharField(help_text='Skill being developed', max_length=100)),
                ('target_proficiency', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('target_completion_date', models.DateField(blank=True, null=True)),
                ('actual_completion_date', models.DateField(blank=True, null=True)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated cost (training fees, hiring budget, etc.)', max_digits=10, null=True)),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated hours investment', max_digits=8, null=True)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('approved', 'Approved'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='proposed', max_length=20)),
                ('progress_percentage', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('expected_impact', models.TextField(blank=True, help_text='Expected impact on team capability')),
                ('actual_impact', models.TextField(blank=True, help_text='Measured impact after completion')),
                ('success_metrics', models.JSONField(blank=True, default=list, help_text="Metrics to track success: [{'metric': 'Tasks completed', 'target': 5, 'actual': 3}]")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_suggested', models.BooleanField(default=False, help_text='Was this plan AI-generated?')),
                ('ai_confidence', models.DecimalField(blank=True, decimal_places=2, help_text='AI confidence in this recommendation (0-1)', max_digits=3, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Person responsible for executing this plan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_development_plans', to=settings.AUTH_USER_MODEL)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_development_plans', to='kanban.board')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_development_plans', to=settings.AUTH_USER_MODEL)),
                ('target_users', models.ManyToManyField(blank=True, help_text='Team members involved in this plan', related_name='skill_development_plans', to=settings.AUTH_USER_MODEL)),
                ('skill_gap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='development_plans', to='kanban.skillgap')),
            ],
            options={
                'verbose_name': 'Skill Development Plan',
                'verbose_name_plural': 'Skill Development Plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamSkillProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_inventory', models.JSONField(default=dict, help_text="Dictionary of available skills: {'Python': {'expert': 2, 'intermediate': 3, 'beginner': 1}}")),
                ('total_capacity_hours', models.DecimalField(decimal_places=2, default=0, help_text='Total team capacity in hours per week', max_digits=10)),
                ('utilized_capacity_hours', models.DecimalField(decimal_places=2, default=0, help_text='Currently utilized hours', max_digits=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('last_analysis', models.DateTimeField(blank=True, help_text='Last AI skill analysis timestamp', null=True)),
                ('board', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='skill_profile', to='kanban.board')),
            ],
            options={
                'verbose_name': 'Team Skill Profile',
                'verbose_name_plural': 'Team Skill Profiles',
            },
        ),
        migrations.AddIndex(
            model_name='skillgap',
            index=models.Index(fields=['board', 'status'], name='kanban_skil_board_i_440c00_idx'),
        ),
        migrations.AddIndex(
            model_name='skillgap',
            index=models.Index(fields=['skill_name', 'proficiency_level'], name='kanban_skil_skill_n_b1a83c_idx'),
        ),
        migrations.AddIndex(
            model_name='skilldevelopmentplan',
            index=models.Index(fields=['board', 'status'], name='kanban_skil_board_i_6c140c_idx'),
        ),
        migrations.AddIndex(
            model_name='skilldevelopmentplan',
            index=models.Index(fields=['skill_gap'], name='kanban_skil_skill_g_084057_idx'),
        ),
    ]
