# Generated by Django 5.2.3 on 2025-11-20 05:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0036_skillgap_skilldevelopmentplan_teamskillprofile_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamVelocitySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(help_text='Start date of velocity measurement period')),
                ('period_end', models.DateField(help_text='End date of velocity measurement period')),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('sprint', 'Sprint'), ('monthly', 'Monthly')], default='weekly', max_length=20)),
                ('tasks_completed', models.IntegerField(default=0, help_text='Number of tasks completed in period')),
                ('story_points_completed', models.DecimalField(decimal_places=2, default=0, help_text='Story points/complexity completed', max_digits=10)),
                ('hours_completed', models.DecimalField(decimal_places=2, default=0, help_text='Estimated hours of work completed', max_digits=10)),
                ('active_team_members', models.IntegerField(default=0, help_text='Number of active team members in period')),
                ('team_member_list', models.JSONField(blank=True, default=list, help_text='List of team member IDs')),
                ('tasks_reopened', models.IntegerField(default=0, help_text='Tasks that were reopened/rejected')),
                ('quality_score', models.DecimalField(decimal_places=2, default=100, help_text='Quality score (100 - reopened_percentage)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='velocity_snapshots', to='kanban.board')),
                ('calculated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calculated_velocities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Team Velocity Snapshot',
                'verbose_name_plural': 'Team Velocity Snapshots',
                'ordering': ['-period_end', '-period_start'],
            },
        ),
        migrations.CreateModel(
            name='BurndownPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_date', models.DateTimeField(auto_now_add=True, help_text='When this prediction was generated')),
                ('prediction_type', models.CharField(choices=[('burndown', 'Burndown (work remaining)'), ('burnup', 'Burnup (work completed)')], default='burndown', max_length=20)),
                ('total_tasks', models.IntegerField(default=0, help_text='Total tasks in scope')),
                ('completed_tasks', models.IntegerField(default=0, help_text='Tasks completed so far')),
                ('remaining_tasks', models.IntegerField(default=0, help_text='Tasks remaining')),
                ('total_story_points', models.DecimalField(decimal_places=2, default=0, help_text='Total story points/complexity', max_digits=10)),
                ('completed_story_points', models.DecimalField(decimal_places=2, default=0, help_text='Completed story points', max_digits=10)),
                ('remaining_story_points', models.DecimalField(decimal_places=2, default=0, help_text='Remaining story points', max_digits=10)),
                ('current_velocity', models.DecimalField(decimal_places=2, default=0, help_text='Current team velocity (tasks/week)', max_digits=10)),
                ('average_velocity', models.DecimalField(decimal_places=2, default=0, help_text='Historical average velocity', max_digits=10)),
                ('velocity_std_dev', models.DecimalField(decimal_places=2, default=0, help_text='Standard deviation of velocity (measures variance/noise)', max_digits=10)),
                ('velocity_trend', models.CharField(choices=[('increasing', 'Increasing'), ('stable', 'Stable'), ('decreasing', 'Decreasing'), ('insufficient_data', 'Insufficient Data')], default='stable', max_length=20)),
                ('predicted_completion_date', models.DateField(help_text='Most likely completion date (50th percentile)')),
                ('completion_date_lower_bound', models.DateField(help_text='Early completion date (10th percentile)')),
                ('completion_date_upper_bound', models.DateField(help_text='Late completion date (90th percentile)')),
                ('days_until_completion_estimate', models.IntegerField(default=0, help_text='Estimated days until completion')),
                ('days_margin_of_error', models.IntegerField(default=0, help_text='±days margin of error (half of confidence interval width)')),
                ('confidence_percentage', models.IntegerField(default=90, help_text='Confidence level (typically 90%)', validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(99)])),
                ('prediction_confidence_score', models.DecimalField(decimal_places=2, default=0.5, help_text='Overall confidence in prediction (0-1)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('delay_probability', models.DecimalField(decimal_places=2, default=0, help_text='Probability of missing target date (%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk - On Track'), ('medium', 'Medium Risk - Monitor'), ('high', 'High Risk - Action Needed'), ('critical', 'Critical Risk - Intervention Required')], default='low', max_length=20)),
                ('target_completion_date', models.DateField(blank=True, help_text='Target/planned completion date (if set)', null=True)),
                ('will_meet_target', models.BooleanField(default=True, help_text='Will predicted date meet target?')),
                ('days_ahead_behind_target', models.IntegerField(default=0, help_text='Days ahead (positive) or behind (negative) target')),
                ('burndown_curve_data', models.JSONField(blank=True, default=dict, help_text='Historical and projected burndown data points')),
                ('confidence_bands_data', models.JSONField(blank=True, default=dict, help_text='Upper and lower confidence band data for visualization')),
                ('velocity_history_data', models.JSONField(blank=True, default=list, help_text='Historical velocity measurements used in prediction')),
                ('actionable_suggestions', models.JSONField(blank=True, default=list, help_text='AI-generated suggestions to improve completion probability')),
                ('model_parameters', models.JSONField(blank=True, default=dict, help_text='Statistical model parameters and assumptions')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='burndown_predictions', to='kanban.board')),
                ('based_on_velocity_snapshots', models.ManyToManyField(blank=True, help_text='Velocity snapshots used to generate this prediction', related_name='predictions', to='kanban.teamvelocitysnapshot')),
            ],
            options={
                'verbose_name': 'Burndown Prediction',
                'verbose_name_plural': 'Burndown Predictions',
                'ordering': ['-prediction_date'],
            },
        ),
        migrations.CreateModel(
            name='BurndownAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('velocity_drop', 'Velocity Dropped'), ('scope_creep', 'Scope Increased'), ('target_risk', 'Target Date at Risk'), ('variance_high', 'High Velocity Variance'), ('stagnation', 'Progress Stagnated'), ('quality_issue', 'Quality Issues Detected')], max_length=20)),
                ('severity', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='active', max_length=20)),
                ('title', models.CharField(help_text='Brief alert title', max_length=200)),
                ('message', models.TextField(help_text='Detailed alert message')),
                ('metric_value', models.DecimalField(blank=True, decimal_places=2, help_text='Relevant metric value (e.g., velocity, delay probability)', max_digits=10, null=True)),
                ('threshold_value', models.DecimalField(blank=True, decimal_places=2, help_text='Threshold that triggered this alert', max_digits=10, null=True)),
                ('suggested_actions', models.JSONField(blank=True, default=list, help_text='Suggested actions to address this alert')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_burndown_alerts', to=settings.AUTH_USER_MODEL)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='burndown_alerts', to='kanban.board')),
                ('prediction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='kanban.burndownprediction')),
            ],
            options={
                'verbose_name': 'Burndown Alert',
                'verbose_name_plural': 'Burndown Alerts',
                'ordering': ['-severity', '-created_at'],
                'indexes': [models.Index(fields=['board', 'status', '-created_at'], name='kanban_burn_board_i_9b8c24_idx'), models.Index(fields=['prediction', 'severity'], name='kanban_burn_predict_dd38b7_idx')],
            },
        ),
        migrations.CreateModel(
            name='SprintMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Milestone name (e.g., 'Sprint 1 End', 'MVP Release')", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Milestone description')),
                ('target_date', models.DateField(help_text='Target completion date')),
                ('actual_date', models.DateField(blank=True, help_text='Actual completion date', null=True)),
                ('target_tasks_completed', models.IntegerField(default=0, help_text='Expected tasks completed by this milestone')),
                ('target_story_points', models.DecimalField(decimal_places=2, default=0, help_text='Expected story points by this milestone', max_digits=10)),
                ('is_completed', models.BooleanField(default=False)),
                ('completion_percentage', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprint_milestones', to='kanban.board')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_milestones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sprint Milestone',
                'verbose_name_plural': 'Sprint Milestones',
                'ordering': ['target_date'],
                'indexes': [models.Index(fields=['board', 'target_date'], name='kanban_spri_board_i_a74527_idx'), models.Index(fields=['is_completed'], name='kanban_spri_is_comp_55b1c5_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='teamvelocitysnapshot',
            index=models.Index(fields=['board', '-period_end'], name='kanban_team_board_i_ecfc83_idx'),
        ),
        migrations.AddIndex(
            model_name='teamvelocitysnapshot',
            index=models.Index(fields=['period_start', 'period_end'], name='kanban_team_period__e64dad_idx'),
        ),
        migrations.AddIndex(
            model_name='burndownprediction',
            index=models.Index(fields=['board', '-prediction_date'], name='kanban_burn_board_i_69ca3c_idx'),
        ),
        migrations.AddIndex(
            model_name='burndownprediction',
            index=models.Index(fields=['predicted_completion_date'], name='kanban_burn_predict_51cfc7_idx'),
        ),
    ]
