# Generated by Django 5.2.3 on 2025-11-20 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0037_teamvelocitysnapshot_burndownprediction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='burndownprediction',
            name='will_meet_target',
            field=models.BooleanField(blank=True, default=True, help_text='Will predicted date meet target?', null=True),
        ),
    ]
