# Generated by Django 5.2.3 on 2025-11-20 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0038_alter_burndownprediction_will_meet_target'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='baseline_complexity_total',
            field=models.IntegerField(blank=True, help_text='Baseline complexity total', null=True),
        ),
        migrations.AddField(
            model_name='board',
            name='baseline_set_by',
            field=models.ForeignKey(blank=True, help_text='User who set the baseline', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baseline_boards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='board',
            name='baseline_set_date',
            field=models.DateTimeField(blank=True, help_text='When the baseline was established', null=True),
        ),
        migrations.AddField(
            model_name='board',
            name='baseline_task_count',
            field=models.IntegerField(blank=True, help_text='Baseline task count for scope tracking', null=True),
        ),
        migrations.CreateModel(
            name='ScopeChangeSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateTimeField(auto_now_add=True)),
                ('total_tasks', models.IntegerField(help_text='Total number of tasks')),
                ('total_complexity_points', models.IntegerField(default=0, help_text='Sum of all task complexity scores')),
                ('avg_complexity', models.FloatField(default=0.0, help_text='Average complexity per task')),
                ('high_priority_tasks', models.IntegerField(default=0, help_text='Count of high/urgent priority tasks')),
                ('urgent_priority_tasks', models.IntegerField(default=0, help_text='Count of urgent priority tasks')),
                ('todo_tasks', models.IntegerField(default=0, help_text='Tasks in To Do columns')),
                ('in_progress_tasks', models.IntegerField(default=0, help_text='Tasks in In Progress columns')),
                ('completed_tasks', models.IntegerField(default=0, help_text='Tasks in Done columns')),
                ('is_baseline', models.BooleanField(default=False, help_text='Is this the baseline snapshot?')),
                ('scope_change_percentage', models.FloatField(blank=True, help_text='Percentage change from baseline', null=True)),
                ('complexity_change_percentage', models.FloatField(blank=True, help_text='Percentage change in complexity', null=True)),
                ('ai_analysis', models.JSONField(blank=True, help_text='AI-generated analysis of scope changes', null=True)),
                ('predicted_delay_days', models.IntegerField(blank=True, help_text='AI-predicted delay in days', null=True)),
                ('snapshot_type', models.CharField(choices=[('manual', 'Manual'), ('scheduled', 'Scheduled'), ('milestone', 'Milestone')], default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this snapshot', null=True)),
                ('baseline_snapshot', models.ForeignKey(blank=True, help_text='Reference to baseline snapshot for comparison', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comparison_snapshots', to='kanban.scopechangesnapshot')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scope_snapshots', to='kanban.board')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Scope Change Snapshot',
                'verbose_name_plural': 'Scope Change Snapshots',
                'ordering': ['-snapshot_date'],
            },
        ),
        migrations.CreateModel(
            name='ScopeCreepAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('info', 'Info - Minor increase (<15%)'), ('warning', 'Warning - Moderate increase (15-30%)'), ('critical', 'Critical - Major increase (>30%)')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='active', max_length=20)),
                ('scope_increase_percentage', models.FloatField(help_text='Percentage increase in task count')),
                ('complexity_increase_percentage', models.FloatField(default=0.0, help_text='Percentage increase in complexity')),
                ('tasks_added', models.IntegerField(default=0, help_text='Number of tasks added')),
                ('predicted_delay_days', models.IntegerField(blank=True, help_text='Estimated project delay in days', null=True)),
                ('timeline_at_risk', models.BooleanField(default=False, help_text='Is the project timeline at risk?')),
                ('recommendations', models.JSONField(default=list, help_text='AI-generated recommendations')),
                ('ai_summary', models.TextField(blank=True, help_text='AI-generated summary of scope changes', null=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, help_text='Notes on how the alert was resolved', null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_scope_alerts', to=settings.AUTH_USER_MODEL)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scope_creep_alerts', to='kanban.board')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_scope_alerts', to=settings.AUTH_USER_MODEL)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_alerts', to='kanban.scopechangesnapshot')),
            ],
            options={
                'verbose_name': 'Scope Creep Alert',
                'verbose_name_plural': 'Scope Creep Alerts',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.AddIndex(
            model_name='scopechangesnapshot',
            index=models.Index(fields=['board', '-snapshot_date'], name='kanban_scop_board_i_90082c_idx'),
        ),
        migrations.AddIndex(
            model_name='scopechangesnapshot',
            index=models.Index(fields=['board', 'is_baseline'], name='kanban_scop_board_i_f72114_idx'),
        ),
        migrations.AddIndex(
            model_name='scopecreepalert',
            index=models.Index(fields=['board', 'status', '-detected_at'], name='kanban_scop_board_i_802b17_idx'),
        ),
        migrations.AddIndex(
            model_name='scopecreepalert',
            index=models.Index(fields=['severity', 'status'], name='kanban_scop_severit_26296b_idx'),
        ),
    ]
