# Generated by Django 5.2.3 on 2025-11-20 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0040_add_retrospective_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectretrospective',
            name='ai_model_used',
            field=models.CharField(default='gemini-2.5-flash', help_text='AI model used for generation', max_length=50),
        ),
    ]
