# Generated by Django 5.2.3 on 2025-11-24 06:54

import colorfield.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0041_alter_projectretrospective_ai_model_used'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Milestone name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the milestone', null=True)),
                ('target_date', models.DateField(help_text='Target date for this milestone')),
                ('milestone_type', models.CharField(choices=[('project_start', 'Project Start'), ('phase_completion', 'Phase Completion'), ('deliverable', 'Deliverable'), ('review', 'Review/Approval'), ('project_end', 'Project End'), ('custom', 'Custom')], default='custom', help_text='Type of milestone', max_length=20)),
                ('is_completed', models.BooleanField(default=False, help_text='Whether this milestone has been achieved')),
                ('completed_date', models.DateField(blank=True, help_text='Actual completion date', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('color', colorfield.fields.ColorField(default='#FFD700', help_text='Color for milestone marker on Gantt chart', image_field=None, max_length=25, samples=None)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='kanban.board')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestone_creations', to=settings.AUTH_USER_MODEL)),
                ('related_tasks', models.ManyToManyField(blank=True, help_text='Tasks that must be completed for this milestone', related_name='milestones', to='kanban.task')),
            ],
            options={
                'ordering': ['target_date', 'created_at'],
                'indexes': [models.Index(fields=['board', 'target_date'], name='kanban_mile_board_i_564061_idx'), models.Index(fields=['is_completed'], name='kanban_mile_is_comp_037540_idx')],
            },
        ),
    ]
