# Generated by Django 5.2.3 on 2025-12-08 03:25

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0042_milestone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_budget', models.DecimalField(decimal_places=2, help_text='Total allocated budget for the project', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('INR', 'Indian Rupee'), ('JPY', 'Japanese Yen')], default='USD', help_text='Currency for budget tracking', max_length=3)),
                ('allocated_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Total allocated hours for the project', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('warning_threshold', models.IntegerField(default=80, help_text='Warning threshold percentage (e.g., 80 for 80%)', validators=[django.core.validators.MinValueValidator(1)])),
                ('critical_threshold', models.IntegerField(default=95, help_text='Critical threshold percentage (e.g., 95 for 95%)', validators=[django.core.validators.MinValueValidator(1)])),
                ('ai_optimization_enabled', models.BooleanField(default=True, help_text='Enable AI-powered budget optimization')),
                ('last_ai_analysis', models.DateTimeField(blank=True, help_text='Last time AI analyzed this budget', null=True)),
                ('board', models.OneToOneField(help_text='Board this budget is for', on_delete=django.db.models.deletion.CASCADE, related_name='budget', to='kanban.board')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_budgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project Budget',
                'verbose_name_plural': 'Project Budgets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Estimated cost for this task', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('estimated_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Estimated hours for this task', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('actual_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Actual cost incurred', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Hourly rate for labor cost calculation', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('resource_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cost of resources/materials', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.OneToOneField(help_text='Task this cost is for', on_delete=django.db.models.deletion.CASCADE, related_name='cost', to='kanban.task')),
            ],
            options={
                'verbose_name': 'Task Cost',
                'verbose_name_plural': 'Task Costs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BudgetRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(choices=[('reallocation', 'Budget Reallocation'), ('scope_cut', 'Scope Reduction'), ('timeline_change', 'Timeline Adjustment'), ('resource_optimization', 'Resource Optimization'), ('risk_mitigation', 'Risk Mitigation'), ('efficiency_improvement', 'Efficiency Improvement')], help_text='Type of recommendation', max_length=30)),
                ('title', models.CharField(help_text='Recommendation title', max_length=200)),
                ('description', models.TextField(help_text='Detailed recommendation description')),
                ('estimated_savings', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated cost savings', max_digits=10, null=True)),
                ('confidence_score', models.IntegerField(help_text='AI confidence score (0-100)', validators=[django.core.validators.MinValueValidator(0)])),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('implemented', 'Implemented')], default='pending', max_length=15)),
                ('ai_reasoning', models.TextField(help_text='AI reasoning for this recommendation')),
                ('based_on_patterns', models.JSONField(blank=True, help_text='Historical patterns that informed this recommendation', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('board', models.ForeignKey(help_text='Board this recommendation is for', on_delete=django.db.models.deletion.CASCADE, related_name='budget_recommendations', to='kanban.board')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Budget Recommendation',
                'verbose_name_plural': 'Budget Recommendations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['board', 'status'], name='kanban_budg_board_i_ec43ec_idx'), models.Index(fields=['recommendation_type', 'status'], name='kanban_budg_recomme_e15db1_idx')],
            },
        ),
        migrations.CreateModel(
            name='CostPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_name', models.CharField(help_text='Name/identifier for this pattern', max_length=100)),
                ('pattern_type', models.CharField(help_text="Type of pattern (e.g., 'task_overrun', 'resource_spike')", max_length=50)),
                ('pattern_data', models.JSONField(help_text='Structured pattern data for ML analysis')),
                ('confidence', models.DecimalField(decimal_places=2, help_text='Pattern confidence score (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('occurrence_count', models.IntegerField(default=1, help_text='Number of times this pattern has been observed')),
                ('last_occurred', models.DateTimeField(default=django.utils.timezone.now, help_text='Last time this pattern was observed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('board', models.ForeignKey(help_text='Board this pattern was learned from', on_delete=django.db.models.deletion.CASCADE, related_name='cost_patterns', to='kanban.board')),
            ],
            options={
                'verbose_name': 'Cost Pattern',
                'verbose_name_plural': 'Cost Patterns',
                'ordering': ['-last_occurred'],
                'unique_together': {('board', 'pattern_name')},
            },
        ),
        migrations.CreateModel(
            name='ProjectROI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_value', models.DecimalField(blank=True, decimal_places=2, help_text='Expected value/revenue from project', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('realized_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Actual realized value', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('snapshot_date', models.DateTimeField(default=django.utils.timezone.now, help_text='When this ROI snapshot was taken')),
                ('total_cost', models.DecimalField(decimal_places=2, help_text='Total cost at snapshot time', max_digits=12)),
                ('roi_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='ROI percentage: (Value - Cost) / Cost * 100', max_digits=8, null=True)),
                ('completed_tasks', models.IntegerField(default=0, help_text='Number of completed tasks')),
                ('total_tasks', models.IntegerField(default=0, help_text='Total number of tasks')),
                ('ai_insights', models.JSONField(blank=True, help_text='AI-generated insights and recommendations', null=True)),
                ('ai_risk_score', models.IntegerField(blank=True, help_text='AI-calculated risk score (0-100)', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(help_text='Board this ROI analysis is for', on_delete=django.db.models.deletion.CASCADE, related_name='roi_analyses', to='kanban.board')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roi_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project ROI',
                'verbose_name_plural': 'Project ROI Analyses',
                'ordering': ['-snapshot_date'],
                'indexes': [models.Index(fields=['board', '-snapshot_date'], name='kanban_proj_board_i_bc015b_idx')],
            },
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_spent', models.DecimalField(decimal_places=2, help_text='Hours spent on this task', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('work_date', models.DateField(help_text='Date when work was performed')),
                ('description', models.TextField(blank=True, help_text='Description of work performed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(help_text='Task this time entry is for', on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='kanban.task')),
                ('user', models.ForeignKey(help_text='User who logged this time', on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Time Entry',
                'verbose_name_plural': 'Time Entries',
                'ordering': ['-work_date', '-created_at'],
                'indexes': [models.Index(fields=['task', 'work_date'], name='kanban_time_task_id_afe347_idx'), models.Index(fields=['user', 'work_date'], name='kanban_time_user_id_57b19a_idx')],
            },
        ),
    ]
