# Generated by Django 5.2.3 on 2025-12-08 06:04

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0043_projectbudget_taskcost_budgetrecommendation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachingInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(choices=[('pattern', 'Pattern Recognition'), ('effectiveness', 'Suggestion Effectiveness'), ('pm_behavior', 'PM Behavior Pattern'), ('team_dynamics', 'Team Dynamics'), ('context_factor', 'Context Factor')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='What was learned')),
                ('confidence_score', models.DecimalField(decimal_places=2, help_text='Confidence in this insight (0-1)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('sample_size', models.IntegerField(default=0, help_text='Number of data points supporting this insight')),
                ('applicable_to_suggestion_types', models.JSONField(default=list, help_text='Which suggestion types this insight applies to')),
                ('rule_adjustments', models.JSONField(blank=True, default=dict, help_text='How rules should be adjusted based on this insight')),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('last_validated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this insight currently being applied?')),
            ],
            options={
                'ordering': ['-confidence_score', '-sample_size'],
            },
        ),
        migrations.CreateModel(
            name='CoachingSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion_type', models.CharField(choices=[('velocity_drop', 'Velocity Dropping'), ('resource_overload', 'Resource Overloaded'), ('risk_convergence', 'Multiple Risks Converging'), ('skill_opportunity', 'Skill Development Opportunity'), ('scope_creep', 'Scope Creep Detected'), ('deadline_risk', 'Deadline at Risk'), ('team_burnout', 'Team Burnout Risk'), ('quality_issue', 'Quality Issues Detected'), ('communication_gap', 'Communication Gap'), ('dependency_blocker', 'Dependency Blocking Progress'), ('best_practice', 'Best Practice Recommendation')], max_length=30)),
                ('severity', models.CharField(choices=[('info', 'Information'), ('low', 'Low Priority'), ('medium', 'Medium Priority'), ('high', 'High Priority'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('acknowledged', 'Acknowledged'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed'), ('expired', 'Expired')], default='active', max_length=20)),
                ('title', models.CharField(help_text='Brief suggestion title', max_length=200)),
                ('message', models.TextField(help_text='Detailed coaching message')),
                ('reasoning', models.TextField(blank=True, help_text='AI explanation of why this suggestion was made')),
                ('recommended_actions', models.JSONField(blank=True, default=list, help_text='List of recommended action steps')),
                ('expected_impact', models.CharField(blank=True, help_text='Expected impact if actions are taken', max_length=500)),
                ('metrics_snapshot', models.JSONField(blank=True, default=dict, help_text='Snapshot of relevant metrics when suggestion was generated')),
                ('confidence_score', models.DecimalField(decimal_places=2, default=Decimal('0.75'), help_text='AI confidence in this suggestion (0-1)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('ai_model_used', models.CharField(default='rule-based', help_text='AI model/system that generated suggestion', max_length=50)),
                ('generation_method', models.CharField(choices=[('rule', 'Rule-Based'), ('ai', 'AI-Generated'), ('hybrid', 'Hybrid (Rule + AI)')], default='rule', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this suggestion becomes irrelevant', null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('was_helpful', models.BooleanField(blank=True, help_text='User feedback on helpfulness', null=True)),
                ('action_taken', models.CharField(blank=True, choices=[('accepted', 'Accepted and Applied'), ('partially', 'Partially Applied'), ('modified', 'Modified Before Applying'), ('ignored', 'Ignored'), ('not_applicable', 'Not Applicable')], max_length=20, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_suggestions', to=settings.AUTH_USER_MODEL)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coaching_suggestions', to='kanban.board')),
                ('task', models.ForeignKey(blank=True, help_text='Specific task this suggestion relates to (if any)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coaching_suggestions', to='kanban.task')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CoachingFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('was_helpful', models.BooleanField(help_text='Was this suggestion helpful?')),
                ('relevance_score', models.IntegerField(help_text='How relevant was this suggestion? (1-5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('feedback_text', models.TextField(blank=True, help_text='Detailed feedback from user')),
                ('action_taken', models.CharField(choices=[('accepted', 'Accepted and Applied'), ('partially', 'Partially Applied'), ('modified', 'Modified Before Applying'), ('ignored', 'Ignored'), ('not_applicable', 'Not Applicable')], max_length=20)),
                ('outcome_description', models.TextField(blank=True, help_text='What happened after applying (or not) the suggestion?')),
                ('improved_situation', models.BooleanField(blank=True, help_text='Did the situation improve?', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coaching_feedback', to=settings.AUTH_USER_MODEL)),
                ('suggestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_entries', to='kanban.coachingsuggestion')),
            ],
            options={
                'verbose_name': 'Coaching Feedback',
                'verbose_name_plural': 'Coaching Feedback',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PMMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('suggestions_received', models.IntegerField(default=0, help_text='Number of suggestions received')),
                ('suggestions_acted_on', models.IntegerField(default=0, help_text='Number of suggestions acted on')),
                ('avg_response_time_hours', models.DecimalField(decimal_places=2, default=0, help_text='Average time to respond to suggestions (hours)', max_digits=10)),
                ('velocity_trend', models.CharField(choices=[('improving', 'Improving'), ('stable', 'Stable'), ('declining', 'Declining')], default='stable', max_length=20)),
                ('risk_mitigation_success_rate', models.DecimalField(decimal_places=2, default=0, help_text='Percentage of risks successfully mitigated', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('deadline_hit_rate', models.DecimalField(decimal_places=2, default=0, help_text='Percentage of deadlines met', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('team_satisfaction_score', models.DecimalField(blank=True, decimal_places=1, help_text='Team satisfaction score (0-5)', max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('improvement_areas', models.JSONField(blank=True, default=list, help_text='Areas where PM is improving')),
                ('struggle_areas', models.JSONField(blank=True, default=list, help_text='Areas where PM needs more support')),
                ('coaching_effectiveness_score', models.DecimalField(decimal_places=2, default=0, help_text='How effective coaching has been (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('calculated_by', models.CharField(default='system', help_text='How metrics were calculated', max_length=50)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pm_metrics', to='kanban.board')),
                ('pm_user', models.ForeignKey(help_text='Project manager being tracked', on_delete=django.db.models.deletion.CASCADE, related_name='pm_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PM Metrics',
                'verbose_name_plural': 'PM Metrics',
                'ordering': ['-period_end'],
            },
        ),
        migrations.AddIndex(
            model_name='coachingsuggestion',
            index=models.Index(fields=['board', 'status', '-created_at'], name='kanban_coac_board_i_ee73e7_idx'),
        ),
        migrations.AddIndex(
            model_name='coachingsuggestion',
            index=models.Index(fields=['suggestion_type', 'severity'], name='kanban_coac_suggest_2d7af4_idx'),
        ),
        migrations.AddIndex(
            model_name='coachingsuggestion',
            index=models.Index(fields=['status', '-created_at'], name='kanban_coac_status_c2e3f4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pmmetrics',
            unique_together={('board', 'pm_user', 'period_start', 'period_end')},
        ),
    ]
