# Generated by Django 5.2.3 on 2025-12-08 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_completed_wizard_and_more'),
        ('kanban', '0044_coachinginsight_coachingsuggestion_coachingfeedback_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceLevelingSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_score', models.FloatField(help_text='AI confidence (0-100)')),
                ('time_savings_hours', models.FloatField(help_text='Expected time savings in hours')),
                ('time_savings_percentage', models.FloatField(help_text='Percentage improvement')),
                ('skill_match_score', models.FloatField(help_text='How well skills match (0-100)')),
                ('workload_impact', models.CharField(choices=[('reduces_bottleneck', 'Reduces Bottleneck'), ('balances_load', 'Balances Workload'), ('better_skills', 'Better Skill Match'), ('improves_timeline', 'Improves Timeline')], max_length=50)),
                ('current_projected_date', models.DateTimeField(blank=True, null=True)),
                ('suggested_projected_date', models.DateTimeField(blank=True, null=True)),
                ('reasoning', models.TextField(help_text='Human-readable explanation')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='Suggestion expires after 48 hours')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('current_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_task_assignments', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leveling_suggestions', to='accounts.organization')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_suggestions', to=settings.AUTH_USER_MODEL)),
                ('suggested_assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_assignments', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leveling_suggestions', to='kanban.task')),
            ],
            options={
                'ordering': ['-confidence_score', '-time_savings_percentage'],
            },
        ),
        migrations.CreateModel(
            name='TaskAssignmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(choices=[('manual', 'Manual Reassignment'), ('ai_suggestion', 'AI Suggestion Accepted'), ('workload_balancing', 'Workload Balancing'), ('skill_match', 'Better Skill Match'), ('other', 'Other')], default='manual', max_length=50)),
                ('predicted_completion_hours', models.FloatField(blank=True, null=True)),
                ('predicted_due_date', models.DateTimeField(blank=True, null=True)),
                ('actual_completion_hours', models.FloatField(blank=True, null=True)),
                ('actual_completion_date', models.DateTimeField(blank=True, null=True)),
                ('prediction_accuracy', models.FloatField(blank=True, help_text='How accurate was prediction (0-100)', null=True)),
                ('was_ai_suggested', models.BooleanField(default=False)),
                ('ai_confidence_score', models.FloatField(blank=True, help_text='AI confidence in suggestion (0-100)', null=True)),
                ('ai_reasoning', models.TextField(blank=True, help_text='Why AI suggested this assignment')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_changes', to=settings.AUTH_USER_MODEL)),
                ('new_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_assignments', to=settings.AUTH_USER_MODEL)),
                ('previous_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_assignments', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_history', to='kanban.task')),
            ],
            options={
                'verbose_name_plural': 'Task Assignment Histories',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPerformanceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_tasks_completed', models.IntegerField(default=0)),
                ('avg_completion_time_hours', models.FloatField(default=0.0, help_text='Average hours to complete a task')),
                ('velocity_score', models.FloatField(default=1.0, help_text='Normalized velocity (tasks/week)')),
                ('on_time_completion_rate', models.FloatField(default=0.0, help_text='Percentage of tasks completed on time')),
                ('quality_score', models.FloatField(default=3.0, help_text='Average quality rating (1-5)')),
                ('skill_keywords', models.JSONField(blank=True, default=dict, help_text='Keywords extracted from completed tasks with frequency counts')),
                ('current_active_tasks', models.IntegerField(default=0)),
                ('current_workload_hours', models.FloatField(default=0.0, help_text='Estimated hours of current work')),
                ('utilization_percentage', models.FloatField(default=0.0, help_text='Current capacity utilization')),
                ('weekly_capacity_hours', models.FloatField(default=40.0, help_text='Available hours per week')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('last_task_completed', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_profiles', to='accounts.organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performance_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-velocity_score'],
                'unique_together': {('user', 'organization')},
            },
        ),
    ]
