# Generated by Django 5.2.3 on 2025-12-08 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0045_resourcelevelingsuggestion_taskassignmenthistory_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectstakeholder',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='projectstakeholder',
            name='board',
        ),
        migrations.RemoveField(
            model_name='projectstakeholder',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='stakeholderengagementrecord',
            name='stakeholder',
        ),
        migrations.RemoveField(
            model_name='stakeholdertaskinvolvement',
            name='stakeholder',
        ),
        migrations.RemoveField(
            model_name='projectstakeholdertag',
            name='stakeholder',
        ),
        migrations.AlterUniqueTogether(
            name='projectstakeholdertag',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='projectstakeholdertag',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='stakeholderengagementrecord',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='stakeholderengagementrecord',
            name='task',
        ),
        migrations.AlterUniqueTogether(
            name='stakeholdertag',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='stakeholdertag',
            name='board',
        ),
        migrations.RemoveField(
            model_name='stakeholdertag',
            name='created_by',
        ),
        migrations.AlterUniqueTogether(
            name='stakeholdertaskinvolvement',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='stakeholdertaskinvolvement',
            name='task',
        ),
        migrations.DeleteModel(
            name='EngagementMetrics',
        ),
        migrations.DeleteModel(
            name='ProjectStakeholder',
        ),
        migrations.DeleteModel(
            name='ProjectStakeholderTag',
        ),
        migrations.DeleteModel(
            name='StakeholderEngagementRecord',
        ),
        migrations.DeleteModel(
            name='StakeholderTag',
        ),
        migrations.DeleteModel(
            name='StakeholderTaskInvolvement',
        ),
    ]
