# Generated by Django 5.2.3 on 2025-12-09 06:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0045_resourcelevelingsuggestion_taskassignmenthistory_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConflictDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conflict_type', models.CharField(choices=[('resource', 'Resource Conflict'), ('schedule', 'Schedule Conflict'), ('dependency', 'Dependency Conflict')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved'), ('ignored', 'Ignored'), ('auto_resolved', 'Auto-Resolved')], default='active', max_length=20)),
                ('title', models.CharField(help_text='Short description of the conflict', max_length=255)),
                ('description', models.TextField(help_text='Detailed explanation of the conflict')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('conflict_data', models.JSONField(default=dict, help_text='Detailed conflict information (e.g., overlapping time ranges, specific dependency chains)')),
                ('ai_confidence_score', models.IntegerField(default=80, help_text='AI confidence in conflict detection (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('suggested_resolutions', models.JSONField(default=list, help_text='AI-generated resolution suggestions with confidence scores')),
                ('resolution_feedback', models.TextField(blank=True, help_text='User feedback on the resolution', null=True)),
                ('resolution_effectiveness', models.IntegerField(blank=True, help_text='User rating of resolution effectiveness (1-5 stars)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('detection_run_id', models.CharField(blank=True, help_text='Unique ID for the detection batch run', max_length=100, null=True)),
                ('auto_detection', models.BooleanField(default=True, help_text='Was this detected automatically or manually reported?')),
                ('affected_users', models.ManyToManyField(help_text='Users affected by this conflict', related_name='affected_conflicts', to=settings.AUTH_USER_MODEL)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='kanban.board')),
                ('tasks', models.ManyToManyField(help_text='Tasks involved in this conflict', related_name='conflicts', to='kanban.task')),
            ],
            options={
                'ordering': ['-detected_at', '-severity'],
            },
        ),
        migrations.CreateModel(
            name='ConflictResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution_type', models.CharField(choices=[('reassign', 'Reassign Task'), ('reschedule', 'Reschedule Task'), ('adjust_dates', 'Adjust Dates'), ('remove_dependency', 'Remove Dependency'), ('modify_dependency', 'Modify Dependency'), ('split_task', 'Split Task'), ('reduce_scope', 'Reduce Scope'), ('add_resources', 'Add Resources'), ('custom', 'Custom Resolution')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('action_steps', models.JSONField(default=list, help_text='Specific steps to implement this resolution')),
                ('estimated_impact', models.CharField(blank=True, help_text='Expected impact of this resolution', max_length=255)),
                ('ai_confidence', models.IntegerField(default=50, help_text='AI confidence in this resolution (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('ai_reasoning', models.TextField(blank=True, help_text='AI explanation for why this resolution was suggested')),
                ('auto_applicable', models.BooleanField(default=False, help_text='Can this resolution be applied automatically?')),
                ('implementation_data', models.JSONField(default=dict, help_text='Data needed to auto-apply this resolution')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('times_suggested', models.IntegerField(default=1)),
                ('times_accepted', models.IntegerField(default=0)),
                ('avg_effectiveness_rating', models.FloatField(blank=True, help_text='Average user rating when this type was chosen', null=True)),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_resolutions', to=settings.AUTH_USER_MODEL)),
                ('conflict', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolutions', to='kanban.conflictdetection')),
            ],
            options={
                'ordering': ['-ai_confidence', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='conflictdetection',
            name='chosen_resolution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_conflicts', to='kanban.conflictresolution'),
        ),
        migrations.CreateModel(
            name='ResolutionPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conflict_type', models.CharField(choices=[('resource', 'Resource Conflict'), ('schedule', 'Schedule Conflict'), ('dependency', 'Dependency Conflict')], max_length=20)),
                ('resolution_type', models.CharField(choices=[('reassign', 'Reassign Task'), ('reschedule', 'Reschedule Task'), ('adjust_dates', 'Adjust Dates'), ('remove_dependency', 'Remove Dependency'), ('modify_dependency', 'Modify Dependency'), ('split_task', 'Split Task'), ('reduce_scope', 'Reduce Scope'), ('add_resources', 'Add Resources'), ('custom', 'Custom Resolution')], max_length=30)),
                ('pattern_context', models.JSONField(default=dict, help_text='Context conditions when this pattern applies (e.g., team size, project type)')),
                ('times_used', models.IntegerField(default=0)),
                ('times_successful', models.IntegerField(default=0)),
                ('success_rate', models.FloatField(default=0.0, help_text='Ratio of successful resolutions (0.0 - 1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('avg_effectiveness_rating', models.FloatField(default=0.0, help_text='Average user effectiveness rating for this pattern')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('confidence_boost', models.FloatField(default=0.0, help_text='Confidence adjustment for AI suggestions based on learning (-50 to +50)', validators=[django.core.validators.MinValueValidator(-50.0), django.core.validators.MaxValueValidator(50.0)])),
                ('board', models.ForeignKey(blank=True, help_text='Board-specific pattern (null = global pattern)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resolution_patterns', to='kanban.board')),
            ],
            options={
                'ordering': ['-success_rate', '-times_used'],
            },
        ),
        migrations.CreateModel(
            name='ConflictNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('notification_type', models.CharField(choices=[('in_app', 'In-App Notification'), ('email', 'Email'), ('both', 'Both')], default='in_app', max_length=20)),
                ('conflict', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='kanban.conflictdetection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflict_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['user', '-sent_at'], name='kanban_conf_user_id_6ade6d_idx'), models.Index(fields=['conflict', 'acknowledged'], name='kanban_conf_conflic_1de2f8_idx')],
                'unique_together': {('conflict', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='conflictresolution',
            index=models.Index(fields=['conflict', 'resolution_type'], name='kanban_conf_conflic_2d4714_idx'),
        ),
        migrations.AddIndex(
            model_name='conflictresolution',
            index=models.Index(fields=['-ai_confidence'], name='kanban_conf_ai_conf_4396d1_idx'),
        ),
        migrations.AddIndex(
            model_name='conflictdetection',
            index=models.Index(fields=['status', 'conflict_type'], name='kanban_conf_status_4fbffd_idx'),
        ),
        migrations.AddIndex(
            model_name='conflictdetection',
            index=models.Index(fields=['board', 'status'], name='kanban_conf_board_i_f5ff00_idx'),
        ),
        migrations.AddIndex(
            model_name='conflictdetection',
            index=models.Index(fields=['detected_at'], name='kanban_conf_detecte_e77a4d_idx'),
        ),
        migrations.AddIndex(
            model_name='resolutionpattern',
            index=models.Index(fields=['conflict_type', 'resolution_type'], name='kanban_reso_conflic_11bf97_idx'),
        ),
        migrations.AddIndex(
            model_name='resolutionpattern',
            index=models.Index(fields=['-success_rate'], name='kanban_reso_success_af3b4e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='resolutionpattern',
            unique_together={('conflict_type', 'resolution_type', 'board')},
        ),
    ]
