# Generated by Django 5.2.3 on 2025-12-15 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_completed_wizard_and_more'),
        ('kanban', '0046_conflict_detection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userperformanceprofile',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_profiles_org', to='accounts.organization'),
        ),
        migrations.AlterField(
            model_name='userperformanceprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
