# Generated by Django 5.2.3 on 2025-12-26 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_completed_wizard_and_more'),
        ('kanban', '0047_alter_userperformanceprofile_organization_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('role_created', 'Role Created'), ('role_updated', 'Role Updated'), ('role_deleted', 'Role Deleted'), ('member_added', 'Member Added'), ('member_removed', 'Member Removed'), ('member_role_changed', 'Member Role Changed'), ('permission_granted', 'Permission Granted'), ('permission_revoked', 'Permission Revoked'), ('override_added', 'Permission Override Added'), ('override_removed', 'Permission Override Removed'), ('column_permission_set', 'Column Permission Set')], db_index=True, max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('details', models.JSONField(default=dict, help_text='Additional details about the change (old/new values, etc.)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('actor', models.ForeignKey(help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permission_actions', to=settings.AUTH_USER_MODEL)),
                ('affected_user', models.ForeignKey(blank=True, help_text='User who was affected by the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permission_changes_received', to=settings.AUTH_USER_MODEL)),
                ('board', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permission_audit_logs', to='kanban.board')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permission_audit_logs', to='accounts.organization')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp', 'organization'], name='kanban_perm_timesta_c4ed41_idx'), models.Index(fields=['actor', '-timestamp'], name='kanban_perm_actor_i_a76b2b_idx'), models.Index(fields=['affected_user', '-timestamp'], name='kanban_perm_affecte_919bd2_idx')],
            },
        ),
    ]
