# Generated by Django 5.2.3 on 2025-12-29 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0048_add_permission_audit_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='created_by_session',
            field=models.CharField(blank=True, help_text='Session ID if created in demo mode (for cleanup)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='board',
            name='is_official_demo_board',
            field=models.BooleanField(default=False, help_text='Official demo boards cannot be deleted by demo users'),
        ),
        migrations.AddField(
            model_name='task',
            name='created_by_session',
            field=models.CharField(blank=True, help_text='Session ID if created in demo mode (for cleanup)', max_length=255, null=True),
        ),
    ]
