# Generated by Django 5.2.3 on 2025-12-31 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0049_board_created_by_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionauditlog',
            name='action',
            field=models.CharField(choices=[('role_created', 'Role Created'), ('role_updated', 'Role Updated'), ('role_deleted', 'Role Deleted'), ('member_added', 'Member Added'), ('member_removed', 'Member Removed'), ('member_role_changed', 'Member Role Changed'), ('permission_granted', 'Permission Granted'), ('permission_revoked', 'Permission Revoked'), ('override_added', 'Permission Override Added'), ('override_removed', 'Permission Override Removed'), ('column_permission_set', 'Column Permission Set'), ('org_member_promoted', 'Organization Member Promoted to Admin'), ('org_member_demoted', 'Organization Admin Demoted to Member'), ('org_member_removed', 'Organization Member Removed')], db_index=True, max_length=30),
        ),
    ]
