# Generated by Django 5.2.3 on 2026-01-12 04:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0050_alter_permissionauditlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='lss_classification',
            field=models.CharField(blank=True, choices=[('value_added', 'Value-Added'), ('necessary_nva', 'Necessary NVA'), ('waste', 'Waste/Eliminate')], help_text='Lean Six Sigma classification - mutually exclusive category', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='lss_classification_confidence',
            field=models.FloatField(blank=True, help_text='AI confidence score for LSS classification (0.0-1.0)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='task',
            name='lss_classification_reasoning',
            field=models.JSONField(blank=True, default=dict, help_text='AI reasoning for LSS classification'),
        ),
    ]
