# Generated by Django 5.2.3 on 2026-01-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0051_add_lss_classification_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='is_seed_demo_data',
            field=models.BooleanField(default=False, help_text='True if this is original seed demo data (not user-created). Used for 48-hour cleanup.'),
        ),
        migrations.AddField(
            model_name='task',
            name='is_seed_demo_data',
            field=models.BooleanField(default=False, help_text='True if this is original seed demo data (not user-created). Used for 48-hour cleanup.'),
        ),
    ]
