# Generated by Django 5.2.3 on 2026-01-20 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0053_mark_existing_seed_demo_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='num_phases',
            field=models.PositiveIntegerField(default=0, help_text='Number of phases for this board (0 means phases are disabled). Users set this during board creation.'),
        ),
        migrations.AddField(
            model_name='task',
            name='item_type',
            field=models.CharField(choices=[('task', 'Task'), ('milestone', 'Milestone')], default='task', help_text='Type of item: task (has duration with start/end dates) or milestone (single date marker)', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='phase',
            field=models.CharField(blank=True, help_text="Phase this task/milestone belongs to (e.g., 'Phase 1', 'Phase 2'). Set via dropdown based on board's num_phases.", max_length=50, null=True),
        ),
    ]
