# Generated by Django 5.2.3 on 2026-01-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0055_migrate_milestones_to_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='item_type',
        ),
        migrations.AlterField(
            model_name='task',
            name='phase',
            field=models.CharField(blank=True, help_text="Phase this task belongs to (e.g., 'Phase 1', 'Phase 2'). Set via dropdown based on board's num_phases.", max_length=50, null=True),
        ),
    ]
