# Generated by Django 5.2.3 on 2026-01-22 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0056_remove_milestone_feature'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Milestone',
        ),
    ]
