# Generated by Django 5.2.3 on 2026-01-27 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_organization_nullable'),
        ('kanban', '0057_delete_milestone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Organization (optional - MVP mode does not require organization)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boards', to='accounts.organization'),
        ),
    ]
