# Generated by Django 5.2.3 on 2026-01-31 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0058_organization_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='is_seed_demo_data',
            field=models.BooleanField(default=False, help_text='True if this is original seed demo data (not user-created).'),
        ),
        migrations.AlterField(
            model_name='task',
            name='is_seed_demo_data',
            field=models.BooleanField(default=False, help_text='True if this is original seed demo data (not user-created).'),
        ),
    ]
