# Generated by Django 5.2.3 on 2026-02-04 01:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0059_alter_board_is_seed_demo_data_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetrecommendation',
            name='implementation_summary',
            field=models.TextField(blank=True, default='', help_text='Summary of changes made when implementing this recommendation'),
        ),
        migrations.AddField(
            model_name='budgetrecommendation',
            name='implemented_at',
            field=models.DateTimeField(blank=True, help_text='When the recommendation was implemented', null=True),
        ),
        migrations.CreateModel(
            name='BudgetImplementationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('budget_reallocation', 'Budget Reallocation'), ('task_estimate_update', 'Task Estimate Update'), ('hourly_rate_change', 'Hourly Rate Change'), ('scope_reduction', 'Scope Reduction'), ('resource_reassignment', 'Resource Reassignment'), ('timeline_adjustment', 'Timeline Adjustment')], help_text='Type of change made', max_length=30)),
                ('field_changed', models.CharField(help_text='Name of the field that was changed', max_length=100)),
                ('old_value', models.DecimalField(blank=True, decimal_places=2, help_text='Previous value', max_digits=12, null=True)),
                ('new_value', models.DecimalField(blank=True, decimal_places=2, help_text='New value after change', max_digits=12, null=True)),
                ('change_details', models.JSONField(blank=True, help_text='Additional details about the change', null=True)),
                ('implemented_at', models.DateTimeField(auto_now_add=True)),
                ('is_rolled_back', models.BooleanField(default=False, help_text='Whether this change has been rolled back')),
                ('rolled_back_at', models.DateTimeField(blank=True, null=True)),
                ('affected_task', models.ForeignKey(blank=True, help_text='Task affected by this change (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_change_logs', to='kanban.task')),
                ('implemented_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_implementations', to=settings.AUTH_USER_MODEL)),
                ('recommendation', models.ForeignKey(help_text='Recommendation that triggered this change', on_delete=django.db.models.deletion.CASCADE, related_name='implementation_logs', to='kanban.budgetrecommendation')),
                ('rolled_back_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_rollbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Budget Implementation Log',
                'verbose_name_plural': 'Budget Implementation Logs',
                'ordering': ['-implemented_at'],
            },
        ),
    ]
