# Generated by Django 5.2.3 on 2026-02-06 10:50

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0060_add_budget_implementation_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeentry',
            name='hours_spent',
            field=models.DecimalField(decimal_places=2, help_text='Hours spent on this task (max 16 hours per entry)', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('16.00'))]),
        ),
    ]
