# Generated by Django 5.2.3 on 2026-02-14 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_organization_nullable'),
        ('kanban', '0061_time_entry_max_validator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userperformanceprofile',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='resourcelevelingsuggestion',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leveling_suggestions', to='accounts.organization'),
        ),
        migrations.AlterField(
            model_name='userperformanceprofile',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performance_profiles_org', to='accounts.organization'),
        ),
        migrations.AlterField(
            model_name='userperformanceprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performance_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
