# Generated by Django 5.2.3 on 2026-02-20 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0063_board_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='project_deadline',
            field=models.DateField(blank=True, help_text='Target completion date for the project (Time constraint). Set from the Triple Constraint dashboard.', null=True),
        ),
    ]
