# Generated by Django 5.2.3 on 2026-02-22 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0064_add_project_deadline_to_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='item_type',
            field=models.CharField(choices=[('task', 'Task'), ('milestone', 'Milestone')], default='task', help_text='Whether this item is a regular task or a milestone marker', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='milestone_status',
            field=models.CharField(blank=True, choices=[('upcoming', 'Upcoming'), ('completed', 'Completed')], help_text="Status of the milestone (only used when item_type='milestone')", max_length=20, null=True),
        ),
    ]
