# Generated by Django 5.2.3 on 2026-02-22 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0065_add_milestone_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='position_after_task',
            field=models.ForeignKey(blank=True, help_text='For milestones: which task this milestone appears after in the Gantt chart rows', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preceded_milestones', to='kanban.task'),
        ),
    ]
