# Generated by Django 5.2.3 on 2026-02-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0066_add_milestone_position_after_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='column_entered_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the task last entered its current column (used for WIP age calculation)', null=True),
        ),
    ]
