# Generated by Django 5.2.3 on 2026-02-22 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0067_add_column_entered_at_to_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardAutomation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Short description, e.g. 'Mark overdue as Urgent'", max_length=120)),
                ('trigger_type', models.CharField(choices=[('task_overdue', 'Task becomes overdue (due date passed, not done)'), ('moved_to_column', 'Task moved to a column')], max_length=30)),
                ('trigger_value', models.CharField(blank=True, help_text="For 'moved_to_column': the column name fragment to match (e.g. 'Review'). Leave blank for 'task_overdue'.", max_length=100)),
                ('action_type', models.CharField(choices=[('set_priority', 'Set priority'), ('add_label', 'Add label')], max_length=30)),
                ('action_value', models.CharField(help_text="For 'set_priority': one of low/medium/high/urgent. For 'add_label': exact label name.", max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run_count', models.IntegerField(default=0, help_text='Number of times this rule has fired')),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automations', to='kanban.board')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_automations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
