# Generated by Django 5.2.3 on 2026-02-23 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0068_add_board_automation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardautomation',
            name='action_type',
            field=models.CharField(choices=[('set_priority', 'Set priority'), ('add_label', 'Add label'), ('send_notification', 'Send notification'), ('move_to_column', 'Move task to column'), ('assign_to_user', 'Assign to a specific person'), ('set_due_date', 'Set due date (now + N days)')], max_length=30),
        ),
        migrations.AlterField(
            model_name='boardautomation',
            name='trigger_type',
            field=models.CharField(choices=[('task_overdue', 'Task becomes overdue (due date passed, not done)'), ('moved_to_column', 'Task moved to a column'), ('task_created', 'Task is created'), ('task_completed', 'Task is marked as complete / done (100%)'), ('priority_changed', 'Task priority changes to…'), ('task_assigned', 'Task is assigned to a team member'), ('due_date_approaching', 'Task due date is approaching (X days before)')], max_length=30),
        ),
    ]
