# Generated by Django 5.2.3 on 2026-02-24 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0070_add_mission_strategy_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='ai_summary',
            field=models.TextField(blank=True, help_text='AI-generated summary synthesised from all task summaries on this board.', null=True),
        ),
        migrations.AddField(
            model_name='board',
            name='ai_summary_generated_at',
            field=models.DateTimeField(blank=True, help_text='When the AI summary was last generated.', null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='ai_summary',
            field=models.TextField(blank=True, help_text='AI-generated summary synthesised from all strategy summaries.', null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='ai_summary_generated_at',
            field=models.DateTimeField(blank=True, help_text='When the AI summary was last generated.', null=True),
        ),
        migrations.AddField(
            model_name='strategy',
            name='ai_summary',
            field=models.TextField(blank=True, help_text='AI-generated summary synthesised from all board summaries under this strategy.', null=True),
        ),
        migrations.AddField(
            model_name='strategy',
            name='ai_summary_generated_at',
            field=models.DateTimeField(blank=True, help_text='When the AI summary was last generated.', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='ai_summary',
            field=models.TextField(blank=True, help_text='Persisted AI-generated executive summary for this task.', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='ai_summary_generated_at',
            field=models.DateTimeField(blank=True, help_text='When the AI task summary was last generated.', null=True),
        ),
    ]
