# Generated by Django 5.2.3 on 2026-02-26 03:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_organization_nullable'),
        ('kanban', '0071_add_ai_summary_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The high-level organizational goal (e.g., 'Increase Market Share in Asia by 15%').", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Context, motivation and success criteria for this goal.', null=True)),
                ('target_metric', models.CharField(blank=True, help_text="Measurable target (e.g., '15% market share increase', '$5M revenue').", max_length=100, null=True)),
                ('target_date', models.DateField(blank=True, help_text='Target completion / measurement date.', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('on_hold', 'On Hold')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_demo', models.BooleanField(default=False)),
                ('is_seed_demo_data', models.BooleanField(default=False)),
                ('ai_summary', models.TextField(blank=True, help_text='AI-generated summary synthesised from all linked Mission summaries.', null=True)),
                ('ai_summary_generated_at', models.DateTimeField(blank=True, help_text='When the AI summary was last generated.', null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_organization_goals', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, help_text='Owning organization (optional — matches MVP open-access model).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_goals', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Organization Goal',
                'verbose_name_plural': 'Organization Goals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='mission',
            name='organization_goal',
            field=models.ForeignKey(blank=True, help_text='The Organization Goal this Mission contributes to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions', to='kanban.organizationgoal'),
        ),
    ]
