# Generated by Django 5.2.3 on 2026-02-28 04:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0073_add_calendar_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='linked_task',
            field=models.ForeignKey(blank=True, help_text="Link to a task to give teammates context (e.g. 'busy on Auth System')", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_events', to='kanban.task'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='visibility',
            field=models.CharField(choices=[('team', "Team can see I'm busy"), ('private', 'Private (only me)')], default='team', help_text="Controls whether teammates can see you're busy on this day", max_length=10),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='event_type',
            field=models.CharField(choices=[('meeting', 'Meeting'), ('out_of_office', 'Out of Office'), ('busy_block', 'Busy Block'), ('team_event', 'Team Event')], default='meeting', max_length=20),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='participants',
            field=models.ManyToManyField(blank=True, help_text='Users invited to this event (for Meetings and Team Events only)', related_name='calendar_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
