# Generated by Django 5.2.3 on 2026-02-28 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0074_add_calendarevent_visibility_linkedtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskfile',
            name='ai_analyzed_at',
            field=models.DateTimeField(blank=True, help_text='When AI last analyzed this file', null=True),
        ),
        migrations.AddField(
            model_name='taskfile',
            name='ai_summary',
            field=models.TextField(blank=True, default='', help_text='AI-generated summary of file contents'),
        ),
        migrations.AddField(
            model_name='taskfile',
            name='ai_tasks_suggested',
            field=models.JSONField(blank=True, default=list, help_text='AI-suggested tasks extracted from file'),
        ),
    ]
