# Generated by Django 5.2.3 on 2026-03-01 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0075_ai_analysis_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingWorkspacePreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_text', models.TextField(help_text='The raw organization goal text the user entered.')),
                ('generated_data', models.JSONField(blank=True, default=dict, help_text='Full AI-generated workspace hierarchy as JSON.')),
                ('edited_data', models.JSONField(blank=True, help_text="User's edits from the review step (overrides generated_data on commit).", null=True)),
                ('status', models.CharField(choices=[('generating', 'Generating'), ('ready', 'Ready for Review'), ('committed', 'Committed'), ('failed', 'Failed')], default='generating', max_length=20)),
                ('celery_task_id', models.CharField(blank=True, default='', help_text='Celery AsyncResult ID for polling task status.', max_length=255)),
                ('error_message', models.TextField(blank=True, help_text='Error details if generation failed.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_preview', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Onboarding Workspace Preview',
                'verbose_name_plural': 'Onboarding Workspace Previews',
            },
        ),
    ]
