# Generated by Django 5.0.14 on 2026-03-02 03:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0018_improve_crontab_helptext'),
        ('kanban', '0076_add_onboarding_workspace_preview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledAutomation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('schedule_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20)),
                ('scheduled_time', models.TimeField(help_text='Time of day to run (HH:MM)')),
                ('scheduled_day', models.IntegerField(blank=True, help_text='For weekly: 0=Monday … 6=Sunday. For monthly: 1–28 (day of month). Leave null for daily.', null=True)),
                ('action', models.CharField(choices=[('send_notification', 'Send Notification'), ('set_priority', 'Set Priority')], max_length=50)),
                ('action_value', models.CharField(blank=True, help_text="For set_priority: 'urgent', 'high', 'medium', 'low'. For send_notification: custom notification message text (optional).", max_length=200)),
                ('notify_target', models.CharField(choices=[('assignee', 'Task Assignee'), ('board_members', 'All Board Members'), ('creator', 'Task Creator')], default='board_members', help_text='Who receives the notification (only used for send_notification action).', max_length=50)),
                ('task_filter', models.CharField(choices=[('all', 'All Tasks'), ('overdue', 'Overdue Tasks'), ('incomplete', 'Incomplete Tasks'), ('high_priority', 'High Priority Tasks')], default='all', max_length=50)),
                ('run_count', models.IntegerField(default=0)),
                ('failure_count', models.IntegerField(default=0)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_automations', to='kanban.board')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_scheduled_automations', to=settings.AUTH_USER_MODEL)),
                ('periodic_task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_celery_beat.periodictask')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
