# Generated by Django 5.0.14 on 2026-03-02 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0077_scheduledautomation'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='ai_summary_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Explainability metadata for the AI summary (confidence, data completeness, key drivers).'),
        ),
        migrations.AddField(
            model_name='resourcedemandforecast',
            name='forecast_explainability',
            field=models.JSONField(blank=True, default=dict, help_text='Explainability data: confidence breakdown, assumptions, calculation details.'),
        ),
        migrations.AddField(
            model_name='task',
            name='ai_summary_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Rich explainability data from the AI task summary (confidence, health, risks, etc.).'),
        ),
    ]
