# Generated by Django 5.0.14 on 2026-03-03 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_onboarding_v2_fields'),
        ('kanban', '0078_board_ai_summary_metadata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationLearningProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion_type', models.CharField(help_text='Suggestion type this profile covers', max_length=30)),
                ('total_suggestions', models.IntegerField(default=0)),
                ('total_feedback', models.IntegerField(default=0)),
                ('helpful_rate', models.DecimalField(decimal_places=4, default=0, help_text='Aggregated helpful rate across all boards (0-1)', max_digits=5)),
                ('action_rate', models.DecimalField(decimal_places=4, default=0, help_text='Aggregated action rate across all boards (0-1)', max_digits=5)),
                ('avg_confidence', models.DecimalField(decimal_places=4, default=0, help_text='Average confidence score across boards', max_digits=5)),
                ('boards_with_data', models.IntegerField(default=0, help_text='Number of boards contributing to this profile')),
                ('recommended_confidence', models.DecimalField(decimal_places=4, default=0.75, help_text='Recommended confidence for new boards without their own data', max_digits=5)),
                ('should_suppress', models.BooleanField(default=False, help_text='Whether this type should be suppressed org-wide')),
                ('severity_effectiveness', models.JSONField(blank=True, default=dict, help_text='Effectiveness rates by severity level')),
                ('last_aggregated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_profiles', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Organization Learning Profile',
                'verbose_name_plural': 'Organization Learning Profiles',
                'ordering': ['-helpful_rate', '-total_feedback'],
                'unique_together': {('organization', 'suggestion_type')},
            },
        ),
    ]
