# Generated by Django 5.0.14 on 2026-03-05 03:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0080_add_ai_experiment_result'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreMortemAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('overall_risk_level', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10)),
                ('analysis_json', models.JSONField(help_text='Full 5-scenario AI output')),
                ('board_snapshot', models.JSONField(help_text='Board data used for the analysis')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_mortems', to='kanban.board')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_mortem_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pre-Mortem Analysis',
                'verbose_name_plural': 'Pre-Mortem Analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PreMortemScenarioAcknowledgment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario_index', models.IntegerField(help_text='0-4, which of the 5 scenarios')),
                ('acknowledged_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('acknowledged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='premortem_acknowledgments', to=settings.AUTH_USER_MODEL)),
                ('pre_mortem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgments', to='kanban.premortemanalysis')),
            ],
            options={
                'verbose_name': 'Pre-Mortem Scenario Acknowledgment',
                'ordering': ['-acknowledged_at'],
                'unique_together': {('pre_mortem', 'scenario_index', 'acknowledged_by')},
            },
        ),
    ]
