# Generated by Django 5.0.14 on 2026-03-05 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0081_premortem_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='archived_at',
            field=models.DateTimeField(blank=True, help_text='When the board was archived.', null=True),
        ),
        migrations.AddField(
            model_name='board',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Whether this board has been archived/completed.'),
        ),
    ]
