# Generated by Django 5.0.14 on 2026-03-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0082_board_archived_at_board_is_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemauditlog',
            name='action_type',
            field=models.CharField(choices=[('user.login', 'User Login'), ('user.logout', 'User Logout'), ('user.login_failed', 'Login Failed'), ('user.password_changed', 'Password Changed'), ('user.session_expired', 'Session Expired'), ('user.created', 'User Created'), ('user.updated', 'User Updated'), ('user.deleted', 'User Deleted'), ('user.profile_updated', 'Profile Updated'), ('organization.created', 'Organization Created'), ('organization.updated', 'Organization Updated'), ('organization.member_added', 'Member Added to Organization'), ('organization.member_removed', 'Member Removed from Organization'), ('board.created', 'Board Created'), ('board.updated', 'Board Updated'), ('board.deleted', 'Board Deleted'), ('board.member_added', 'Board Member Added'), ('board.member_removed', 'Board Member Removed'), ('board.viewed', 'Board Viewed'), ('column.created', 'Column Created'), ('column.updated', 'Column Updated'), ('column.deleted', 'Column Deleted'), ('column.reordered', 'Column Reordered'), ('task.created', 'Task Created'), ('task.updated', 'Task Updated'), ('task.deleted', 'Task Deleted'), ('task.field_changed', 'Task Field Changed'), ('task.assigned', 'Task Assigned'), ('task.moved', 'Task Moved Between Columns'), ('task.viewed', 'Task Viewed'), ('comment.created', 'Comment Created'), ('comment.updated', 'Comment Updated'), ('comment.deleted', 'Comment Deleted'), ('label.created', 'Label Created'), ('label.updated', 'Label Updated'), ('label.deleted', 'Label Deleted'), ('label.added_to_task', 'Label Added to Task'), ('label.removed_from_task', 'Label Removed from Task'), ('file.uploaded', 'File Uploaded'), ('file.downloaded', 'File Downloaded'), ('file.deleted', 'File Deleted'), ('permission.granted', 'Permission Granted'), ('permission.revoked', 'Permission Revoked'), ('role.assigned', 'Role Assigned'), ('role.removed', 'Role Removed'), ('access.denied', 'Access Denied'), ('token.created', 'API Token Created'), ('token.revoked', 'API Token Revoked'), ('token.used', 'API Token Used'), ('webhook.created', 'Webhook Created'), ('webhook.updated', 'Webhook Updated'), ('webhook.deleted', 'Webhook Deleted'), ('webhook.triggered', 'Webhook Triggered'), ('data.exported', 'Data Exported'), ('data.imported', 'Data Imported'), ('data.bulk_operation', 'Bulk Operation Performed'), ('system.error', 'System Error'), ('system.warning', 'System Warning'), ('memory.search', 'Organizational Memory Search'), ('memory.created', 'Memory Node Created'), ('memory.feedback', 'Memory Feedback Submitted')], db_index=True, max_length=50),
        ),
    ]
