# Generated by Django 5.0.14 on 2026-03-05 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0083_alter_systemauditlog_action_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScopeAutopsyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('generating', 'Generating'), ('complete', 'Complete'), ('failed', 'Failed')], default='generating', max_length=20)),
                ('baseline_task_count', models.IntegerField(default=0)),
                ('baseline_date', models.DateTimeField(blank=True, null=True)),
                ('final_task_count', models.IntegerField(default=0)),
                ('total_scope_growth_percentage', models.FloatField(default=0.0)),
                ('total_delay_days', models.IntegerField(default=0)),
                ('total_budget_impact', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('timeline_json', models.JSONField(default=list)),
                ('pattern_analysis', models.TextField(blank=True)),
                ('ai_summary', models.TextField(blank=True)),
                ('recommendations', models.JSONField(default=list)),
                ('board_snapshot', models.JSONField(default=dict)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scope_autopsies', to='kanban.board')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScopeTimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateTimeField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('source_type', models.CharField(choices=[('task_added', 'Task Added Manually'), ('scope_alert', 'Scope Creep Alert'), ('conflict', 'Conflict Resolution'), ('meeting', 'Meeting Transcript'), ('ai_suggestion', 'AI Suggestion Accepted'), ('bulk_import', 'Bulk Task Import'), ('unknown', 'Unknown Source')], max_length=30)),
                ('source_object_type', models.CharField(blank=True, max_length=50)),
                ('source_object_id', models.IntegerField(blank=True, null=True)),
                ('tasks_added', models.IntegerField(default=0)),
                ('tasks_removed', models.IntegerField(default=0)),
                ('net_task_change', models.IntegerField(default=0)),
                ('estimated_delay_days', models.IntegerField(default=0)),
                ('estimated_budget_impact', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cumulative_task_count', models.IntegerField(default=0)),
                ('is_major_event', models.BooleanField(default=False)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scope_autopsy_events', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='kanban.scopeautopsyreport')),
            ],
            options={
                'ordering': ['event_date'],
            },
        ),
        migrations.AddIndex(
            model_name='scopeautopsyreport',
            index=models.Index(fields=['board', '-created_at'], name='kanban_scop_board_i_cc2d36_idx'),
        ),
        migrations.AddIndex(
            model_name='scopeautopsyreport',
            index=models.Index(fields=['status'], name='kanban_scop_status_2e44b8_idx'),
        ),
        migrations.AddIndex(
            model_name='scopetimelineevent',
            index=models.Index(fields=['report', 'event_date'], name='kanban_scop_report__c9e53e_idx'),
        ),
    ]
