# Generated by Django 5.0.14 on 2026-03-05 22:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0084_scope_autopsy_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatIfScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('scenario_type', models.CharField(choices=[('scope_change', 'Scope Change'), ('team_change', 'Team Change'), ('deadline_change', 'Deadline Change'), ('combined', 'Combined')], default='combined', max_length=20)),
                ('input_parameters', models.JSONField(default=dict, help_text='Slider values: tasks_added, team_size_delta, deadline_shift_days')),
                ('baseline_snapshot', models.JSONField(default=dict, help_text='Board state at the time of analysis')),
                ('impact_results', models.JSONField(default=dict, help_text='Computed before/after comparison and deltas')),
                ('ai_analysis', models.JSONField(blank=True, default=dict, help_text='Gemini AI analysis of the scenario')),
                ('is_starred', models.BooleanField(default=False)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatif_scenarios', to='kanban.board')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'What-If Scenario',
                'verbose_name_plural': 'What-If Scenarios',
                'ordering': ['-created_at'],
            },
        ),
    ]
