# Generated by Django 5.0.14 on 2026-03-15 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0085_whatif_scenario'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='task_prefix',
            field=models.CharField(blank=True, default='', help_text="Short prefix for task IDs in Gantt chart (e.g. 'PRZ'). Auto-derived from board name if left blank.", max_length=10),
        ),
    ]
