# Generated by Django 5.0.14 on 2026-03-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0086_board_task_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='wip_limit',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='Maximum number of tasks allowed in this column. Leave blank for no limit.', null=True),
        ),
    ]
