# Generated by Django 5.0.14 on 2026-03-16 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0087_add_wip_limit_to_column'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShadowBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('committed', 'Committed')], default='active', max_length=20)),
                ('branch_color', models.CharField(default='#0d6efd', help_text='Hex color code for UI color coding (e.g., #0d6efd, #198754)', max_length=7)),
                ('is_starred', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shadow_branches', to='kanban.board')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('source_scenario', models.ForeignKey(blank=True, help_text='Original What-If scenario this branch was promoted from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shadow_branches', to='kanban.whatifscenario')),
            ],
            options={
                'verbose_name': 'Shadow Branch',
                'verbose_name_plural': 'Shadow Branches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BranchSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('scope_delta', models.IntegerField(default=0, help_text='Number of tasks added/removed (+/-)')),
                ('team_delta', models.IntegerField(default=0, help_text='Number of team members added/removed (+/-)')),
                ('deadline_delta_weeks', models.IntegerField(default=0, help_text='Weeks to extend/reduce deadline (+/-)')),
                ('feasibility_score', models.IntegerField(default=0, help_text='Feasibility score 0-100')),
                ('projected_completion_date', models.DateField(blank=True, help_text='AI-predicted project completion date', null=True)),
                ('projected_budget_utilization', models.FloatField(blank=True, help_text='Projected budget utilization percentage', null=True)),
                ('conflicts_detected', models.JSONField(blank=True, default=dict, help_text='JSON array of detected conflicts from feasibility analysis')),
                ('gemini_recommendation', models.TextField(blank=True, help_text='AI recommendation text from Gemini analysis', null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='kanban.shadowbranch')),
            ],
            options={
                'verbose_name': 'Branch Snapshot',
                'verbose_name_plural': 'Branch Snapshots',
                'ordering': ['-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='BranchDivergenceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('old_score', models.IntegerField(help_text='Previous feasibility score (0-100)')),
                ('new_score', models.IntegerField(help_text='New feasibility score (0-100)')),
                ('trigger_event', models.TextField(help_text='Description of what triggered the recalculation (e.g., "Task XYZ completed")')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divergence_logs', to='kanban.shadowbranch')),
            ],
            options={
                'verbose_name': 'Branch Divergence Log',
                'verbose_name_plural': 'Branch Divergence Logs',
                'ordering': ['-logged_at'],
            },
        ),
        migrations.AddIndex(
            model_name='shadowbranch',
            index=models.Index(fields=['board', 'status'], name='kanban_shad_board_i_3acdd3_idx'),
        ),
        migrations.AddIndex(
            model_name='shadowbranch',
            index=models.Index(fields=['board', 'created_at'], name='kanban_shad_board_i_7514e1_idx'),
        ),
        migrations.AddIndex(
            model_name='branchsnapshot',
            index=models.Index(fields=['branch', '-captured_at'], name='kanban_bran_branch__2e18d1_idx'),
        ),
        migrations.AddIndex(
            model_name='branchdivergencelog',
            index=models.Index(fields=['branch', '-logged_at'], name='kanban_bran_branch__40b362_idx'),
        ),
    ]
