# Generated by Django 5.0.14 on 2026-03-17 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0089_add_branch_committed_action_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StressTestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('score_rationale', models.TextField(blank=True)),
                ('assumptions_made', models.JSONField(default=list)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stress_test_sessions', to='kanban.board')),
                ('run_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stress_test_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stress Test Session',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StressTestScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario_number', models.IntegerField()),
                ('attack_type', models.CharField(max_length=60)),
                ('title', models.CharField(max_length=120)),
                ('attack_description', models.TextField()),
                ('cascade_effect', models.TextField()),
                ('outcome', models.CharField(choices=[('FAIL', 'Critical Fail'), ('SURVIVED_BARELY', 'Survived (Barely)'), ('SURVIVED', 'Survived')], max_length=20)),
                ('severity', models.IntegerField()),
                ('tasks_blocked', models.IntegerField(default=0)),
                ('estimated_delay_weeks', models.IntegerField(blank=True, null=True)),
                ('has_recovery_path', models.BooleanField(default=False)),
                ('early_warning_sign', models.TextField(blank=True)),
                ('tags', models.JSONField(default=list)),
                ('is_addressed', models.BooleanField(default=False)),
                ('addressed_at', models.DateTimeField(blank=True, null=True)),
                ('addressed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addressed_scenarios', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='kanban.stresstestsession')),
            ],
            options={
                'verbose_name': 'Stress Test Scenario',
                'ordering': ['-severity'],
            },
        ),
        migrations.CreateModel(
            name='ImmunityScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall', models.IntegerField()),
                ('schedule', models.IntegerField()),
                ('budget', models.IntegerField()),
                ('team', models.IntegerField()),
                ('dependencies', models.IntegerField()),
                ('scope_stability', models.IntegerField()),
                ('schedule_rationale', models.TextField(blank=True)),
                ('budget_rationale', models.TextField(blank=True)),
                ('team_rationale', models.TextField(blank=True)),
                ('dependencies_rationale', models.TextField(blank=True)),
                ('scope_stability_rationale', models.TextField(blank=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='immunity_score', to='kanban.stresstestsession')),
            ],
            options={
                'verbose_name': 'Immunity Score',
            },
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_number', models.IntegerField()),
                ('targets_scenario_number', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('effort_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=10)),
                ('effort_rationale', models.TextField(blank=True)),
                ('projected_score_improvement', models.IntegerField(default=0)),
                ('implementation_hint', models.TextField(blank=True)),
                ('is_applied', models.BooleanField(default=False)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_vaccines', to=settings.AUTH_USER_MODEL)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccines', to='kanban.board')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccines', to='kanban.stresstestsession')),
            ],
            options={
                'verbose_name': 'Vaccine',
                'ordering': ['-projected_score_improvement'],
            },
        ),
    ]
