# Generated by Django 5.0.14 on 2026-03-17 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0090_stresstestsession_stresstestscenario_immunityscore_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stresstestscenario',
            options={'ordering': ['scenario_number'], 'verbose_name': 'Stress Test Scenario'},
        ),
    ]
