# Generated by Django 5.0.14 on 2026-03-17 21:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0091_alter_stresstestscenario_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitmentProtocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('target_date', models.DateField()),
                ('initial_confidence', models.FloatField(default=0.85, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(1.0)])),
                ('current_confidence', models.FloatField(default=0.85)),
                ('confidence_halflife_days', models.IntegerField(default=14, help_text='Days for confidence to halve without positive signals')),
                ('decay_model', models.CharField(choices=[('exponential', 'Exponential'), ('linear', 'Linear'), ('stepped', 'Stepped')], default='exponential', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('at_risk', 'At Risk'), ('critical', 'Critical'), ('met', 'Met'), ('missed', 'Missed'), ('renegotiated', 'Renegotiated')], default='active', max_length=20)),
                ('baseline_snapshot', models.JSONField(default=dict, help_text='Board state when commitment was created')),
                ('last_signal_date', models.DateTimeField(blank=True, null=True)),
                ('last_decay_calculation', models.DateTimeField(auto_now_add=True)),
                ('ai_reasoning', models.TextField(blank=True)),
                ('negotiation_threshold', models.FloatField(default=0.4, help_text='Confidence % that triggers Negotiation Bot')),
                ('token_pool_per_member', models.IntegerField(default=100, help_text='Betting tokens per member per week')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commitments', to='kanban.board')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_commitments', to=settings.AUTH_USER_MODEL)),
                ('linked_tasks', models.ManyToManyField(blank=True, related_name='commitments', to='kanban.task')),
                ('stakeholders', models.ManyToManyField(blank=True, related_name='watched_commitments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Commitment Protocol',
                'verbose_name_plural': 'Commitment Protocols',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConfidenceSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_type', models.CharField(choices=[('task_completed', 'Task Completed'), ('task_added', 'Task Added (Scope)'), ('milestone_hit', 'Milestone Hit'), ('milestone_missed', 'Milestone Missed'), ('team_member_left', 'Team Member Left'), ('team_member_joined', 'Team Member Joined'), ('dependency_blocked', 'Dependency Blocked'), ('dependency_resolved', 'Dependency Resolved'), ('manual_positive', 'Manual Positive Update'), ('manual_negative', 'Manual Negative Update'), ('external_risk', 'External Risk Detected'), ('decay', 'Time Decay')], max_length=30)),
                ('signal_value', models.FloatField(help_text='Strength from -1.0 (very negative) to +1.0 (very positive)')),
                ('description', models.TextField()),
                ('confidence_before', models.FloatField()),
                ('confidence_after', models.FloatField()),
                ('ai_generated', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='kanban.commitmentprotocol')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_signals', to=settings.AUTH_USER_MODEL)),
                ('related_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commitment_signals', to='kanban.task')),
            ],
            options={
                'verbose_name': 'Confidence Signal',
                'verbose_name_plural': 'Confidence Signals',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='NegotiationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_confidence', models.FloatField()),
                ('trigger_reason', models.TextField()),
                ('ai_drafted_message', models.TextField()),
                ('option_a_description', models.TextField(blank=True, help_text='Reduce scope option')),
                ('option_a_impact', models.JSONField(default=dict)),
                ('option_b_description', models.TextField(blank=True, help_text='Extend deadline option')),
                ('option_b_impact', models.JSONField(default=dict)),
                ('option_c_description', models.TextField(blank=True, help_text='Add resources option')),
                ('option_c_impact', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent to Stakeholders'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='draft', max_length=20)),
                ('chosen_option', models.CharField(blank=True, choices=[('a', 'Option A: Reduce Scope'), ('b', 'Option B: Extend Deadline'), ('c', 'Option C: Add Resources'), ('custom', 'Custom Agreement')], max_length=10, null=True)),
                ('new_target_date', models.DateField(blank=True, null=True)),
                ('new_scope_tasks', models.IntegerField(blank=True, null=True)),
                ('stakeholder_notes', models.TextField(blank=True)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('initiated_by_ai', models.BooleanField(default=True)),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negotiations', to='kanban.commitmentprotocol')),
            ],
            options={
                'verbose_name': 'Negotiation Session',
                'verbose_name_plural': 'Negotiation Sessions',
                'ordering': ['-initiated_at'],
            },
        ),
        migrations.CreateModel(
            name='UserCredibilityScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=50.0, help_text='0-100, starts at 50')),
                ('total_bets', models.IntegerField(default=0)),
                ('correct_bets', models.IntegerField(default=0)),
                ('tokens_remaining', models.IntegerField(default=100)),
                ('tokens_reset_date', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='betting_credibility', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Credibility Score',
                'verbose_name_plural': 'User Credibility Scores',
            },
        ),
        migrations.CreateModel(
            name='CommitmentBet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokens_wagered', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('confidence_estimate', models.FloatField(help_text="Bettor's personal confidence estimate 0-1", validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(0.99)])),
                ('reasoning', models.TextField(blank=True)),
                ('is_anonymous', models.BooleanField(default=True)),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolution_correct', models.BooleanField(blank=True, null=True)),
                ('credibility_delta', models.FloatField(blank=True, help_text='Credibility score change on resolution', null=True)),
                ('bettor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commitment_bets', to=settings.AUTH_USER_MODEL)),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='kanban.commitmentprotocol')),
            ],
            options={
                'verbose_name': 'Commitment Bet',
                'verbose_name_plural': 'Commitment Bets',
                'ordering': ['-placed_at'],
                'unique_together': {('protocol', 'bettor')},
            },
        ),
    ]
