# Generated by Django 5.0.14 on 2026-03-18 04:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('kanban', '0092_commitment_protocols'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='due_date',
            field=models.DateField(blank=True, help_text='Target completion date for this mission.', null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Accountable owner of this mission.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_missions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mission',
            name='version',
            field=models.IntegerField(default=1, help_text='Current version number — incremented on each edit.'),
        ),
        migrations.AddField(
            model_name='organizationgoal',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Accountable owner of this goal (defaults to creator).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_goals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationgoal',
            name='version',
            field=models.IntegerField(default=1, help_text='Current version number — incremented on each edit.'),
        ),
        migrations.AddField(
            model_name='strategy',
            name='due_date',
            field=models.DateField(blank=True, help_text='Target completion date for this strategy.', null=True),
        ),
        migrations.AddField(
            model_name='strategy',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Accountable owner of this strategy.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_strategies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='strategy',
            name='version',
            field=models.IntegerField(default=1, help_text='Current version number — incremented on each edit.'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('paused', 'Paused'), ('completed', 'Completed'), ('archived', 'Archived')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='organizationgoal',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('paused', 'Paused'), ('completed', 'Completed'), ('archived', 'Archived')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('paused', 'Paused'), ('completed', 'Completed'), ('archived', 'Archived')], default='active', max_length=20),
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete'), ('missed', 'Missed')], default='pending', max_length=10)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='kanban.strategy')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='GoalVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('target_date', models.DateField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('change_reason', models.CharField(choices=[('minor_tweak', 'Minor tweak'), ('scope_change', 'Scope change'), ('strategic_pivot', 'Strategic pivot')], max_length=20)),
                ('change_notes', models.TextField(blank=True, default='')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='kanban.organizationgoal')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version_number'],
                'unique_together': {('goal', 'version_number')},
            },
        ),
        migrations.CreateModel(
            name='MissionVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('due_date', models.DateField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('change_reason', models.CharField(choices=[('minor_tweak', 'Minor tweak'), ('scope_change', 'Scope change'), ('strategic_pivot', 'Strategic pivot')], max_length=20)),
                ('change_notes', models.TextField(blank=True, default='')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='kanban.mission')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version_number'],
                'unique_together': {('mission', 'version_number')},
            },
        ),
        migrations.CreateModel(
            name='StrategicFollower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('followed_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategic_follows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='kanban_stra_content_0ddc76_idx')],
                'unique_together': {('content_type', 'object_id', 'user')},
            },
        ),
        migrations.CreateModel(
            name='StrategicUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('on_track', 'On track'), ('at_risk', 'At risk'), ('off_track', 'Off track'), ('blocked', 'Blocked')], max_length=20)),
                ('message', models.TextField(help_text='Structured status check-in (max 500 characters).', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategic_updates', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='kanban_stra_content_46ed9e_idx')],
            },
        ),
        migrations.CreateModel(
            name='StrategyVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('due_date', models.DateField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('change_reason', models.CharField(choices=[('minor_tweak', 'Minor tweak'), ('scope_change', 'Scope change'), ('strategic_pivot', 'Strategic pivot')], max_length=20)),
                ('change_notes', models.TextField(blank=True, default='')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='kanban.strategy')),
            ],
            options={
                'ordering': ['-version_number'],
                'unique_together': {('strategy', 'version_number')},
            },
        ),
    ]
