# Generated by Django 5.0.14 on 2026-03-18 04:43

from django.db import migrations


def set_owner_and_version(apps, schema_editor):
    """Set owner = created_by and version = 1 for all existing records."""
    OrganizationGoal = apps.get_model('kanban', 'OrganizationGoal')
    Mission = apps.get_model('kanban', 'Mission')
    Strategy = apps.get_model('kanban', 'Strategy')

    for goal in OrganizationGoal.objects.filter(owner__isnull=True):
        goal.owner = goal.created_by
        goal.version = 1
        goal.save(update_fields=['owner', 'version'])

    for mission in Mission.objects.filter(owner__isnull=True):
        mission.owner = mission.created_by
        mission.version = 1
        mission.save(update_fields=['owner', 'version'])

    for strategy in Strategy.objects.filter(owner__isnull=True):
        strategy.owner = strategy.created_by
        strategy.version = 1
        strategy.save(update_fields=['owner', 'version'])


def migrate_on_hold_to_paused(apps, schema_editor):
    """Migrate existing 'on_hold' status to 'paused'."""
    OrganizationGoal = apps.get_model('kanban', 'OrganizationGoal')
    Mission = apps.get_model('kanban', 'Mission')
    Strategy = apps.get_model('kanban', 'Strategy')

    OrganizationGoal.objects.filter(status='on_hold').update(status='paused')
    Mission.objects.filter(status='on_hold').update(status='paused')
    Strategy.objects.filter(status='on_hold').update(status='paused')


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0093_goal_redesign_phase1_fields_and_models'),
    ]

    operations = [
        migrations.RunPython(set_owner_and_version, migrations.RunPython.noop),
        migrations.RunPython(migrate_on_hold_to_paused, migrations.RunPython.noop),
    ]
