# Generated by Django 5.0.14 on 2026-03-18 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0018_improve_crontab_helptext'),
        ('kanban', '0094_goal_redesign_phase1_data_migration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('task_management', 'Task Management'), ('notifications', 'Notifications'), ('deadlines', 'Deadlines'), ('sprint', 'Sprint'), ('scheduled', 'Scheduled')], max_length=30)),
                ('trigger_type', models.CharField(max_length=30)),
                ('rule_definition', models.JSONField(help_text='JSON block tree identical to AutomationRule.rule_definition')),
                ('is_builtin', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trigger_type', models.CharField(blank=True, choices=[('task_overdue', 'Task becomes overdue'), ('moved_to_column', 'Task moved to column'), ('task_created', 'Task created'), ('task_completed', 'Task completed'), ('priority_changed', 'Task priority changed'), ('task_assigned', 'Task assigned'), ('due_date_approaching', 'Due date approaching'), ('task_completion_reached', 'Task completion reached threshold'), ('scheduled_daily', 'Scheduled — daily'), ('scheduled_weekly', 'Scheduled — weekly'), ('scheduled_monthly', 'Scheduled — monthly')], default='', max_length=30)),
                ('trigger_value', models.CharField(blank=True, default='', max_length=200)),
                ('action_type', models.CharField(blank=True, choices=[('set_priority', 'Set priority'), ('add_label', 'Add label'), ('send_notification', 'Send notification'), ('move_to_column', 'Move to column'), ('assign_to_user', 'Assign to user'), ('set_due_date', 'Set due date (now + N days)'), ('remove_label', 'Remove label'), ('set_due_date_relative', 'Set due date (relative)'), ('close_task', 'Close / complete task'), ('create_comment', 'Post a comment'), ('log_time_entry', 'Log time entry')], default='', max_length=30)),
                ('action_value', models.CharField(blank=True, default='', max_length=200)),
                ('rule_definition', models.JSONField(blank=True, help_text='JSON block tree: {id, type, block_type, config, children, else_children}', null=True)),
                ('schedule_type', models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='', max_length=20)),
                ('scheduled_time', models.TimeField(blank=True, null=True)),
                ('scheduled_day', models.IntegerField(blank=True, null=True)),
                ('notify_target', models.CharField(blank=True, default='', max_length=50)),
                ('task_filter', models.CharField(blank=True, default='all', max_length=50)),
                ('run_count', models.IntegerField(default=0)),
                ('failure_count', models.IntegerField(default=0)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_rules', to='kanban.board')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_rules_created', to=settings.AUTH_USER_MODEL)),
                ('periodic_task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_rule', to='django_celery_beat.periodictask')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AutomationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggered_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('trigger_event', models.CharField(max_length=100)),
                ('actions_summary', models.TextField(blank=True)),
                ('outcome', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed')], db_index=True, max_length=10)),
                ('error_detail', models.TextField(blank=True)),
                ('task_affected', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_logs', to='kanban.task')),
                ('rule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='kanban.automationrule')),
            ],
            options={
                'ordering': ['-triggered_at'],
            },
        ),
    ]
