# Generated by Django 5.0.14 on 2026-03-19 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('kanban', '0096_automation_engine_data_migration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('favorite_type', models.CharField(choices=[('board', 'Board'), ('goal', 'Goal'), ('mission', 'Mission'), ('wiki_page', 'Wiki Page'), ('task', 'Task'), ('retrospective', 'Retrospective'), ('chat_room', 'Chat Room'), ('conflict', 'Conflict'), ('shadow_branch', 'Shadow Branch'), ('automation', 'Automation Rule')], max_length=20)),
                ('display_name', models.CharField(help_text='Cached name for sidebar rendering without extra queries', max_length=200)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['position', '-created_at'],
                'indexes': [models.Index(fields=['user', 'position'], name='kanban_user_user_id_8dfaac_idx'), models.Index(fields=['content_type', 'object_id'], name='kanban_user_content_621129_idx')],
                'unique_together': {('user', 'content_type', 'object_id')},
            },
        ),
    ]
