# Generated by Django 5.0.14 on 2026-03-23 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0097_add_userfavorite_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='analytics_narrative',
            field=models.TextField(blank=True, help_text='Gemini-generated 2-sentence narrative explaining what board metrics mean for the linked Goal.', null=True),
        ),
        migrations.AddField(
            model_name='board',
            name='analytics_narrative_generated_at',
            field=models.DateTimeField(blank=True, help_text='When the analytics narrative was last generated.', null=True),
        ),
        migrations.AddField(
            model_name='board',
            name='analytics_narrative_metric_snapshot',
            field=models.JSONField(blank=True, help_text='Metric values at time of narrative generation — used for staleness detection.', null=True),
        ),
        migrations.AddField(
            model_name='board',
            name='project_type',
            field=models.CharField(blank=True, choices=[('product_tech', 'Product / Tech'), ('marketing_campaign', 'Marketing / Campaign'), ('operations', 'Operations')], help_text='Gemini-classified project type. Controls which analytics are promoted.', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='board',
            name='project_type_confidence',
            field=models.FloatField(blank=True, help_text='Gemini confidence score at time of classification (0.0 to 1.0).', null=True),
        ),
        migrations.AddField(
            model_name='board',
            name='project_type_confirmed',
            field=models.BooleanField(default=False, help_text='True once user has confirmed or manually set the project type.'),
        ),
        migrations.AddField(
            model_name='mission',
            name='portfolio_narrative',
            field=models.TextField(blank=True, help_text='Gemini-generated narrative summarising health of all linked boards in Mission context.', null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='portfolio_narrative_generated_at',
            field=models.DateTimeField(blank=True, help_text='When the portfolio narrative was last generated.', null=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='portfolio_narrative_metric_snapshot',
            field=models.JSONField(blank=True, help_text='Metric snapshot at time of portfolio narrative generation.', null=True),
        ),
        migrations.AddField(
            model_name='organizationgoal',
            name='portfolio_narrative',
            field=models.TextField(blank=True, help_text='Gemini-generated narrative summarising health of all linked boards in Goal context.', null=True),
        ),
        migrations.AddField(
            model_name='organizationgoal',
            name='portfolio_narrative_generated_at',
            field=models.DateTimeField(blank=True, help_text='When the portfolio narrative was last generated.', null=True),
        ),
        migrations.AddField(
            model_name='organizationgoal',
            name='portfolio_narrative_metric_snapshot',
            field=models.JSONField(blank=True, help_text='Metric snapshot at time of portfolio narrative generation.', null=True),
        ),
        migrations.AddField(
            model_name='strategy',
            name='portfolio_narrative',
            field=models.TextField(blank=True, help_text='Gemini-generated narrative summarising health of all linked boards in Strategy context.', null=True),
        ),
        migrations.AddField(
            model_name='strategy',
            name='portfolio_narrative_generated_at',
            field=models.DateTimeField(blank=True, help_text='When the portfolio narrative was last generated.', null=True),
        ),
        migrations.AddField(
            model_name='strategy',
            name='portfolio_narrative_metric_snapshot',
            field=models.JSONField(blank=True, help_text='Metric snapshot at time of portfolio narrative generation.', null=True),
        ),
        migrations.CreateModel(
            name='GoalProxyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('why_it_matters', models.TextField()),
                ('how_to_measure', models.TextField()),
                ('current_value', models.CharField(blank=True, max_length=200, null=True)),
                ('previous_value', models.CharField(blank=True, max_length=200, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('display_order', models.IntegerField(default=0)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proxy_metrics', to='kanban.organizationgoal')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
    ]
