# Generated by Django 5.0.14 on 2026-03-24 02:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('kanban', '0098_goal_aware_analytics'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoSandbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='Always created_at + 24 hours.')),
                ('warning_sent', models.BooleanField(default=False, help_text='True once the 2-hour expiry warning has been sent.')),
            ],
        ),
        migrations.CreateModel(
            name='StrategicMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('member', 'Member'), ('viewer', 'Viewer')], default='member', help_text='Owner: full control + invite. Member: contribute. Viewer: read-only.', max_length=10)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='columnpermission',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='columnpermission',
            name='column',
        ),
        migrations.RemoveField(
            model_name='columnpermission',
            name='role',
        ),
        # Remove indexes on PermissionAuditLog BEFORE removing its fields
        # (SQLite requires this to avoid FieldDoesNotExist during table rebuild)
        migrations.RemoveIndex(
            model_name='permissionauditlog',
            name='kanban_perm_timesta_c4ed41_idx',
        ),
        migrations.RemoveIndex(
            model_name='permissionauditlog',
            name='kanban_perm_actor_i_a76b2b_idx',
        ),
        migrations.RemoveIndex(
            model_name='permissionauditlog',
            name='kanban_perm_affecte_919bd2_idx',
        ),
        migrations.RemoveField(
            model_name='permissionauditlog',
            name='actor',
        ),
        migrations.RemoveField(
            model_name='permissionauditlog',
            name='affected_user',
        ),
        migrations.RemoveField(
            model_name='permissionauditlog',
            name='board',
        ),
        migrations.RemoveField(
            model_name='permissionauditlog',
            name='organization',
        ),
        migrations.AlterUniqueTogether(
            name='permissionoverride',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='permissionoverride',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='permissionoverride',
            name='membership',
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='role',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='role',
            name='organization',
        ),
        migrations.AlterField(
            model_name='boardmembership',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('member', 'Member'), ('viewer', 'Viewer')], default='member', help_text='Owner: full control. Member: create/edit tasks. Viewer: read-only.', max_length=10),
        ),
        migrations.RemoveIndex(
            model_name='boardmembership',
            name='kanban_boar_user_id_0ca23e_idx',
        ),
        migrations.RemoveField(
            model_name='boardmembership',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='boardmembership',
            name='is_active',
        ),
        migrations.AddField(
            model_name='board',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Board owner — full edit, delete, invite rights. Access flows down to all children.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_boards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='boardmembership',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_board_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='boardmembership',
            index=models.Index(fields=['user', 'role'], name='kanban_boar_user_id_d9c4af_idx'),
        ),
        migrations.AddField(
            model_name='demosandbox',
            name='saved_board',
            field=models.ForeignKey(blank=True, help_text='Board the user chose to save before sandbox deletion.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='kanban.board'),
        ),
        migrations.AddField(
            model_name='demosandbox',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='demo_sandbox', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='strategicmembership',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='strategicmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategic_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ColumnPermission',
        ),
        migrations.DeleteModel(
            name='PermissionAuditLog',
        ),
        migrations.DeleteModel(
            name='PermissionOverride',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.AddIndex(
            model_name='strategicmembership',
            index=models.Index(fields=['content_type', 'object_id'], name='kanban_stra_content_24eeba_idx'),
        ),
        migrations.AddIndex(
            model_name='strategicmembership',
            index=models.Index(fields=['user', 'role'], name='kanban_stra_user_id_848407_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='strategicmembership',
            unique_together={('content_type', 'object_id', 'user')},
        ),
    ]
