# Generated by Django 5.0.14 on 2026-03-24 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0100_populate_rbac_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='members',
        ),
    ]
