# Generated by Django 5.0.14 on 2026-03-24 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0101_remove_board_members_m2m'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], db_index=True, default='pending', max_length=12)),
                ('trigger', models.CharField(choices=[('board_view', 'Board View Denied'), ('task_search', 'Task Search — Parent Board Inaccessible'), ('task_view', 'Task View Denied'), ('spectra_chat', 'Spectra Chat Query')], default='board_view', help_text='What action triggered the access denial.', max_length=20)),
                ('requested_role', models.CharField(choices=[('viewer', 'Viewer'), ('member', 'Member')], default='member', help_text='The role the requester is asking for.', max_length=10)),
                ('message', models.TextField(blank=True, default='', help_text='Optional message from the requester to the owner.')),
                ('spectra_context', models.TextField(blank=True, default='', help_text='Context Spectra captured when the denial occurred.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer_message', models.TextField(blank=True, default='', help_text='Optional message from the reviewer on approval/denial.')),
                ('board', models.ForeignKey(help_text='The board being requested.', on_delete=django.db.models.deletion.CASCADE, related_name='access_requests', to='kanban.board')),
                ('owner', models.ForeignKey(help_text='The board owner who reviews this request.', on_delete=django.db.models.deletion.CASCADE, related_name='access_requests_received', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(help_text='The user requesting access.', on_delete=django.db.models.deletion.CASCADE, related_name='access_requests_sent', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_requests_resolved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['requester', 'status'], name='kanban_acce_request_d09464_idx'), models.Index(fields=['owner', 'status'], name='kanban_acce_owner_i_4064a6_idx'), models.Index(fields=['board', 'status'], name='kanban_acce_board_i_d4ec38_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='accessrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('requester', 'board'), name='unique_pending_access_request'),
        ),
    ]
