# Generated by Django 5.0.14 on 2026-03-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0102_spectra_access_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='color',
            field=models.CharField(choices=[('green', 'Green'), ('blue', 'Blue'), ('purple', 'Purple'), ('orange', 'Orange'), ('red', 'Red'), ('yellow', 'Yellow'), ('teal', 'Teal'), ('gray', 'Gray')], default='blue', max_length=20),
        ),
    ]
