# Generated by Django 5.0.14 on 2026-03-24 16:52

from django.db import migrations


_COLUMN_COLOR_MAP = {
    'done': 'green', 'complete': 'green', 'completed': 'green', 'finished': 'green',
    'in progress': 'blue', 'working on it': 'blue', 'doing': 'blue', 'active': 'blue',
    'stuck': 'red', 'blocked': 'red',
    'not started': 'gray', 'backlog': 'gray', 'to do': 'gray', 'todo': 'gray',
    'review': 'purple', 'testing': 'purple', 'qa': 'purple',
    'ready': 'teal', 'approved': 'teal',
    'on hold': 'orange', 'waiting': 'orange', 'pending': 'orange',
    'urgent': 'red', 'critical': 'red',
}


def assign_colors(apps, schema_editor):
    Column = apps.get_model('kanban', 'Column')
    for column in Column.objects.all():
        name_lower = column.name.strip().lower()
        for pattern, color in _COLUMN_COLOR_MAP.items():
            if pattern in name_lower:
                column.color = color
                column.save(update_fields=['color'])
                break


def reverse_colors(apps, schema_editor):
    Column = apps.get_model('kanban', 'Column')
    Column.objects.all().update(color='blue')


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0103_add_column_color'),
    ]

    operations = [
        migrations.RunPython(assign_colors, reverse_colors),
    ]
