# Generated by Django 5.2.3 on 2026-03-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0104_auto_assign_column_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='demosandbox',
            name='is_browsing',
            field=models.BooleanField(default=True, help_text="True = user is in browse-only mode (drag-drop disabled, edit buttons hidden).  Flipped to False when user clicks 'Start experimenting'."),
        ),
    ]
