# Generated by Django 5.2.3 on 2026-03-27 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0105_single_tier_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='is_sandbox_copy',
            field=models.BooleanField(default=False, help_text='True if this board was created by sandbox provisioning (personal demo copy).'),
        ),
    ]
