# Generated by Django 5.2.3 on 2026-03-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0106_add_is_sandbox_copy_to_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='demosandbox',
            name='reassigned_tasks',
            field=models.JSONField(blank=True, default=dict, help_text='Maps task IDs (str) to original assignee user IDs. Used to restore assignments when user leaves demo mode.'),
        ),
    ]
