# Generated by Django 5.2.3 on 2026-03-27 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0107_add_reassigned_tasks_to_demosandbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='cloned_from',
            field=models.ForeignKey(blank=True, help_text='Template board this sandbox copy was cloned from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sandbox_clones', to='kanban.board'),
        ),
    ]
