# Generated by Django 5.2.3 on 2026-03-28 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0108_add_cloned_from_to_board'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demosandbox',
            name='is_browsing',
        ),
    ]
