# Generated by Django 5.2.3 on 2026-03-28 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0109_remove_is_browsing_from_demosandbox'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demosandbox',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='demosandbox',
            name='saved_board',
        ),
        migrations.RemoveField(
            model_name='demosandbox',
            name='warning_sent',
        ),
        migrations.AddField(
            model_name='demosandbox',
            name='last_reset_at',
            field=models.DateTimeField(blank=True, help_text='When the user last reset their demo. NULL on first provision.', null=True),
        ),
    ]
