# Generated by Django 5.2.3 on 2026-03-30 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0111_board_created_by_set_null'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_key', models.SlugField(help_text="Lookup key used in the template tag, e.g. 'shadow_board'.", max_length=80, unique=True)),
                ('feature_name', models.CharField(help_text='Display name shown in the modal title.', max_length=120)),
                ('brief_description', models.CharField(help_text='Short description shown in the popover (max 400 chars).', max_length=400)),
                ('detailed_description', models.TextField(help_text='Full HTML description shown in the modal body. Supports headings, lists, bold, etc.')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide the help badge without deleting content.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Ordering in admin list view.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Feature Guide',
                'verbose_name_plural': 'Feature Guides',
                'ordering': ['order', 'feature_name'],
            },
        ),
    ]
