# Generated by Django 5.2.3 on 2026-04-01 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0113_add_checklist_item_and_epic_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='is_imported',
            field=models.BooleanField(default=False, help_text='True if this board was created via file import (Jira, Monday.com, Trello, etc.).'),
        ),
    ]
