# Generated by Django 5.2.3 on 2026-04-02 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_org_domain_optional_and_org_invitation'),
        ('kanban', '0114_add_board_is_imported'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Display name of this workspace (e.g., 'Acme Corp Launch').", max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_demo', models.BooleanField(default=False, help_text='True for the demo/sandbox workspace. Only one per organization.')),
                ('is_active', models.BooleanField(default=True, help_text='Soft-delete flag. Inactive workspaces are hidden from the switcher.')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_workspaces', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='The organization this workspace belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='workspaces', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'Workspace',
                'verbose_name_plural': 'Workspaces',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='board',
            name='workspace',
            field=models.ForeignKey(blank=True, help_text='The workspace this board belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boards', to='kanban.workspace'),
        ),
        migrations.AddField(
            model_name='mission',
            name='workspace',
            field=models.ForeignKey(blank=True, help_text='The workspace this mission belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='kanban.workspace'),
        ),
        migrations.AddField(
            model_name='organizationgoal',
            name='workspace',
            field=models.ForeignKey(blank=True, help_text='The workspace this goal belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='kanban.workspace'),
        ),
        migrations.AddField(
            model_name='strategy',
            name='workspace',
            field=models.ForeignKey(blank=True, help_text='The workspace this strategy belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='strategies', to='kanban.workspace'),
        ),
    ]
