# Generated by Django 5.2.3 on 2026-04-02 14:18

from django.db import migrations


def populate_workspaces(apps, schema_editor):
    """
    Create Workspace objects from existing data and link them up.

    1. For each Organization that has non-demo OrganizationGoals, create one
       Workspace per OrganizationGoal (real workspaces).
    2. For each Organization that has demo data, create one demo Workspace.
    3. For orphan goals (no organization), create an org + workspace.
    4. Set workspace FK on all OrganizationGoal, Mission, Strategy, Board.
    5. Set active_workspace on all UserProfile records based on is_viewing_demo.
    """
    Organization = apps.get_model('accounts', 'Organization')
    UserProfile = apps.get_model('accounts', 'UserProfile')
    Workspace = apps.get_model('kanban', 'Workspace')
    OrganizationGoal = apps.get_model('kanban', 'OrganizationGoal')
    Mission = apps.get_model('kanban', 'Mission')
    Strategy = apps.get_model('kanban', 'Strategy')
    Board = apps.get_model('kanban', 'Board')

    # ── 1. Create one Demo Workspace per org that has demo goals ──
    demo_goals = OrganizationGoal.objects.filter(
        is_demo=True
    ).select_related('organization')

    demo_workspace_map = {}  # org_id → demo Workspace
    for goal in demo_goals:
        org = goal.organization
        if org and org.pk not in demo_workspace_map:
            ws = Workspace.objects.create(
                name=f'{org.name} (Demo)',
                organization=org,
                created_by_id=goal.created_by_id,
                is_demo=True,
            )
            demo_workspace_map[org.pk] = ws

    # ── 2. Create one Workspace per real OrganizationGoal ──
    real_goals = OrganizationGoal.objects.filter(
        is_demo=False, is_seed_demo_data=False,
    ).select_related('organization')

    goal_workspace_map = {}  # goal_id → Workspace
    for goal in real_goals:
        org = goal.organization
        if not org:
            # Orphan goal — skip (no org to attach workspace to)
            continue
        ws = Workspace.objects.create(
            name=goal.name[:200],
            organization=org,
            created_by_id=goal.created_by_id,
            is_demo=False,
        )
        goal_workspace_map[goal.pk] = ws

    # ── 3. Set workspace FK on all hierarchy objects ──
    for goal in real_goals:
        ws = goal_workspace_map.get(goal.pk)
        if not ws:
            continue
        goal.workspace = ws
        goal.save(update_fields=['workspace'])

        missions = Mission.objects.filter(organization_goal=goal)
        for m in missions:
            m.workspace = ws
            m.save(update_fields=['workspace'])

        strategies = Strategy.objects.filter(mission__organization_goal=goal)
        for s in strategies:
            s.workspace = ws
            s.save(update_fields=['workspace'])

        boards = Board.objects.filter(
            strategy__mission__organization_goal=goal,
            is_sandbox_copy=False,
            is_official_demo_board=False,
        )
        for b in boards:
            b.workspace = ws
            b.save(update_fields=['workspace'])

    # Demo goals → demo workspace
    for goal in demo_goals:
        org = goal.organization
        if not org:
            continue
        ws = demo_workspace_map.get(org.pk)
        if not ws:
            continue
        goal.workspace = ws
        goal.save(update_fields=['workspace'])

        missions = Mission.objects.filter(organization_goal=goal)
        for m in missions:
            m.workspace = ws
            m.save(update_fields=['workspace'])

        strategies = Strategy.objects.filter(mission__organization_goal=goal)
        for s in strategies:
            s.workspace = ws
            s.save(update_fields=['workspace'])

        boards = Board.objects.filter(
            strategy__mission__organization_goal=goal,
            is_official_demo_board=True,
        )
        for b in boards:
            b.workspace = ws
            b.save(update_fields=['workspace'])

    # Sandbox board copies → demo workspace of their cloned_from board's org
    sandbox_boards = Board.objects.filter(is_sandbox_copy=True).select_related('cloned_from__strategy__mission__organization_goal__organization')
    for sb in sandbox_boards:
        cloned = sb.cloned_from
        if cloned and cloned.strategy and cloned.strategy.mission and cloned.strategy.mission.organization_goal:
            org = cloned.strategy.mission.organization_goal.organization
            if org and org.pk in demo_workspace_map:
                sb.workspace = demo_workspace_map[org.pk]
                sb.save(update_fields=['workspace'])

    # ── 4. Set active_workspace on UserProfile ──
    # For users viewing demo → set to demo workspace of their org
    # For users not viewing demo → set to the first real workspace of their org
    for profile in UserProfile.objects.select_related('organization').all():
        org = profile.organization
        if not org:
            continue

        if profile.is_viewing_demo:
            if org.pk in demo_workspace_map:
                profile.active_workspace = demo_workspace_map[org.pk]
                profile.save(update_fields=['active_workspace'])
        else:
            # Find the first (most recent) real workspace for this org
            real_ws = Workspace.objects.filter(
                organization=org, is_demo=False, is_active=True,
            ).order_by('-created_at').first()
            if real_ws:
                profile.active_workspace = real_ws
                profile.save(update_fields=['active_workspace'])


def reverse_populate(apps, schema_editor):
    """Reverse: clear workspace FKs (the Workspace rows will be dropped by schema reversal)."""
    pass  # Schema migration handles dropping the FK columns


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0115_workspace_model_and_fks'),
        ('accounts', '0013_workspace_model_and_fks'),
    ]

    operations = [
        migrations.RunPython(populate_workspaces, reverse_populate),
    ]
