# Generated by Django 5.2.3 on 2026-04-04 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_workspace_model_and_fks'),
        ('kanban', '0118_populate_orgadmin_for_creators'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_preset', models.CharField(blank=True, choices=[('lean', 'Lean / Startup'), ('professional', 'Professional / Growth'), ('enterprise', 'Enterprise / Heavyweight')], help_text='If set, overrides the global preset for this board only. Cannot exceed the global preset tier.', max_length=20, null=True)),
                ('board', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='board_preset', to='kanban.board')),
            ],
        ),
        migrations.CreateModel(
            name='WorkspacePreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('global_preset', models.CharField(choices=[('lean', 'Lean / Startup'), ('professional', 'Professional / Growth'), ('enterprise', 'Enterprise / Heavyweight')], default='lean', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_preset', to='accounts.organization')),
            ],
        ),
    ]
