# Generated by Django 5.2.3 on 2026-04-04 15:20

from django.db import migrations


def populate_presets(apps, schema_editor):
    """
    For every existing Organization that doesn't yet have a WorkspacePreset,
    create one defaulting to 'enterprise' so current users keep full access.

    For every existing Board that doesn't yet have a BoardPreset, create one
    with local_preset=None (inherits global).
    """
    Organization = apps.get_model('accounts', 'Organization')
    WorkspacePreset = apps.get_model('kanban', 'WorkspacePreset')
    Board = apps.get_model('kanban', 'Board')
    BoardPreset = apps.get_model('kanban', 'BoardPreset')

    # Orgs → enterprise (preserve existing power-user experience)
    existing_org_ids = set(
        WorkspacePreset.objects.values_list('organization_id', flat=True)
    )
    orgs_to_create = []
    for org in Organization.objects.exclude(id__in=existing_org_ids):
        orgs_to_create.append(
            WorkspacePreset(organization=org, global_preset='enterprise')
        )
    if orgs_to_create:
        WorkspacePreset.objects.bulk_create(orgs_to_create)

    # Boards → inherit global (local_preset=None)
    existing_board_ids = set(
        BoardPreset.objects.values_list('board_id', flat=True)
    )
    boards_to_create = []
    for board in Board.objects.exclude(id__in=existing_board_ids):
        boards_to_create.append(
            BoardPreset(board=board, local_preset=None)
        )
    if boards_to_create:
        BoardPreset.objects.bulk_create(boards_to_create)


def reverse_presets(apps, schema_editor):
    """Remove all preset records (safe reverse)."""
    apps.get_model('kanban', 'WorkspacePreset').objects.all().delete()
    apps.get_model('kanban', 'BoardPreset').objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0119_add_workspace_and_board_preset_models'),
    ]

    operations = [
        migrations.RunPython(populate_presets, reverse_presets),
    ]
