# Generated by Django 5.2.3 on 2026-04-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0120_populate_presets_for_existing_records'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspacepreset',
            name='global_preset',
            field=models.CharField(choices=[('lean', 'Lean / Startup'), ('professional', 'Professional / Growth'), ('enterprise', 'Enterprise / Heavyweight')], default='professional', max_length=20),
        ),
    ]
