# Generated by Django 5.2.3 on 2026-04-08 02:36

from django.db import migrations


def backfill_workspace_memberships(apps, schema_editor):
    """
    Create WorkspaceMembership 'owner' records for all existing workspace creators.
    """
    Workspace = apps.get_model('kanban', 'Workspace')
    WorkspaceMembership = apps.get_model('kanban', 'WorkspaceMembership')

    created = 0
    for ws in Workspace.objects.filter(is_active=True):
        if ws.created_by_id:
            _, was_created = WorkspaceMembership.objects.get_or_create(
                workspace=ws,
                user_id=ws.created_by_id,
                defaults={'role': 'owner', 'added_by_id': ws.created_by_id},
            )
            if was_created:
                created += 1

    if created:
        print(f"\n  Backfilled {created} WorkspaceMembership records for workspace creators.")


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0122_add_workspace_membership_and_invitation'),
    ]

    operations = [
        migrations.RunPython(backfill_workspace_memberships, migrations.RunPython.noop),
    ]
