# Generated by Django 5.2.3 on 2026-04-15 16:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0123_backfill_workspace_membership_for_creators'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachingsuggestion',
            name='suggestion_type',
            field=models.CharField(choices=[('velocity_drop', 'Velocity Dropping'), ('resource_overload', 'Resource Overloaded'), ('risk_convergence', 'Multiple Risks Converging'), ('skill_opportunity', 'Skill Development Opportunity'), ('scope_creep', 'Scope Creep Detected'), ('deadline_risk', 'Deadline at Risk'), ('team_burnout', 'Team Burnout Risk'), ('quality_issue', 'Quality Issues Detected'), ('communication_gap', 'Communication Gap'), ('dependency_blocker', 'Dependency Blocking Progress'), ('best_practice', 'Best Practice Recommendation'), ('confidence_drop', 'Project Confidence Drop')], max_length=30),
        ),
        migrations.CreateModel(
            name='ProjectConfidenceScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('scope_score', models.FloatField(default=100.0, help_text='100 = no scope creep, 0 = extreme scope creep', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('budget_score', models.FloatField(default=100.0, help_text='100 = on budget, 0 = severely over budget', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('schedule_score', models.FloatField(default=100.0, help_text='100 = on schedule, 0 = far behind schedule', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('signal_adjustment', models.FloatField(default=0.0, help_text='Adjustment from recent project signals (-50 to +50)')),
                ('composite_score', models.FloatField(default=100.0, help_text='Weighted composite confidence score', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('trend', models.CharField(choices=[('improving', 'Improving'), ('stable', 'Stable'), ('declining', 'Declining')], default='stable', max_length=20)),
                ('previous_score', models.FloatField(blank=True, null=True)),
                ('computation_data', models.JSONField(blank=True, default=dict, help_text='Raw metrics snapshot used for this calculation')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confidence_scores', to='kanban.board')),
            ],
            options={
                'verbose_name': 'Project Confidence Score',
                'verbose_name_plural': 'Project Confidence Scores',
                'ordering': ['-computed_at'],
                'indexes': [models.Index(fields=['board', '-computed_at'], name='kanban_proj_board_i_dcdcdf_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProjectSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_type', models.CharField(choices=[('task_completed', 'Task Completed'), ('task_added', 'Task Added (Scope Growth)'), ('task_removed', 'Task Removed'), ('milestone_hit', 'Milestone Hit'), ('milestone_missed', 'Milestone Missed'), ('deadline_risk', 'Deadline Risk Detected'), ('team_member_joined', 'Team Member Joined'), ('team_member_left', 'Team Member Left'), ('blocker_added', 'Blocker Emerged'), ('blocker_resolved', 'Blocker Resolved'), ('scope_creep', 'Scope Creep Detected'), ('scope_approved', 'Scope Change Approved'), ('budget_overrun', 'Budget Overrun Risk'), ('budget_approved', 'Budget Increase Approved'), ('quality_issue', 'Quality Issue Detected'), ('manual_positive', 'Manual Positive Update'), ('manual_negative', 'Manual Negative Update')], max_length=30)),
                ('impact', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral')], default='neutral', max_length=10)),
                ('strength', models.FloatField(default=0.0, help_text='Signal strength from -1.0 (very negative) to +1.0 (very positive)', validators=[django.core.validators.MinValueValidator(-1.0), django.core.validators.MaxValueValidator(1.0)])),
                ('description', models.TextField()),
                ('ai_generated', models.BooleanField(default=False)),
                ('confidence_before', models.FloatField(blank=True, null=True)),
                ('confidence_after', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_signals', to='kanban.board')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_project_signals', to=settings.AUTH_USER_MODEL)),
                ('related_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_signals', to='kanban.task')),
            ],
            options={
                'verbose_name': 'Project Signal',
                'verbose_name_plural': 'Project Signals',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['board', '-timestamp'], name='kanban_proj_board_i_65f55a_idx'), models.Index(fields=['board', 'signal_type'], name='kanban_proj_board_i_79f82f_idx')],
            },
        ),
    ]
