# Generated by Django 5.2.3 on 2026-04-16 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0124_add_project_signals_and_confidence_score'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedBrief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('audience', models.CharField(max_length=30)),
                ('purpose', models.CharField(max_length=30)),
                ('mode', models.CharField(max_length=30)),
                ('audience_label', models.CharField(blank=True, default='', max_length=80)),
                ('purpose_label', models.CharField(blank=True, default='', max_length=80)),
                ('mode_label', models.CharField(blank=True, default='', max_length=80)),
                ('slides_json', models.JSONField(help_text='List of slide dicts: [{number, title, body, body_html}, ...]')),
                ('full_text', models.TextField(help_text='Plain-text version used for Copy All / Download.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_briefs', to='kanban.board')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_briefs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
