# Generated by Django 5.2.3 on 2026-04-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0125_saved_brief'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavorite',
            name='favorite_type',
            field=models.CharField(choices=[('board', 'Board'), ('goal', 'Goal'), ('mission', 'Mission'), ('strategy', 'Strategy'), ('wiki_page', 'Wiki Page'), ('task', 'Task'), ('retrospective', 'Retrospective'), ('chat_room', 'Chat Room'), ('conflict', 'Conflict'), ('shadow_branch', 'Shadow Branch'), ('automation', 'Automation Rule')], max_length=20),
        ),
    ]
