# Generated by Django 5.2.3 on 2026-05-01 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0126_alter_userfavorite_favorite_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='google_calendar_event_id',
            field=models.CharField(blank=True, help_text="Google Calendar event ID if this task has been synced to a user's calendar.", max_length=255, null=True),
        ),
    ]
