# Generated by Django 5.2.3 on 2026-05-07 14:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_googlecalendartoken'),
        ('kanban', '0127_task_google_calendar_event_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoveryIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('source', models.CharField(choices=[('customer_feedback', 'Customer Feedback'), ('internal_brainstorm', 'Internal Brainstorm'), ('market_research', 'Market Research'), ('user_feedback', 'User Feedback'), ('sales_team', 'Sales Team'), ('finance_team', 'Finance Team'), ('other', 'Other')], default='other', max_length=30)),
                ('stage', models.CharField(choices=[('new', 'New / Unscored'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='new', max_length=20)),
                ('ai_score_impact', models.PositiveSmallIntegerField(blank=True, help_text='Impact score 0–100 (higher = more valuable).', null=True)),
                ('ai_score_effort', models.PositiveSmallIntegerField(blank=True, help_text='Effort score 0–100 (higher = more effort required).', null=True)),
                ('ai_score_confidence', models.PositiveSmallIntegerField(blank=True, help_text='Confidence in the above scores, 0–100.', null=True)),
                ('ai_score_recommendation', models.CharField(blank=True, default='', help_text='Short one-line recommendation from Spectra.', max_length=500)),
                ('ai_score_reasoning', models.TextField(blank=True, default='', help_text='Full Spectra reasoning shown to the user (Explainable AI).')),
                ('ai_scored_at', models.DateTimeField(blank=True, null=True)),
                ('promoted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_demo', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discovery_ideas', to='accounts.organization')),
                ('promoted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promoted_ideas', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_ideas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Discovery Idea',
                'verbose_name_plural': 'Discovery Ideas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IdeaComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idea_comments', to=settings.AUTH_USER_MODEL)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='kanban.discoveryidea')),
            ],
            options={
                'verbose_name': 'Idea Comment',
                'verbose_name_plural': 'Idea Comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='IdeaPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promoted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('board', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promoted_ideas', to='kanban.board')),
                ('idea', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='promotion', to='kanban.discoveryidea')),
                ('promoted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idea_promotions', to=settings.AUTH_USER_MODEL)),
                ('tasks', models.ManyToManyField(blank=True, related_name='originated_from_ideas', to='kanban.task')),
            ],
            options={
                'verbose_name': 'Idea Promotion',
                'verbose_name_plural': 'Idea Promotions',
            },
        ),
    ]
