# Generated by Django 5.2.3 on 2026-05-07 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0128_discovery_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discoveryidea',
            name='stage',
            field=models.CharField(choices=[('new', 'New'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='new', max_length=20),
        ),
    ]
