# Generated by Django 5.2.3 on 2026-05-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0129_alter_discoveryidea_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='is_billable',
            field=models.BooleanField(default=True, help_text='Mark whether time is billable to a client'),
        ),
    ]
