# Generated by Django 5.2.3 on 2026-05-12 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0130_add_is_billable_to_timeentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardStatusReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_text', models.TextField()),
                ('report_html', models.TextField()),
                ('rag_status', models.CharField(choices=[('green', 'Green'), ('amber', 'Amber'), ('red', 'Red')], default='amber', max_length=10)),
                ('rag_reasoning', models.TextField(blank=True)),
                ('confidence_score', models.FloatField(default=0.5)),
                ('data_completeness', models.FloatField(default=0.5)),
                ('key_data_drivers', models.JSONField(blank=True, default=list)),
                ('provider_name', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_reports', to='kanban.board')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_status_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['board', '-created_at'], name='kanban_boar_board_i_65cc6a_idx')],
            },
        ),
    ]
