# Generated by Django 5.2.3 on 2026-05-16 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0132_taskscopetreason'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='taskscopereason',
            new_name='kanban_task_board_i_c18196_idx',
            old_name='kanban_task_board_i_reason_idx',
        ),
    ]
