# Generated by Django 5.2.3 on 2026-05-18 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0135_unified_rule_builder_data'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='automationlog',
            new_name='kanban_auto_board_i_4664e0_idx',
            old_name='kanban_autolog_board_time_idx',
        ),
        migrations.RenameIndex(
            model_name='automationlog',
            new_name='kanban_auto_rule_id_13d56a_idx',
            old_name='kanban_autolog_rule_time_idx',
        ),
        migrations.RenameIndex(
            model_name='automationrule',
            new_name='kanban_auto_board_i_db2345_idx',
            old_name='kanban_auto_board_i_trigtype_idx',
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='action_type',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='actions',
            field=models.JSONField(default=list, help_text='[{"type": "set_priority", "target": "Urgent", "message": null}, ...]'),
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='conditions',
            field=models.JSONField(default=list, help_text='[{"attribute": "priority", "operator": "is", "value": "Urgent"}, ...]'),
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='otherwise_actions',
            field=models.JSONField(default=list, help_text='Same format as actions. Empty list = no else branch.'),
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='rule_definition',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='trigger_config',
            field=models.JSONField(default=dict, help_text='Trigger-specific parameters. Examples: task_moved_to_column: {"column_name": "Review"}, due_date_approaching: {"days": 2}, scheduled_daily: {"time": "09:00"}, scheduled_weekly: {"day": "Monday", "time": "09:00"}'),
        ),
        migrations.AlterField(
            model_name='automationrule',
            name='trigger_type',
            field=models.CharField(blank=True, choices=[('task_overdue', 'Task becomes overdue'), ('task_moved_to_column', 'Task is moved to a column'), ('task_created', 'Task is created'), ('task_completed', 'Task is completed'), ('task_priority_changed', 'Task priority changes'), ('task_assigned', 'Task is assigned'), ('due_date_approaching', 'Due date is approaching'), ('task_completion_threshold', 'Completion threshold reached'), ('scheduled_daily', 'Every day at a set time'), ('scheduled_weekly', 'Every week on a set day'), ('scheduled_monthly', 'Every month on a set date')], default='', max_length=30),
        ),
    ]
