# Generated by Django 5.2.3 on 2026-05-19 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0137_alter_automationrule_trigger_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFieldDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('long_text', 'Long Text'), ('number', 'Number'), ('date', 'Date'), ('boolean', 'Boolean'), ('list', 'List')], max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('is_multi_select', models.BooleanField(default=False)),
                ('default_text', models.TextField(blank=True, default='')),
                ('default_number', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('default_date', models.DateField(blank=True, null=True)),
                ('default_boolean', models.BooleanField(blank=True, null=True)),
                ('applies_to_tasks', models.BooleanField(default=True)),
                ('applies_to_boards', models.BooleanField(default=False)),
                ('exclude_from_ai', models.BooleanField(default=False, help_text="When checked, Spectra and other AI features will not see this field's values. Use for sensitive data like client budgets or PII.")),
                ('is_active', models.BooleanField(default=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_fields_created', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='kanban.workspace')),
            ],
            options={
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CustomFieldOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200)),
                ('is_default', models.BooleanField(default=False)),
                ('position', models.PositiveIntegerField(default=0)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='kanban.customfielddefinition')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TaskCustomFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.TextField(blank=True, default='')),
                ('value_number', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('value_date', models.DateField(blank=True, null=True)),
                ('value_boolean', models.BooleanField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='kanban.customfielddefinition')),
                ('selected_options', models.ManyToManyField(blank=True, related_name='value_rows', to='kanban.customfieldoption')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_values', to='kanban.task')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_field_values_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='customfielddefinition',
            index=models.Index(fields=['workspace', 'is_active', 'position'], name='kanban_cust_workspa_754f61_idx'),
        ),
        migrations.AddConstraint(
            model_name='customfielddefinition',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('workspace', 'name'), name='uniq_active_field_name_per_workspace'),
        ),
        migrations.AddConstraint(
            model_name='customfieldoption',
            constraint=models.UniqueConstraint(fields=('field', 'value'), name='uniq_option_value_per_field'),
        ),
        migrations.AddIndex(
            model_name='taskcustomfieldvalue',
            index=models.Index(fields=['field', 'value_text'], name='kanban_task_field_i_c21e6d_idx'),
        ),
        migrations.AddIndex(
            model_name='taskcustomfieldvalue',
            index=models.Index(fields=['field', 'value_number'], name='kanban_task_field_i_26c073_idx'),
        ),
        migrations.AddIndex(
            model_name='taskcustomfieldvalue',
            index=models.Index(fields=['field', 'value_date'], name='kanban_task_field_i_7f52c1_idx'),
        ),
        migrations.AddIndex(
            model_name='taskcustomfieldvalue',
            index=models.Index(fields=['field', 'value_boolean'], name='kanban_task_field_i_b36427_idx'),
        ),
        migrations.AddConstraint(
            model_name='taskcustomfieldvalue',
            constraint=models.UniqueConstraint(fields=('task', 'field'), name='uniq_value_per_task_field'),
        ),
    ]
