# Generated by Django 5.2.3 on 2026-05-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0138_custom_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskactivity',
            name='activity_type',
            field=models.CharField(choices=[('created', 'Created'), ('moved', 'Moved'), ('assigned', 'Assigned'), ('updated', 'Updated'), ('commented', 'Commented'), ('label_added', 'Label Added'), ('label_removed', 'Label Removed'), ('custom_field', 'Custom Field Changed')], max_length=20),
        ),
    ]
