# Generated by Django 5.2.3 on 2026-05-19 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0139_alter_taskactivity_activity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scopetimelineevent',
            name='source_type',
            field=models.CharField(choices=[('task_added', 'Task Added Manually'), ('scope_alert', 'Scope Creep Alert'), ('conflict', 'Conflict Resolution'), ('meeting', 'Meeting Transcript'), ('ai_suggestion', 'AI Suggestion Accepted'), ('bulk_import', 'Bulk Task Import'), ('custom_field_change', 'Custom Field Change'), ('unknown', 'Unknown Source')], max_length=30),
        ),
    ]
