# Generated by Django 5.2.3 on 2026-05-24 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0141_add_integer_custom_field_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='shadowbranch',
            name='baseline_velocity_per_week',
            field=models.FloatField(blank=True, help_text='Team velocity (tasks/week) the branch projection was created against. Compared against the live 7-day actual velocity to produce the velocity health adjustment in feasibility recalculations.', null=True),
        ),
        migrations.AddField(
            model_name='stresstestsession',
            name='vaccines_applied_at_run',
            field=models.IntegerField(default=0, help_text='Cumulative count of board-wide applied vaccines at the moment this session was created.'),
        ),
        migrations.AlterField(
            model_name='branchsnapshot',
            name='conflicts_detected',
            field=models.JSONField(blank=True, default=list, help_text='JSON array of detected conflicts from feasibility analysis'),
        ),
        migrations.AlterField(
            model_name='branchsnapshot',
            name='feasibility_score',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Feasibility score 0-100 (2dp precision retains micro-nudges)', max_digits=6),
        ),
    ]
