# Generated by Django 5.2.3 on 2026-05-25 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0143_backfill_shadow_and_stresstest_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchdivergencelog',
            name='new_score',
            field=models.DecimalField(decimal_places=2, help_text='New feasibility score (0-100, 2dp precision)', max_digits=6),
        ),
        migrations.AlterField(
            model_name='branchdivergencelog',
            name='old_score',
            field=models.DecimalField(decimal_places=2, help_text='Previous feasibility score (0-100, 2dp precision)', max_digits=6),
        ),
    ]
