# Generated by Django 5.2.3 on 2026-05-29 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0144_promote_divergence_log_scores_to_decimal'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchsnapshot',
            name='trigger_event',
            field=models.CharField(blank=True, default='', help_text='Human-readable event that triggered this snapshot', max_length=255),
        ),
    ]
