# Generated by Django 5.2.3 on 2026-05-30 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0145_branchsnapshot_trigger_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfielddefinition',
            name='applies_to_epics',
            field=models.BooleanField(default=True, help_text="When unchecked, this field is hidden on Epics. Use for task-level metadata (e.g. Story Points, Sprint) that doesn't apply to an Epic."),
        ),
    ]
