# Generated by Django 5.2.3 on 2026-06-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0146_customfielddefinition_applies_to_epics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationrule',
            name='trigger_type',
            field=models.CharField(blank=True, choices=[('task_created', 'Task is created'), ('task_completed', 'Task is completed'), ('task_assigned', 'Task is assigned'), ('task_unassigned', 'Task is unassigned'), ('task_moved_to_column', 'Task is moved to a column'), ('task_status_changed', 'Task status (column) changed'), ('task_priority_changed', 'Task priority changes'), ('task_progress_changed', 'Task progress changed'), ('task_description_updated', 'Task description updated'), ('task_due_date_changed', 'Task due date changed'), ('task_label_added', 'Task label added'), ('task_overdue', 'Task becomes overdue'), ('task_idle', 'Task is idle (no updates for N days)'), ('task_start_date_reached', 'Task start date reached'), ('task_completion_threshold', 'Completion threshold reached'), ('due_date_approaching', 'Due date is approaching'), ('risk_level_changed', 'Risk level changed'), ('risk_level_critical', 'Risk level becomes critical'), ('predicted_late', 'Predicted to miss due date'), ('schedule_status_changed', 'Schedule status changed (late/at-risk/on-track)'), ('complexity_increased', 'Complexity increased'), ('subtask_completed', 'A subtask completed'), ('all_subtasks_completed', 'All subtasks completed'), ('dependency_completed', 'A blocking dependency completed'), ('dependency_overdue', 'A blocking dependency became overdue'), ('checklist_completed', 'Checklist fully completed'), ('checklist_item_added', 'Checklist item added'), ('milestone_reached', 'Milestone reached'), ('parent_status_changed', 'Parent task status changed'), ('coach_suggestion_created', 'AI Coach suggestion created'), ('conflict_detected', 'Conflict detected'), ('discovery_idea_scored', 'Discovery idea AI-scored'), ('discovery_idea_submitted', 'Discovery idea submitted'), ('comment_added', 'Comment added to a task'), ('mention_received', 'Assignee was @-mentioned'), ('attachment_added', 'Attachment added to a task'), ('scheduled_daily', 'Every day at a set time'), ('scheduled_weekly', 'Every week on a set day'), ('scheduled_monthly', 'Every month on a set date')], default='', max_length=30),
        ),
    ]
