# Generated by Django 5.2.3 on 2026-06-05 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0147_alter_automationrule_trigger_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationlog',
            name='dedupe_key',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddConstraint(
            model_name='automationlog',
            constraint=models.UniqueConstraint(condition=models.Q(('dedupe_key__isnull', False)), fields=('dedupe_key',), name='uniq_automationlog_dedupe_key'),
        ),
    ]
