# Generated by Django 5.2.3 on 2026-06-17 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0148_automationlog_dedupe_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automationrule',
            name='trigger_type',
            field=models.CharField(blank=True, choices=[('task_created', 'Task is created'), ('task_completed', 'Task is completed'), ('task_assigned', 'Task is assigned'), ('task_moved_to_column', 'Task is moved to a column'), ('task_priority_changed', 'Task priority changes'), ('task_due_date_changed', 'Task due date changed'), ('task_completion_threshold', 'Completion threshold reached'), ('task_overdue', 'Task becomes overdue'), ('due_date_approaching', 'Due date is approaching'), ('task_idle', 'Task is idle (no updates for N days)'), ('scheduled_daily', 'Every day at a set time'), ('scheduled_weekly', 'Every week on a set day')], default='', max_length=30),
        ),
    ]
