# Generated by Django 5.2.3 on 2026-06-19 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0149_alter_automationrule_trigger_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='discoveryidea',
            name='sandbox_owner',
            field=models.ForeignKey(blank=True, help_text='Owning demo user for sandbox-isolated copies; None for template/real ideas.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sandbox_discovery_ideas', to=settings.AUTH_USER_MODEL),
        ),
    ]
