# Generated by Django 5.2.3 on 2026-06-23 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0151_clean_legacy_demo_discovery_ideas'),
    ]

    operations = [
        migrations.AddField(
            model_name='discoveryidea',
            name='workspace',
            field=models.ForeignKey(blank=True, help_text='Workspace this idea belongs to (scopes visibility).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discovery_ideas', to='kanban.workspace'),
        ),
    ]
