# Generated by Django 5.2.3 on 2026-06-24 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_googlecalendartoken_sync_status'),
        ('kanban', '0154_workspacepreset_per_workspace'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationlearningprofile',
            options={'ordering': ['-helpful_rate', '-total_feedback'], 'verbose_name': 'Workspace Learning Profile', 'verbose_name_plural': 'Workspace Learning Profiles'},
        ),
        migrations.AlterUniqueTogether(
            name='aiexperimentresult',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='organizationlearningprofile',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='aiexperimentresult',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiment_results', to='kanban.workspace'),
        ),
        migrations.AddField(
            model_name='organizationlearningprofile',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learning_profiles', to='kanban.workspace'),
        ),
        migrations.AddField(
            model_name='resourcelevelingsuggestion',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leveling_suggestions', to='kanban.workspace'),
        ),
        migrations.AddField(
            model_name='userperformanceprofile',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performance_profiles', to='kanban.workspace'),
        ),
        migrations.AlterField(
            model_name='aiexperimentresult',
            name='board',
            field=models.ForeignKey(blank=True, help_text='Board scope (null = workspace-wide)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiment_results', to='kanban.board'),
        ),
        migrations.AlterField(
            model_name='organizationlearningprofile',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learning_profiles', to='accounts.organization'),
        ),
        migrations.AlterUniqueTogether(
            name='aiexperimentresult',
            unique_together={('board', 'workspace', 'suggestion_type', 'generation_method', 'period_start')},
        ),
        migrations.AlterUniqueTogether(
            name='organizationlearningprofile',
            unique_together={('workspace', 'suggestion_type')},
        ),
    ]
