# Generated by Django 5.2.3 on 2026-07-02 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0157_velocity_snapshot_dedupe_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='column_type',
            field=models.CharField(blank=True, choices=[('', 'Auto (detect from name)'), ('todo', 'To Do'), ('in_progress', 'In Progress'), ('review', 'Review'), ('done', 'Done'), ('blocked', 'Blocked'), ('other', 'Other')], default='', help_text='Semantic type of this column. Leave on Auto to detect from the name.', max_length=20),
        ),
    ]
