# Generated by Django 5.2.3 on 2026-07-02 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0158_column_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='demosandbox',
            name='last_accessed_at',
            field=models.DateTimeField(blank=True, help_text='When the user last entered demo mode / (re)provisioned. Used by the stale-sandbox garbage collector to reclaim storage for abandoned demos.', null=True),
        ),
    ]
