# Generated by Django 5.2.3 on 2026-07-05 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0159_demosandbox_last_accessed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Milestone',
        ),
    ]
