# Generated by Django 5.2.3 on 2026-07-10 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0160_delete_strategy_milestone_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='aging_configured',
        ),
        migrations.DeleteModel(
            name='AgingOnboardingDismissal',
        ),
    ]
