# Generated by Django 5.2.3 on 2026-07-12 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0161_remove_board_aging_configured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='is_demo',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
