# Generated by Django 5.2.3 on 2026-07-12 01:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _copy_legacy_participants(apps, schema_editor):
    """Preserve rows from the old implicit M2M join table.

    Switching ``participants`` to a custom ``through`` model creates a new
    explicit table but does not migrate data out of the old auto-created
    join table (Django only knows how to manage the new one going forward).
    Existing participants were added under the old semantics — where being
    listed meant already attending, not merely invited — so they're copied
    over as ACCEPTED rather than the new default of PENDING; only invites
    created after this migration go through a real accept/decline step.
    """
    if schema_editor.connection.alias != 'default':
        return
    with schema_editor.connection.cursor() as cursor:
        tables = schema_editor.connection.introspection.table_names(cursor)
        if 'kanban_calendarevent_participants' not in tables:
            return  # fresh DB — nothing to migrate
        cursor.execute(
            'SELECT calendarevent_id, user_id FROM kanban_calendarevent_participants'
        )
        rows = cursor.fetchall()

    CalendarEventParticipant = apps.get_model('kanban', 'CalendarEventParticipant')
    CalendarEventParticipant.objects.bulk_create(
        [
            CalendarEventParticipant(event_id=event_id, user_id=user_id, status='accepted')
            for event_id, user_id in rows
        ],
        ignore_conflicts=True,
    )


def _noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0162_calendarevent_is_demo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEventParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=10)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_links', to='kanban.calendarevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_event_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('event', 'user')},
            },
        ),
        migrations.RunPython(_copy_legacy_participants, _noop_reverse),
        # AlterField can't add through= to an M2M in-place ("you cannot alter
        # to or from M2M fields, or add or remove through= on M2M fields") —
        # the old implicit-join field must be removed and replaced instead.
        # The RunPython step above already preserved its data.
        migrations.RemoveField(
            model_name='calendarevent',
            name='participants',
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='participants',
            field=models.ManyToManyField(blank=True, help_text='Users invited to this event (for Meetings and Team Events only)', related_name='calendar_events', through='kanban.CalendarEventParticipant', to=settings.AUTH_USER_MODEL),
        ),
    ]
