# Generated by Django 5.2.3 on 2026-07-12 05:13

from django.db import migrations, models


def forwards_mark_team_events_public(apps, schema_editor):
    """team_event rows predate the 'public' visibility value and are all
    stored with visibility='team'. Sanitization now keys off visibility
    instead of event_type, so without this backfill every existing
    team_event would suddenly render as a redacted "busy" block."""
    CalendarEvent = apps.get_model('kanban', 'CalendarEvent')
    CalendarEvent.objects.filter(event_type='team_event').update(visibility='public')


def backwards_restore_team_visibility(apps, schema_editor):
    CalendarEvent = apps.get_model('kanban', 'CalendarEvent')
    CalendarEvent.objects.filter(event_type='team_event', visibility='public').update(visibility='team')


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0163_calendarevent_participant_rsvp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='visibility',
            field=models.CharField(choices=[('team', "Team can see I'm busy"), ('public', 'Public (visible to entire board)'), ('private', 'Private (only me)')], default='team', help_text="Controls whether teammates can see you're busy on this day", max_length=10),
        ),
        migrations.RunPython(forwards_mark_team_events_public, backwards_restore_team_visibility),
    ]
