# Generated by Django 5.2.3 on 2026-07-13 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0164_calendarevent_public_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='cloned_from',
            field=models.ForeignKey(blank=True, help_text='Template-board event this sandbox clone was cloned from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sandbox_clones', to='kanban.calendarevent'),
        ),
    ]
