# Generated by Django 5.2.3 on 2026-07-18 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0165_calendarevent_cloned_from'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customfielddefinition',
            name='uniq_active_field_name_per_workspace',
        ),
        migrations.AddField(
            model_name='customfielddefinition',
            name='sandbox_owner',
            field=models.ForeignKey(blank=True, help_text='Demo-only: the sandbox user this cloned field belongs to. NULL on real-workspace fields and on shared demo templates.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sandbox_custom_fields', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='customfielddefinition',
            index=models.Index(fields=['sandbox_owner', 'is_active'], name='kanban_cust_sandbox_c5dda7_idx'),
        ),
        migrations.AddConstraint(
            model_name='customfielddefinition',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('sandbox_owner__isnull', True)), fields=('workspace', 'name'), name='uniq_active_field_name_per_workspace'),
        ),
        migrations.AddConstraint(
            model_name='customfielddefinition',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('sandbox_owner__isnull', False)), fields=('workspace', 'sandbox_owner', 'name'), name='uniq_active_field_name_per_sandbox_owner'),
        ),
    ]
