# Generated by Django 5.2.3 on 2026-07-23 01:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0166_customfielddefinition_sandbox_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='story_points',
            field=models.IntegerField(choices=[(0, '—'), (1, '1'), (2, '2'), (3, '3'), (5, '5'), (8, '8'), (13, '13'), (21, '21')], default=0, help_text='Relative effort estimate on the Fibonacci scale. 0 = unestimated.'),
        ),
        migrations.AlterField(
            model_name='task',
            name='complexity_score',
            field=models.IntegerField(default=5, help_text='Task risk/complexity score (1-10). Effort estimation lives in story_points.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
