# Generated by Django 5.2.3 on 2025-12-29 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_completed_wizard_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_demo',
            field=models.BooleanField(default=False, help_text='Whether this is a demo organization (for demo mode)'),
        ),
    ]
