# Generated by Django 5.2.3 on 2026-03-01 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_organization_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_viewing_demo',
            field=models.BooleanField(default=False, help_text='Whether user is currently viewing the demo workspace'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='onboarding_goal_text',
            field=models.TextField(blank=True, help_text='Raw organization goal text entered during onboarding', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='onboarding_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('demo_exploring', 'Exploring Demo'), ('goal_submitted', 'Goal Submitted'), ('workspace_generated', 'Workspace Generated'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='completed', help_text='Current position in the v2 onboarding flow', max_length=25),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='onboarding_version',
            field=models.IntegerField(default=1, help_text='1 = legacy (old welcome modal), 2 = new AI onboarding flow'),
        ),
    ]
