# Generated by Django 5.0.14 on 2026-03-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_onboarding_v2_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='timezone',
            field=models.CharField(default='Asia/Kolkata', help_text="User's preferred timezone for displaying dates and times", max_length=63),
        ),
    ]
