# Generated by Django 5.0.14 on 2026-03-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userprofile_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='display_mode',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Browser (Auto)'), ('accessibility', 'Accessibility (Color-blind friendly)')], default='light', help_text='Preferred display mode for the interface', max_length=20),
        ),
    ]
