# Generated by Django 5.0.14 on 2026-03-24 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_add_display_mode_to_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_demo_account',
            field=models.BooleanField(default=False, help_text='Permanent flag for demo login accounts (Alex, Sam, Jordan). Read-only, zero AI access.'),
        ),
    ]
