# Generated by Django 5.2.3 on 2026-03-25 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userprofile_is_demo_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='demo_task_originals',
            field=models.JSONField(blank=True, default=dict, help_text='Maps task_id→original_assignee_id for demo tasks temporarily assigned to this real user'),
        ),
    ]
