# Generated by Django 5.2.3 on 2026-03-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_add_demo_task_originals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='demo_task_originals',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_viewing_demo',
            field=models.BooleanField(default=False, help_text='Whether user is currently viewing their personal demo sandbox'),
        ),
    ]
