# Generated by Django 5.2.3 on 2026-04-02 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_org_domain_optional_and_org_invitation'),
        ('kanban', '0115_workspace_model_and_fks'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='active_workspace',
            field=models.ForeignKey(blank=True, help_text='The workspace the user is currently viewing. Null = no workspace selected yet.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_users', to='kanban.workspace'),
        ),
    ]
