# Generated by Django 5.2.3 on 2026-05-01 21:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_workspace_model_and_fks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleCalendarToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField(help_text='Google OAuth 2.0 access token.')),
                ('refresh_token', models.TextField(help_text='Google OAuth 2.0 refresh token (long-lived).')),
                ('token_expiry', models.DateTimeField(blank=True, help_text='When the current access token expires.', null=True)),
                ('calendar_id', models.CharField(default='primary', help_text='Google Calendar ID to sync tasks to. "primary" uses the user\'s main calendar.', max_length=255)),
                ('sync_enabled', models.BooleanField(default=True, help_text='Master toggle. When False, no sync happens even if the token is valid.')),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_calendar_token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Google Calendar Token',
                'verbose_name_plural': 'Google Calendar Tokens',
            },
        ),
    ]
