# Generated by Django 5.2.3 on 2026-07-14 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_googlecalendartoken_sync_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='custom_ai_instructions',
            field=models.TextField(blank=True, default='', help_text='Free-text catch-all: anything the AI should always remember about your preferred format', max_length=600),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='response_length',
            field=models.CharField(choices=[('default', 'Default'), ('brief', 'Brief'), ('standard', 'Standard'), ('detailed', 'Detailed')], default='default', help_text='Preferred length/verbosity for AI-generated prose', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='response_structure',
            field=models.CharField(choices=[('default', 'Default'), ('bullets', 'Bullet-heavy'), ('narrative', 'Narrative paragraphs')], default='default', help_text='Preferred structure (bullets vs narrative paragraphs) for AI-generated prose', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='response_tone',
            field=models.CharField(choices=[('default', 'Default'), ('formal', 'Formal'), ('conversational', 'Conversational'), ('executive', 'Executive')], default='default', help_text='Preferred tone for AI-generated prose (briefs, retros, coaching, Spectra)', max_length=20),
        ),
    ]
