# Generated by Django 5.2.3 on 2025-11-09 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreference',
            name='theme',
        ),
    ]
