# Generated by Django 5.2.3 on 2026-01-24 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0002_remove_userpreference_theme'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aiassistantmessage',
            options={'ordering': ['created_at', 'id']},
        ),
    ]
