# Generated by Django 5.2.3 on 2026-01-26 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0003_alter_aiassistantmessage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiassistantsession',
            name='is_demo',
            field=models.BooleanField(default=False, help_text='Is this a demo/example session visible to all users?'),
        ),
    ]
