# Generated by Django 5.2.3 on 2026-02-28 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0004_aiassistantsession_is_demo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAssistantAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='ai_assistant/%Y/%m/%d/')),
                ('filename', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('file_type', models.CharField(help_text='File extension without dot', max_length=10)),
                ('extracted_text', models.TextField(blank=True, default='', help_text='Text extracted from the file at upload time')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='ai_assistant.aiassistantsession')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_assistant_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='aiassistantmessage',
            name='attachment',
            field=models.ForeignKey(blank=True, help_text='File attachment that was analysed in this message turn', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='ai_assistant.aiassistantattachment'),
        ),
    ]
