# Generated by Django 5.2.3 on 2026-03-01 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0005_spectra_attachment'),
        ('kanban', '0076_add_onboarding_workspace_preview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpectraConversationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('normal', 'Normal Q&A'), ('collecting_task', 'Collecting task details'), ('collecting_board', 'Collecting board details'), ('collecting_automation', 'Collecting automation selection'), ('awaiting_confirmation', 'Awaiting user confirmation')], default='normal', max_length=50)),
                ('collected_data', models.JSONField(blank=True, default=dict)),
                ('pending_action', models.CharField(blank=True, choices=[('', 'None'), ('create_task', 'Create Task'), ('create_board', 'Create Board'), ('activate_automation', 'Activate Automation')], default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('board', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spectra_conversation_states', to='kanban.board')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spectra_conversation_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'board')},
            },
        ),
    ]
