# Generated by Django 5.0.14 on 2026-03-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0006_spectra_conversation_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spectraconversationstate',
            name='mode',
            field=models.CharField(choices=[('normal', 'Normal Q&A'), ('collecting_task', 'Collecting task details'), ('collecting_board', 'Collecting board details'), ('collecting_automation', 'Collecting automation selection'), ('collecting_message', 'Collecting message details'), ('collecting_time_entry', 'Collecting time entry details'), ('collecting_event', 'Collecting event details'), ('collecting_retrospective', 'Collecting retrospective details'), ('awaiting_confirmation', 'Awaiting user confirmation')], default='normal', max_length=50),
        ),
        migrations.AlterField(
            model_name='spectraconversationstate',
            name='pending_action',
            field=models.CharField(blank=True, choices=[('', 'None'), ('create_task', 'Create Task'), ('create_board', 'Create Board'), ('activate_automation', 'Activate Automation'), ('send_message', 'Send Message'), ('log_time', 'Log Time'), ('schedule_event', 'Schedule Event'), ('create_retrospective', 'Create Retrospective'), ('create_custom_automation', 'Create Custom Automation'), ('create_scheduled_automation', 'Create Scheduled Automation')], default='', max_length=50),
        ),
    ]
