# Generated by Django 5.0.14 on 2026-03-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0007_extend_spectra_state_for_new_actions'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiassistantsession',
            name='question_count',
            field=models.IntegerField(default=0, help_text='Number of original user questions (excluding follow-ups in multi-step flows)'),
        ),
    ]
