# Generated by Django 5.0.14 on 2026-03-18 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0008_add_question_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spectraconversationstate',
            name='pending_action',
            field=models.CharField(blank=True, choices=[('', 'None'), ('create_task', 'Create Task'), ('create_board', 'Create Board'), ('activate_automation', 'Activate Automation'), ('send_message', 'Send Message'), ('log_time', 'Log Time'), ('schedule_event', 'Schedule Event'), ('create_retrospective', 'Create Retrospective'), ('create_custom_automation', 'Create Custom Automation'), ('create_scheduled_automation', 'Create Scheduled Automation'), ('get_commitment_status', 'Get Commitment Status'), ('list_at_risk_commitments', 'List At-Risk Commitments'), ('place_commitment_bet', 'Place Commitment Bet')], default='', max_length=50),
        ),
    ]
