# Generated by Django 5.0.14 on 2026-03-20 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0010_alter_spectraconversationstate_mode_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aiassistantmessage',
            options={'ordering': ['id']},
        ),
    ]
