# Generated by Django 5.2.3 on 2026-04-04 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0011_alter_aiassistantmessage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spectraconversationstate',
            name='mode',
            field=models.CharField(choices=[('normal', 'Normal Q&A'), ('collecting_task', 'Collecting task details'), ('collecting_board', 'Collecting board details'), ('collecting_automation', 'Collecting automation selection'), ('collecting_message', 'Collecting message details'), ('collecting_time_entry', 'Collecting time entry details'), ('collecting_event', 'Collecting event details'), ('collecting_retrospective', 'Collecting retrospective details'), ('collecting_task_update', 'Collecting task update details'), ('collecting_preset', 'Collecting workspace preset preference'), ('awaiting_confirmation', 'Awaiting user confirmation')], default='normal', max_length=50),
        ),
    ]
