# Generated by Django 5.2.3 on 2026-04-29 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_workspace_model_and_fks'),
        ('ai_assistant', '0012_add_collecting_preset_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationAISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('gemini', 'Google Gemini'), ('openai', 'OpenAI'), ('anthropic', 'Anthropic Claude')], default='gemini', help_text='Organisation-wide active AI provider. Applies to all users unless overridden (when allow_user_provider_override is True).', max_length=20)),
                ('allow_user_provider_override', models.BooleanField(default=False, help_text='When True, Members and Owners may set their own personal provider preference. When False, everyone uses the org-wide provider. Only an Org Admin can change this field.')),
                ('byok_provider', models.CharField(blank=True, choices=[('gemini', 'Google Gemini'), ('openai', 'OpenAI'), ('anthropic', 'Anthropic Claude')], help_text='Which provider the stored BYOK key belongs to.', max_length=20, null=True)),
                ('encrypted_api_key', models.TextField(blank=True, help_text='Fernet-encrypted organisation BYOK API key. NEVER store plain text here. Use AIRouter._encrypt_key() to write and AIRouter._decrypt_key() to read.', null=True)),
                ('key_last_four', models.CharField(blank=True, help_text="Last few visible characters of the BYOK key for safe UI display (e.g. '••••1a3f'). Never store more than this.", max_length=8, null=True)),
                ('key_validated_at', models.DateTimeField(blank=True, help_text='Timestamp when the BYOK key was last successfully validated.', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_settings', to='accounts.organization')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Org Admin who last changed these settings.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_ai_settings_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organisation AI Settings',
                'verbose_name_plural': 'Organisation AI Settings',
            },
        ),
        migrations.CreateModel(
            name='UserAISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_override', models.CharField(choices=[('inherit', 'Inherit from Organisation'), ('gemini', 'Google Gemini'), ('openai', 'OpenAI'), ('anthropic', 'Anthropic Claude')], default='inherit', help_text="User's preferred provider. 'inherit' means follow the org-wide setting. Other values are respected only if org.allow_user_provider_override is True, or this user is an Org Admin.", max_length=20)),
                ('byok_provider', models.CharField(blank=True, choices=[('gemini', 'Google Gemini'), ('openai', 'OpenAI'), ('anthropic', 'Anthropic Claude')], help_text="Which provider the user's personal BYOK key belongs to.", max_length=20, null=True)),
                ('encrypted_api_key', models.TextField(blank=True, help_text='Fernet-encrypted personal BYOK API key. NEVER store plain text here. Use AIRouter._encrypt_key() to write and AIRouter._decrypt_key() to read.', null=True)),
                ('key_last_four', models.CharField(blank=True, help_text="Last few visible characters of the personal BYOK key for safe UI display (e.g. '••••1a3f'). Never store more than this.", max_length=8, null=True)),
                ('key_validated_at', models.DateTimeField(blank=True, help_text='Timestamp when the personal BYOK key was last successfully validated.', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User AI Settings',
                'verbose_name_plural': 'User AI Settings',
            },
        ),
    ]
