# Generated by Django 5.2.3 on 2026-05-20 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0014_add_byok_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectknowledgebase',
            name='embedding',
            field=models.JSONField(blank=True, help_text='Embedding vector for semantic retrieval (list of floats).', null=True),
        ),
        migrations.AddField(
            model_name='projectknowledgebase',
            name='embedding_model',
            field=models.CharField(blank=True, default='', help_text='Model used to generate the embedding (for safe re-indexing).', max_length=64),
        ),
        migrations.AddField(
            model_name='projectknowledgebase',
            name='embedding_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
