# Generated by Django 5.2.3 on 2026-05-21 12:40

import django.db.models.deletion
from django.db import migrations, models


def backfill_workspace(apps, schema_editor):
    """
    Backfill ``workspace`` for existing AIAssistantSession and AIAssistantAnalytics rows.

    Resolution order:
      1. session.board.workspace (the natural mapping)
      2. If board.workspace is null (orphan boards), the board owner's personal
         non-demo workspace via WorkspaceMembership
      3. If is_demo=True, the single demo workspace
      4. Leave null and log to stdout — operator can fix manually
    """
    Session = apps.get_model('ai_assistant', 'AIAssistantSession')
    Analytics = apps.get_model('ai_assistant', 'AIAssistantAnalytics')
    Workspace = apps.get_model('kanban', 'Workspace')
    WorkspaceMembership = apps.get_model('kanban', 'WorkspaceMembership')

    demo_ws = Workspace.objects.filter(is_demo=True).first()
    unresolved_sessions = []

    for session in Session.objects.select_related('board', 'user').iterator():
        ws = None
        if session.board_id and session.board.workspace_id:
            ws = session.board.workspace
        elif session.board_id and session.board.owner_id:
            ws = (
                Workspace.objects.filter(
                    memberships__user_id=session.board.owner_id,
                    is_demo=False,
                    is_active=True,
                )
                .order_by('created_at')
                .first()
            )
        if ws is None and session.is_demo and demo_ws is not None:
            ws = demo_ws
        if ws is None and session.user_id:
            ws = (
                Workspace.objects.filter(
                    memberships__user_id=session.user_id,
                    is_demo=False,
                    is_active=True,
                )
                .order_by('created_at')
                .first()
            )
        if ws is None:
            unresolved_sessions.append(session.id)
            continue
        session.workspace = ws
        session.save(update_fields=['workspace'])

    if unresolved_sessions:
        print(
            f"[migration 0016] WARNING: {len(unresolved_sessions)} AIAssistantSession rows "
            f"could not be assigned a workspace (ids: {unresolved_sessions[:20]}{'...' if len(unresolved_sessions) > 20 else ''}). "
            "They remain null — fix manually or delete."
        )

    unresolved_analytics = 0
    for row in Analytics.objects.select_related('board', 'user').iterator():
        ws = None
        if row.board_id and row.board.workspace_id:
            ws = row.board.workspace
        elif row.board_id and row.board.owner_id:
            ws = (
                Workspace.objects.filter(
                    memberships__user_id=row.board.owner_id,
                    is_demo=False,
                    is_active=True,
                )
                .order_by('created_at')
                .first()
            )
        if ws is None and row.user_id:
            # Analytics rows have no is_demo flag; assume the user's primary non-demo workspace
            ws = (
                Workspace.objects.filter(
                    memberships__user_id=row.user_id,
                    is_demo=False,
                    is_active=True,
                )
                .order_by('created_at')
                .first()
            )
        if ws is None and demo_ws is not None:
            # Last resort — drop into demo so it's visible somewhere, not silently lost
            ws = demo_ws
        if ws is None:
            unresolved_analytics += 1
            continue
        row.workspace = ws
        row.save(update_fields=['workspace'])

    if unresolved_analytics:
        print(
            f"[migration 0016] WARNING: {unresolved_analytics} AIAssistantAnalytics rows "
            "could not be assigned a workspace and remain null."
        )


def reverse_noop(apps, schema_editor):
    """Reverse migration is a no-op — the FK column is dropped by AddField reverse."""
    return


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0015_kb_embeddings'),
        ('kanban', '0140_alter_scopetimelineevent_source_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiassistantanalytics',
            name='workspace',
            field=models.ForeignKey(blank=True, help_text='The workspace this analytics row belongs to. Null only for legacy rows pre-migration.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_analytics', to='kanban.workspace'),
        ),
        migrations.AddField(
            model_name='aiassistantsession',
            name='workspace',
            field=models.ForeignKey(blank=True, help_text='The workspace this session belongs to. Null only for legacy rows pre-migration.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_sessions', to='kanban.workspace'),
        ),
        migrations.RunPython(backfill_workspace, reverse_noop),
    ]
