# Generated by Django 5.2.3 on 2026-06-24 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_googlecalendartoken_sync_status'),
        ('ai_assistant', '0016_add_workspace_to_session_and_analytics'),
        ('kanban', '0154_workspacepreset_per_workspace'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationaisettings',
            options={'verbose_name': 'Workspace AI Settings', 'verbose_name_plural': 'Workspace AI Settings'},
        ),
        migrations.AddField(
            model_name='organizationaisettings',
            name='workspace',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_settings', to='kanban.workspace'),
        ),
        migrations.AlterField(
            model_name='organizationaisettings',
            name='organisation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_settings', to='accounts.organization'),
        ),
    ]
