# Generated by Django 5.2.3 on 2026-01-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_chatmessage_is_read_chatmessage_read_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='ai_summary',
            field=models.CharField(blank=True, help_text='AI-generated concise summary of the notification', max_length=200, null=True),
        ),
    ]
