# Generated by Django 5.2.3 on 2026-02-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_add_ai_summary_to_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='action_url',
            field=models.CharField(blank=True, help_text='Optional URL the notification links to', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('MENTION', 'Mention'), ('COMMENT', 'Comment Reply'), ('CHAT_MESSAGE', 'Chat Message'), ('ACTIVITY', 'Activity Update'), ('TASK_ASSIGNED_CAL', 'Task Assigned via Calendar'), ('EVENT_INVITED', 'Calendar Event Invitation')], max_length=20),
        ),
    ]
