# Generated by Django 5.0.14 on 2026-03-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0006_ai_analysis_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('MENTION', 'Mention'), ('COMMENT', 'Comment Reply'), ('CHAT_MESSAGE', 'Chat Message'), ('ACTIVITY', 'Activity Update'), ('TASK_ASSIGNED_CAL', 'Task Assigned via Calendar'), ('EVENT_INVITED', 'Calendar Event Invitation'), ('ACCESS_REQUEST', 'Access Request'), ('ACCESS_RESPONSE', 'Access Request Response')], max_length=20),
        ),
    ]
