# Generated by Django 5.2.3 on 2026-05-11 02:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    atomic = False  # pre-existing FK integrity issue in DB; safe to skip atomic wrap

    dependencies = [
        ('messaging', '0008_notification_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('MENTION', 'Mention'), ('COMMENT', 'Comment Reply'), ('CHAT_MESSAGE', 'Chat Message'), ('ACTIVITY', 'Activity Update'), ('TASK_ASSIGNED_CAL', 'Task Assigned via Calendar'), ('EVENT_INVITED', 'Calendar Event Invitation'), ('ACCESS_REQUEST', 'Access Request'), ('ACCESS_RESPONSE', 'Access Request Response'), ('CHAT_ROOM_INVITE', 'Chat Room Invitation')], max_length=20),
        ),
        migrations.CreateModel(
            name='ChatRoomInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('chat_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='messaging.chatroom')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_chat_room_invitations', to=settings.AUTH_USER_MODEL)),
                ('invited_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_room_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('chat_room', 'invited_user')},
            },
        ),
    ]
