"""
Django settings for kanban_board project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Gemini API settings
GEMINI_API_KEY = os.getenv('GEMINI_API_KEY', '')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY must be set in environment variables for security
import sys

SECRET_KEY = os.getenv('SECRET_KEY')

# In production, fail if SECRET_KEY not set
if not SECRET_KEY:
    if not os.getenv('DEBUG', 'False').lower() == 'true':
        print("=" * 70)
        print("SECURITY ERROR: SECRET_KEY environment variable not set!")
        print("Please set SECRET_KEY in your .env file before running in production.")
        print("Generate a new key with: python -c 'from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())'")
        print("=" * 70)
        sys.exit(1)
    else:
        # Only use default in development with warning
        print("⚠️  WARNING: Using default SECRET_KEY (development only - NEVER use in production)")
        SECRET_KEY = 'dev-secret-key-change-in-production-' + 'yhj1u7b0_^(b-%5t#n^p!8pzy&%nabpd0*=$7xvfwby&_5_4@c'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').lower() == 'true'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '127.0.0.1,localhost,testserver').split(',')

# Security settings for production
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = 'DENY'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',  # Required for allauth
    
    # Third-party apps
    'crispy_forms',
    'crispy_bootstrap5',
    'colorfield',
    'widget_tweaks',
    'channels',  # Django Channels for WebSockets
    'rest_framework',  # Django REST Framework for API
    'corsheaders',  # Django CORS headers for mobile/PWA support
    'axes',  # django-axes for brute force protection
    'csp',  # django-csp for Content Security Policy
    
    # Django Allauth
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    
    # Local apps
    'accounts',
    'kanban',
    'ai_assistant',
    'messaging',
    'wiki',
    'api',  # RESTful API for external integrations
    'webhooks',  # Webhook system for event-driven integrations
    'analytics',  # Analytics and user feedback system
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Add WhiteNoise for static files in production
    'corsheaders.middleware.CorsMiddleware',  # CORS middleware for mobile/PWA support
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'csp.middleware.CSPMiddleware',  # Content Security Policy
    'allauth.account.middleware.AccountMiddleware',  # Required for django-allauth
    # Demo session management - Must be after SessionMiddleware
    'kanban.middleware.demo_session.DemoSessionMiddleware',
    'kanban.middleware.demo_session.DemoAnalyticsMiddleware',
    # Security and audit logging middleware
    'kanban.audit_middleware.AuditLoggingMiddleware',
    'kanban.audit_middleware.APIRequestLoggingMiddleware',
    # Analytics tracking middleware - SessionTrackingMiddleware must come before SessionTimeoutMiddleware
    'analytics.middleware.SessionTrackingMiddleware',
    'analytics.middleware.SessionTimeoutMiddleware',  # Auto-end inactive sessions
    'kanban.audit_middleware.SecurityMonitoringMiddleware',
    'axes.middleware.AxesMiddleware',  # Brute force protection
]

ROOT_URLCONF = 'kanban_board.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'kanban_board.context_processors.static_version',
                'kanban_board.context_processors.user_preferences',
                'kanban.context_processors.conflict_count',
                'kanban.context_processors.demo_context',  # Demo mode context
            ],
        },
    },
]

WSGI_APPLICATION = 'kanban_board.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
STATIC_ROOT = BASE_DIR / "staticfiles"

# WhiteNoise configuration for static files
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Static files cache busting
STATIC_VERSION = "3"  # Increment this when updating JS/CSS files

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Crispy Forms
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# Authentication settings
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'

# Email Configuration
# For development, use console backend to display emails in terminal
if DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    # Production email settings (configure based on your email provider)
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
    EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
    EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() == 'true'
    EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
    EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')

# Default from email for system emails
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@prizmAI.com')
SERVER_EMAIL = DEFAULT_FROM_EMAIL

# Django Sites Framework (required for allauth)
SITE_ID = 1

# Django Allauth Configuration
AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
)

# Allauth settings (updated for django-allauth 65.9.0+)
ACCOUNT_EMAIL_VERIFICATION = 'optional'  # Can be 'mandatory', 'optional', or 'none'
ACCOUNT_USER_MODEL_USERNAME_FIELD = 'username'
ACCOUNT_USER_MODEL_EMAIL_FIELD = 'email'
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_SESSION_REMEMBER = True

# Updated settings for django-allauth 65.9.0+
ACCOUNT_LOGIN_METHODS = {'email'}  # Replaces ACCOUNT_AUTHENTICATION_METHOD
ACCOUNT_SIGNUP_FIELDS = ['email*', 'username*', 'password1*', 'password2*']  # Replaces ACCOUNT_EMAIL_REQUIRED and ACCOUNT_USERNAME_REQUIRED

# Social account settings
SOCIALACCOUNT_EMAIL_REQUIRED = True
SOCIALACCOUNT_EMAIL_VERIFICATION = 'optional'
SOCIALACCOUNT_QUERY_EMAIL = True
SOCIALACCOUNT_AUTO_SIGNUP = True

# Google OAuth2 settings
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        },
        'OAUTH_PKCE_ENABLED': True,
        'FETCH_USERINFO': True,
    }
}

# Google OAuth2 credentials (to be set in .env file)
GOOGLE_OAUTH2_CLIENT_ID = os.getenv('GOOGLE_OAUTH2_CLIENT_ID', '')
GOOGLE_OAUTH2_CLIENT_SECRET = os.getenv('GOOGLE_OAUTH2_CLIENT_SECRET', '')

# Custom adapters for handling organization assignment
ACCOUNT_ADAPTER = 'accounts.adapters.CustomAccountAdapter'
SOCIALACCOUNT_ADAPTER = 'accounts.adapters.CustomSocialAccountAdapter'

# ============================================
# AI PROJECT ASSISTANT CONFIGURATION
# ============================================

# AI Model API Keys
GEMINI_API_KEY = os.getenv('GEMINI_API_KEY', '')
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY', '')

# Google Custom Search API (for RAG - Retrieval Augmented Generation)
GOOGLE_SEARCH_API_KEY = os.getenv('GOOGLE_SEARCH_API_KEY', '')
GOOGLE_SEARCH_ENGINE_ID = os.getenv('GOOGLE_SEARCH_ENGINE_ID', '')
ENABLE_WEB_SEARCH = os.getenv('ENABLE_WEB_SEARCH', 'True').lower() == 'true'

# AI Assistant Settings
AI_ASSISTANT_CONFIG = {
    'DEFAULT_MODEL': 'gemini',  # 'gemini' or 'openai'
    'MAX_HISTORY_LENGTH': 50,
    'RESPONSE_TIMEOUT': 30,  # seconds
    'ENABLE_WEB_SEARCH': ENABLE_WEB_SEARCH,
    'KB_REFRESH_INTERVAL': 3600,  # 1 hour
    'CACHE_TTL': 3600,  # 1 hour
}

# Logging for AI Assistant
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'ai_assistant.log'),
            'formatter': 'verbose',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'ai_assistant': {
            'handlers': ['file', 'console'],
            'level': os.getenv('LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
        'analytics': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Channels Configuration for WebSockets
ASGI_APPLICATION = 'kanban_board.asgi.application'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [('127.0.0.1', 6379)],
        },
    },
}

# Cache Configuration (for caching AI responses and search results)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
        'TIMEOUT': 300,
        'OPTIONS': {
            'MAX_ENTRIES': 1000
        }
    }
}

# Create logs directory if it doesn't exist
LOGS_DIR = os.path.join(BASE_DIR, 'logs')
if not os.path.exists(LOGS_DIR):
    os.makedirs(LOGS_DIR)

# Celery Configuration
CELERY_BROKER_URL = 'redis://127.0.0.1:6379/0'
CELERY_RESULT_BACKEND = 'redis://127.0.0.1:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True  # Fix Celery 6.0 deprecation warning

# ============================================
# REST FRAMEWORK CONFIGURATION
# ============================================

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'api.v1.authentication.APITokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',
        'user': '1000/hour'
    },
    'EXCEPTION_HANDLER': 'rest_framework.views.exception_handler',
    'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.openapi.AutoSchema',
}

# ============================================
# CORS CONFIGURATION (for Mobile/PWA Support)
# ============================================

# Allow requests from mobile PWA during development
CORS_ALLOWED_ORIGINS = [
    "http://localhost:8080",
    "http://localhost:3000",
    "http://127.0.0.1:8080",
    "http://127.0.0.1:3000",
]

# Allow all origins in development (can be restricted in production)
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True
else:
    # In production, specify exact origins
    CORS_ALLOW_ALL_ORIGINS = False

# Allow credentials (cookies, authorization headers, etc.)
CORS_ALLOW_CREDENTIALS = True

# Allow these HTTP methods
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# Allow these headers
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# ============================================
# CONTENT SECURITY POLICY (CSP) CONFIGURATION
# ============================================

# CSP settings to prevent XSS and other injection attacks
CSP_DEFAULT_SRC = ("'self'",)
CSP_SCRIPT_SRC = (
    "'self'", 
    "'unsafe-inline'",
    "https://cdn.jsdelivr.net", 
    "https://code.jquery.com",
    "https://www.googletagmanager.com",  # Google Analytics
    "https://www.google-analytics.com",  # Google Analytics
)
CSP_STYLE_SRC = (
    "'self'", 
    "'unsafe-inline'", 
    "https://cdn.jsdelivr.net", 
    "https://fonts.googleapis.com", 
    "https://cdnjs.cloudflare.com",
)
CSP_IMG_SRC = (
    "'self'", 
    "data:", 
    "https:",  # Allow all HTTPS images
)
CSP_FONT_SRC = (
    "'self'", 
    "data:", 
    "https://cdn.jsdelivr.net", 
    "https://fonts.gstatic.com", 
    "https://cdnjs.cloudflare.com",
)
CSP_CONNECT_SRC = (
    "'self'", 
    "wss:", 
    "ws:", 
    # Google Analytics
    "https://www.google-analytics.com",
    "https://analytics.google.com",
    "https://www.googletagmanager.com",
)
CSP_FRAME_SRC = (
    "'self'",
)
CSP_FRAME_ANCESTORS = ("'none'",)  # Prevent clickjacking
CSP_BASE_URI = ("'self'",)
CSP_FORM_ACTION = (
    "'self'",
)
CSP_UPGRADE_INSECURE_REQUESTS = not DEBUG  # Upgrade HTTP to HTTPS in production

# Enable CSP reporting (optional - can be configured to send reports)
CSP_REPORT_ONLY = False  # Set to True for testing without enforcement

# ============================================
# DJANGO-AXES CONFIGURATION (Brute Force Protection)
# ============================================

# Add django.contrib.auth.backends.ModelBackend to AUTHENTICATION_BACKENDS
AUTHENTICATION_BACKENDS = (
    'axes.backends.AxesStandaloneBackend',  # AxesStandaloneBackend should be first
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
)

# Axes Configuration
AXES_FAILURE_LIMIT = 5  # Number of failed login attempts before lockout
AXES_COOLOFF_TIME = 1  # Hours to wait before allowing login again after lockout
AXES_LOCK_OUT_AT_FAILURE = True  # Lock out after failure limit
AXES_LOCKOUT_PARAMETERS = ["username", "ip_address"]  # Lock by username and IP (replaces deprecated AXES_LOCK_OUT_BY_COMBINATION_USER_AND_IP)
AXES_RESET_ON_SUCCESS = True  # Reset failed attempts on successful login
AXES_ENABLE_ADMIN = True  # Enable axes in admin
AXES_VERBOSE = True  # Verbose logging
AXES_LOCKOUT_TEMPLATE = None  # Use default lockout handling
AXES_LOCKOUT_URL = None  # Redirect URL after lockout (None = stay on same page)

# Use cache for tracking attempts (faster than database)
AXES_CACHE = 'default'

# Additional rate limiting
AXES_RESET_COOL_OFF = True  # Automatically reset after cooloff period

# ============================================
# ANALYTICS & FEEDBACK CONFIGURATION
# ============================================

# Google Analytics 4
GA4_MEASUREMENT_ID = os.getenv('GA4_MEASUREMENT_ID', '')  # e.g., 'G-XXXXXXXXXX'

# Session tracking settings
ANALYTICS_SESSION_TIMEOUT = 30  # Minutes of inactivity before session timeout
ANALYTICS_TRACK_ANONYMOUS = True  # Track anonymous users
ANALYTICS_MIN_ENGAGEMENT_FOR_FEEDBACK = 0  # Minimum minutes before showing feedback form (0 = always show)
