# Generated by Django 5.2.3 on 2026-05-13 02:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirementhistory',
            name='new_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('implemented', 'Implemented'), ('verified', 'Verified')], max_length=20),
        ),
        migrations.AlterField(
            model_name='requirementhistory',
            name='old_status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('implemented', 'Implemented'), ('verified', 'Verified')], max_length=20),
        ),
        migrations.CreateModel(
            name='RequirementAICache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(choices=[('quality', 'Quality Check'), ('criteria', 'Acceptance Criteria'), ('impact', 'Impact Analysis')], max_length=20)),
                ('result_json', models.TextField()),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_cache', to='requirements.requirement')),
            ],
            options={
                'ordering': ['-generated_at'],
                'unique_together': {('requirement', 'analysis_type')},
            },
        ),
    ]
