# Generated by Django 5.2.3 on 2026-05-01 21:30

import django.db.models.deletion
import secrets
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kanban', '0126_alter_userfavorite_favorite_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_full_name', models.CharField(help_text='GitHub repository in "owner/repo" format, e.g. "acme/backend"', max_length=255)),
                ('webhook_secret', models.CharField(default=secrets.token_hex, help_text='Secret token shared with GitHub for HMAC-SHA256 signature verification.', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('board', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='github_integration', to='kanban.board')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='github_integrations_created', to=settings.AUTH_USER_MODEL)),
                ('in_review_column', models.ForeignKey(blank=True, help_text="Tasks matching a PR will be moved to this column (e.g. 'In Review').", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='github_review_integrations', to='kanban.column')),
            ],
            options={
                'verbose_name': 'GitHub Integration',
                'verbose_name_plural': 'GitHub Integrations',
            },
        ),
    ]
