# Generated by Django 5.2.3 on 2026-07-14 22:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
        ('kanban', '0165_calendarevent_cloned_from'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('jira', 'Jira'), ('trello', 'Trello'), ('asana', 'Asana'), ('monday', 'Monday.com'), ('clickup', 'ClickUp'), ('notion', 'Notion')], max_length=20)),
                ('base_url', models.URLField(blank=True, help_text="Provider site/base URL, e.g. 'https://acme.atlassian.net' for Jira Cloud.", max_length=500)),
                ('account_email', models.EmailField(blank=True, help_text='Account email used with the API token (Basic auth for Jira Cloud).', max_length=254)),
                ('encrypted_api_token', models.TextField(help_text='Fernet-encrypted API token. Never store or log the raw token.')),
                ('token_last_four', models.CharField(blank=True, help_text='Last 4 chars of the token, for display only.', max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('error', 'Error'), ('syncing', 'Syncing')], default='connected', max_length=20)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_connections_created', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(help_text='The workspace (tenant) this connection belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='source_connections', to='kanban.workspace')),
            ],
            options={
                'verbose_name': 'Source Connection',
                'verbose_name_plural': 'Source Connections',
                'ordering': ['-created_at'],
            },
        ),
    ]
