# Generated by Django 5.0.14 on 2026-03-05 13:40

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('kanban', '0083_alter_systemauditlog_action_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionCenterBriefing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('headline', models.CharField(max_length=300)),
                ('briefing', models.TextField()),
                ('estimated_minutes', models.PositiveSmallIntegerField(default=0)),
                ('top_priority_board', models.CharField(blank=True, max_length=200)),
                ('item_counts', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_briefings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='DecisionCenterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_digest_enabled', models.BooleanField(default=True)),
                ('digest_time', models.TimeField(default=datetime.time(8, 0))),
                ('show_awareness_items', models.BooleanField(default=True)),
                ('show_quick_wins', models.BooleanField(default=True)),
                ('min_overdue_days', models.PositiveSmallIntegerField(default=2)),
                ('min_stale_days', models.PositiveSmallIntegerField(default=14)),
                ('budget_alert_threshold', models.PositiveSmallIntegerField(default=80)),
                ('deadline_warning_days', models.PositiveSmallIntegerField(default=7)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='decision_center_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Decision Center Settings',
                'verbose_name_plural': 'Decision Center Settings',
            },
        ),
        migrations.CreateModel(
            name='DecisionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('conflict', 'Unresolved Conflict'), ('premortem_risk', 'Pre-Mortem Risk Unacknowledged'), ('overdue_task', 'Overdue Tasks'), ('overallocated', 'Team Member Over-Allocated'), ('scope_change', 'Scope Change Detected'), ('budget_threshold', 'Budget Threshold Crossed'), ('deadline_approaching', 'Deadline Approaching'), ('unassigned_task', 'Unassigned Tasks'), ('stale_task', 'Stale Tasks'), ('ai_recommendation', 'AI Recommendation Pending'), ('memory_captured', 'New Knowledge Memory Captured')], max_length=30)),
                ('priority_level', models.CharField(choices=[('action_required', 'Action Required'), ('awareness', 'Awareness Only'), ('quick_win', 'Quick Win')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('suggested_action', models.TextField(blank=True)),
                ('source_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('context_data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved'), ('snoozed', 'Snoozed'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('snoozed_until', models.DateTimeField(blank=True, null=True)),
                ('estimated_minutes', models.PositiveSmallIntegerField(default=2)),
                ('board', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='decision_items', to='kanban.board')),
                ('created_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_items', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_decisions', to=settings.AUTH_USER_MODEL)),
                ('source_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['status', 'priority_level', '-created_at'],
                'indexes': [models.Index(fields=['created_for', 'status'], name='decision_ce_created_dd5650_idx'), models.Index(fields=['created_for', 'status', 'priority_level'], name='decision_ce_created_12add8_idx')],
            },
        ),
    ]
