# Generated by Django 5.2.3 on 2026-05-09 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decision_center', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='decisionitem',
            name='archive_reason',
            field=models.CharField(blank=True, choices=[('resolved', 'Resolved'), ('dismissed', 'Dismissed')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='decisionitem',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
