# Generated by Django 5.2.3 on 2026-06-18 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decision_center', '0002_archive_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='decisioncenterbriefing',
            name='is_demo',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
